project_name: chirpstack-application-server

builds:
  - main: cmd/chirpstack-application-server/main.go
    binary: chirpstack-application-server
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

release:
  disable: true

nfpms:
  - id: chirpstack-application-server
    vendor: ChirpStack
    homepage: https://www.chirpstack.io/
    maintainer: Orne Brocaar <info@brocaar.com>
    description: ChirpStack Application Server
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: "packaging/files/chirpstack-application-server.rotate"
        dst: "/etc/logrotate.d/chirpstack-application-server"
      - src: "packaging/files/chirpstack-application-server.init"
        dst: "/usr/lib/chirpstack-application-server/scripts/chirpstack-application-server.init"
      - src: "packaging/files/chirpstack-application-server.service"
        dst: "/usr/lib/chirpstack-application-server/scripts/chirpstack-application-server.service"
      - src: "packaging/files/chirpstack-application-server.toml"
        dst: "/etc/chirpstack-application-server/chirpstack-application-server.toml"
        type: config
    scripts:
      preinstall: "packaging/scripts/pre-install.sh"
      postinstall: "packaging/scripts/post-install.sh"
      postremove: "packaging/scripts/post-remove.sh"
