project_name: lora-app-server

builds:
  - main: cmd/lora-app-server/main.go
    binary: lora-app-server
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

release:
  disable: true

nfpm:
  vendor: LoRa Server project
  homepage: https://www.loraserver.io/
  maintainer: Orne Brocaar <info@brocaar.com>
  description: LoRa App Server
  license: MIT
  formats:
    - deb
  bindir: /usr/bin
  files:
    "packaging/files/lora-app-server.rotate": "/etc/logrotate.d/lora-app-server"
    "packaging/files/lora-app-server.init": "/usr/lib/lora-app-server/scripts/lora-app-server.init"
    "packaging/files/lora-app-server.service": "/usr/lib/lora-app-server/scripts/lora-app-server.service"
  scripts:
    postinstall: "packaging/scripts/post-install.sh"
    postremove: "packaging/scripts/post-remove.sh"
