version: "2"
services:
  chirpstack-application-server:
    build: 
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack-application-server
      - ../chirpstack-api/go:/chirpstack-api/go
    links:
      - postgres
      - redis
      - mosquitto
      - rabbitmq
    environment:
      - TEST_POSTGRES_DSN=postgres://chirpstack_as:chirpstack_as@postgres/chirpstack_as?sslmode=disable
      - TEST_REDIS_URL=redis://redis:6379
      - TEST_MQTT_SERVER=tcp://mosquitto:1883
      - TEST_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:4-alpine

  mosquitto:
    image: eclipse-mosquitto

  rabbitmq:
    image: rabbitmq:3-alpine
