version: "2"
services:
  appserver:
    build: 
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/lora-app-server
    links:
      - postgres
      - redis
      - mosquitto
    environment:
      - TEST_POSTGRES_DSN=postgres://loraserver_as:loraserver_as@postgres/loraserver_as?sslmode=disable
      - TEST_REDIS_URL=redis://redis:6379
      - TEST_MQTT_SERVER=tcp://mosquitto:1883

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:4-alpine

  mosquitto:
    image: eclipse-mosquitto
