// Code generated by protoc-gen-go.
// source: application.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateApplicationRequest struct {
	// Name of the application (must be unique).
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Description of the application.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *CreateApplicationRequest) Reset()                    { *m = CreateApplicationRequest{} }
func (m *CreateApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateApplicationRequest) ProtoMessage()               {}
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *CreateApplicationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateApplicationRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateApplicationResponse struct {
	// ID of the application that was created.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateApplicationResponse) Reset()                    { *m = CreateApplicationResponse{} }
func (m *CreateApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateApplicationResponse) ProtoMessage()               {}
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *CreateApplicationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetApplicationRequest struct {
	// Name of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetApplicationRequest) Reset()                    { *m = GetApplicationRequest{} }
func (m *GetApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationRequest) ProtoMessage()               {}
func (*GetApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GetApplicationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetApplicationResponse struct {
	// ID of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Name of the application.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Description of the application.
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *GetApplicationResponse) Reset()                    { *m = GetApplicationResponse{} }
func (m *GetApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationResponse) ProtoMessage()               {}
func (*GetApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GetApplicationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetApplicationResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetApplicationResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateApplicationRequest struct {
	// ID of the application to update.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Name of the application (must be unique).
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Description of the application.
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *UpdateApplicationRequest) Reset()                    { *m = UpdateApplicationRequest{} }
func (m *UpdateApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateApplicationRequest) ProtoMessage()               {}
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *UpdateApplicationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateApplicationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateApplicationRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateApplicationResponse struct {
}

func (m *UpdateApplicationResponse) Reset()                    { *m = UpdateApplicationResponse{} }
func (m *UpdateApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateApplicationResponse) ProtoMessage()               {}
func (*UpdateApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

type DeleteApplicationRequest struct {
	// ID of the application.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteApplicationRequest) Reset()                    { *m = DeleteApplicationRequest{} }
func (m *DeleteApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteApplicationRequest) ProtoMessage()               {}
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *DeleteApplicationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteApplicationResponse struct {
}

func (m *DeleteApplicationResponse) Reset()                    { *m = DeleteApplicationResponse{} }
func (m *DeleteApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteApplicationResponse) ProtoMessage()               {}
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

type ListApplicationRequest struct {
	// Max number of applications to return in the result-test.
	Limit int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *ListApplicationRequest) Reset()                    { *m = ListApplicationRequest{} }
func (m *ListApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationRequest) ProtoMessage()               {}
func (*ListApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *ListApplicationRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListApplicationRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListApplicationResponse struct {
	// Total number of applications available within the result-set.
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	// Applications within this result-set.
	Result []*GetApplicationResponse `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListApplicationResponse) Reset()                    { *m = ListApplicationResponse{} }
func (m *ListApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationResponse) ProtoMessage()               {}
func (*ListApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *ListApplicationResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListApplicationResponse) GetResult() []*GetApplicationResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListApplicationUsersRequest struct {
	// The id of the application
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Max number of applications to return in the result-test.
	Limit int64 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	// Offset in the result-set (for pagination).
	Offset int64 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *ListApplicationUsersRequest) Reset()                    { *m = ListApplicationUsersRequest{} }
func (m *ListApplicationUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationUsersRequest) ProtoMessage()               {}
func (*ListApplicationUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *ListApplicationUsersRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListApplicationUsersRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListApplicationUsersRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetApplicationUserResponse struct {
	// The id of the user
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The username for the user
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	// Has admin rights.
	IsAdmin bool `protobuf:"varint,3,opt,name=isAdmin" json:"isAdmin,omitempty"`
}

func (m *GetApplicationUserResponse) Reset()                    { *m = GetApplicationUserResponse{} }
func (m *GetApplicationUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationUserResponse) ProtoMessage()               {}
func (*GetApplicationUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *GetApplicationUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetApplicationUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetApplicationUserResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type ListApplicationUsersResponse struct {
	// Total number of applications available within the result-set.
	TotalCount int32 `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	// Applications within this result-set.
	Result []*GetApplicationUserResponse `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListApplicationUsersResponse) Reset()                    { *m = ListApplicationUsersResponse{} }
func (m *ListApplicationUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationUsersResponse) ProtoMessage()               {}
func (*ListApplicationUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *ListApplicationUsersResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListApplicationUsersResponse) GetResult() []*GetApplicationUserResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type AddApplicationUserRequest struct {
	// The application to be set to allow these users
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// User id
	UserID int64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
	// admin rights?
	IsAdmin bool `protobuf:"varint,3,opt,name=isAdmin" json:"isAdmin,omitempty"`
}

func (m *AddApplicationUserRequest) Reset()                    { *m = AddApplicationUserRequest{} }
func (m *AddApplicationUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AddApplicationUserRequest) ProtoMessage()               {}
func (*AddApplicationUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *AddApplicationUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddApplicationUserRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *AddApplicationUserRequest) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type ApplicationUserRequest struct {
	// The application id
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The user id
	UserID int64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *ApplicationUserRequest) Reset()                    { *m = ApplicationUserRequest{} }
func (m *ApplicationUserRequest) String() string            { return proto.CompactTextString(m) }
func (*ApplicationUserRequest) ProtoMessage()               {}
func (*ApplicationUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *ApplicationUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ApplicationUserRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type UpdateApplicationUserRequest struct {
	// The application id
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// The user id
	UserID int64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
	// Is admin?
	IsAdmin bool `protobuf:"varint,3,opt,name=isAdmin" json:"isAdmin,omitempty"`
}

func (m *UpdateApplicationUserRequest) Reset()                    { *m = UpdateApplicationUserRequest{} }
func (m *UpdateApplicationUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateApplicationUserRequest) ProtoMessage()               {}
func (*UpdateApplicationUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *UpdateApplicationUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateApplicationUserRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UpdateApplicationUserRequest) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type EmptyApplicationUserResponse struct {
}

func (m *EmptyApplicationUserResponse) Reset()                    { *m = EmptyApplicationUserResponse{} }
func (m *EmptyApplicationUserResponse) String() string            { return proto.CompactTextString(m) }
func (*EmptyApplicationUserResponse) ProtoMessage()               {}
func (*EmptyApplicationUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func init() {
	proto.RegisterType((*CreateApplicationRequest)(nil), "api.CreateApplicationRequest")
	proto.RegisterType((*CreateApplicationResponse)(nil), "api.CreateApplicationResponse")
	proto.RegisterType((*GetApplicationRequest)(nil), "api.GetApplicationRequest")
	proto.RegisterType((*GetApplicationResponse)(nil), "api.GetApplicationResponse")
	proto.RegisterType((*UpdateApplicationRequest)(nil), "api.UpdateApplicationRequest")
	proto.RegisterType((*UpdateApplicationResponse)(nil), "api.UpdateApplicationResponse")
	proto.RegisterType((*DeleteApplicationRequest)(nil), "api.DeleteApplicationRequest")
	proto.RegisterType((*DeleteApplicationResponse)(nil), "api.DeleteApplicationResponse")
	proto.RegisterType((*ListApplicationRequest)(nil), "api.ListApplicationRequest")
	proto.RegisterType((*ListApplicationResponse)(nil), "api.ListApplicationResponse")
	proto.RegisterType((*ListApplicationUsersRequest)(nil), "api.ListApplicationUsersRequest")
	proto.RegisterType((*GetApplicationUserResponse)(nil), "api.GetApplicationUserResponse")
	proto.RegisterType((*ListApplicationUsersResponse)(nil), "api.ListApplicationUsersResponse")
	proto.RegisterType((*AddApplicationUserRequest)(nil), "api.AddApplicationUserRequest")
	proto.RegisterType((*ApplicationUserRequest)(nil), "api.ApplicationUserRequest")
	proto.RegisterType((*UpdateApplicationUserRequest)(nil), "api.UpdateApplicationUserRequest")
	proto.RegisterType((*EmptyApplicationUserResponse)(nil), "api.EmptyApplicationUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Application service

type ApplicationClient interface {
	// Create creates the given application.
	Create(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*CreateApplicationResponse, error)
	// Get returns the requested application.
	Get(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*GetApplicationResponse, error)
	// Update updates the given application.
	Update(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*UpdateApplicationResponse, error)
	// Delete deletes the given application.
	Delete(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error)
	// List lists the available applications.
	List(ctx context.Context, in *ListApplicationRequest, opts ...grpc.CallOption) (*ListApplicationResponse, error)
	// ListUsers lists the users for an application.
	ListUsers(ctx context.Context, in *ListApplicationUsersRequest, opts ...grpc.CallOption) (*ListApplicationUsersResponse, error)
	// AddUser adds a user to an application.
	AddUser(ctx context.Context, in *AddApplicationUserRequest, opts ...grpc.CallOption) (*EmptyApplicationUserResponse, error)
	// GetUser gets the user that is associated with the application.
	GetUser(ctx context.Context, in *ApplicationUserRequest, opts ...grpc.CallOption) (*GetApplicationUserResponse, error)
	// UpdateUser sets the user's access to the associated application.
	UpdateUser(ctx context.Context, in *UpdateApplicationUserRequest, opts ...grpc.CallOption) (*EmptyApplicationUserResponse, error)
	// DeleteUser deletes the user's access to the associated application.
	DeleteUser(ctx context.Context, in *ApplicationUserRequest, opts ...grpc.CallOption) (*EmptyApplicationUserResponse, error)
}

type applicationClient struct {
	cc *grpc.ClientConn
}

func NewApplicationClient(cc *grpc.ClientConn) ApplicationClient {
	return &applicationClient{cc}
}

func (c *applicationClient) Create(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*CreateApplicationResponse, error) {
	out := new(CreateApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) Get(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*GetApplicationResponse, error) {
	out := new(GetApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) Update(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*UpdateApplicationResponse, error) {
	out := new(UpdateApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) Delete(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error) {
	out := new(DeleteApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) List(ctx context.Context, in *ListApplicationRequest, opts ...grpc.CallOption) (*ListApplicationResponse, error) {
	out := new(ListApplicationResponse)
	err := grpc.Invoke(ctx, "/api.Application/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) ListUsers(ctx context.Context, in *ListApplicationUsersRequest, opts ...grpc.CallOption) (*ListApplicationUsersResponse, error) {
	out := new(ListApplicationUsersResponse)
	err := grpc.Invoke(ctx, "/api.Application/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) AddUser(ctx context.Context, in *AddApplicationUserRequest, opts ...grpc.CallOption) (*EmptyApplicationUserResponse, error) {
	out := new(EmptyApplicationUserResponse)
	err := grpc.Invoke(ctx, "/api.Application/AddUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) GetUser(ctx context.Context, in *ApplicationUserRequest, opts ...grpc.CallOption) (*GetApplicationUserResponse, error) {
	out := new(GetApplicationUserResponse)
	err := grpc.Invoke(ctx, "/api.Application/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) UpdateUser(ctx context.Context, in *UpdateApplicationUserRequest, opts ...grpc.CallOption) (*EmptyApplicationUserResponse, error) {
	out := new(EmptyApplicationUserResponse)
	err := grpc.Invoke(ctx, "/api.Application/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationClient) DeleteUser(ctx context.Context, in *ApplicationUserRequest, opts ...grpc.CallOption) (*EmptyApplicationUserResponse, error) {
	out := new(EmptyApplicationUserResponse)
	err := grpc.Invoke(ctx, "/api.Application/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Application service

type ApplicationServer interface {
	// Create creates the given application.
	Create(context.Context, *CreateApplicationRequest) (*CreateApplicationResponse, error)
	// Get returns the requested application.
	Get(context.Context, *GetApplicationRequest) (*GetApplicationResponse, error)
	// Update updates the given application.
	Update(context.Context, *UpdateApplicationRequest) (*UpdateApplicationResponse, error)
	// Delete deletes the given application.
	Delete(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error)
	// List lists the available applications.
	List(context.Context, *ListApplicationRequest) (*ListApplicationResponse, error)
	// ListUsers lists the users for an application.
	ListUsers(context.Context, *ListApplicationUsersRequest) (*ListApplicationUsersResponse, error)
	// AddUser adds a user to an application.
	AddUser(context.Context, *AddApplicationUserRequest) (*EmptyApplicationUserResponse, error)
	// GetUser gets the user that is associated with the application.
	GetUser(context.Context, *ApplicationUserRequest) (*GetApplicationUserResponse, error)
	// UpdateUser sets the user's access to the associated application.
	UpdateUser(context.Context, *UpdateApplicationUserRequest) (*EmptyApplicationUserResponse, error)
	// DeleteUser deletes the user's access to the associated application.
	DeleteUser(context.Context, *ApplicationUserRequest) (*EmptyApplicationUserResponse, error)
}

func RegisterApplicationServer(s *grpc.Server, srv ApplicationServer) {
	s.RegisterService(&_Application_serviceDesc, srv)
}

func _Application_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).Create(ctx, req.(*CreateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).Get(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).Update(ctx, req.(*UpdateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).Delete(ctx, req.(*DeleteApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).List(ctx, req.(*ListApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).ListUsers(ctx, req.(*ListApplicationUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddApplicationUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).AddUser(ctx, req.(*AddApplicationUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).GetUser(ctx, req.(*ApplicationUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).UpdateUser(ctx, req.(*UpdateApplicationUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Application_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Application/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServer).DeleteUser(ctx, req.(*ApplicationUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Application_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Application",
	HandlerType: (*ApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Application_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Application_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Application_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Application_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Application_List_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Application_ListUsers_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _Application_AddUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Application_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Application_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Application_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application.proto",
}

func init() { proto.RegisterFile("application.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 678 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x4e, 0xd4, 0x40,
	0x14, 0xce, 0x6e, 0xa1, 0xc0, 0x21, 0x31, 0x61, 0xd4, 0xda, 0xed, 0xd6, 0x95, 0x9d, 0x68, 0x20,
	0x6b, 0x64, 0x0d, 0x5c, 0x98, 0x78, 0xe5, 0x06, 0x94, 0x98, 0x78, 0x61, 0x9a, 0x70, 0xa5, 0x12,
	0x0a, 0x1d, 0xc8, 0x98, 0x6e, 0x5b, 0x3b, 0x53, 0x8c, 0x21, 0xdc, 0x18, 0xdf, 0xc0, 0x47, 0xf3,
	0x15, 0x7c, 0x02, 0x9f, 0xc0, 0x74, 0x66, 0x58, 0xba, 0xdb, 0x99, 0xb2, 0x46, 0xee, 0x76, 0x3a,
	0x67, 0xbe, 0xef, 0x7c, 0xdf, 0xf9, 0xc9, 0xc2, 0x5a, 0x98, 0x65, 0x31, 0x3d, 0x09, 0x39, 0x4d,
	0x93, 0xad, 0x2c, 0x4f, 0x79, 0x8a, 0xac, 0x30, 0xa3, 0x9e, 0x7f, 0x96, 0xa6, 0x67, 0x31, 0x19,
	0x86, 0x19, 0x1d, 0x86, 0x49, 0x92, 0x72, 0x11, 0xc1, 0x64, 0x08, 0x7e, 0x0f, 0xee, 0x6e, 0x4e,
	0x42, 0x4e, 0x46, 0xd7, 0xaf, 0x03, 0xf2, 0xa5, 0x20, 0x8c, 0x23, 0x04, 0x0b, 0x49, 0x38, 0x26,
	0x6e, 0x6b, 0xbd, 0xb5, 0xb9, 0x12, 0x88, 0xdf, 0x68, 0x1d, 0x56, 0x23, 0xc2, 0x4e, 0x72, 0x9a,
	0x95, 0x91, 0x6e, 0x5b, 0x5c, 0x55, 0x3f, 0xe1, 0xa7, 0xd0, 0xd1, 0x20, 0xb2, 0x2c, 0x4d, 0x18,
	0x41, 0x77, 0xa0, 0x4d, 0x23, 0x01, 0x68, 0x05, 0x6d, 0x1a, 0xe1, 0x0d, 0xb8, 0xbf, 0x4f, 0xb8,
	0x86, 0x7b, 0x36, 0xf0, 0x10, 0x9c, 0xd9, 0x40, 0x3d, 0xe4, 0x24, 0xeb, 0xb6, 0x39, 0x6b, 0xab,
	0x9e, 0xf5, 0x11, 0xb8, 0x07, 0x59, 0xa4, 0xf7, 0xe1, 0x76, 0x18, 0xba, 0xd0, 0xd1, 0x30, 0x48,
	0x11, 0x78, 0x00, 0xee, 0x1e, 0x89, 0xc9, 0x3c, 0xf4, 0x25, 0x90, 0x26, 0x56, 0x01, 0xbd, 0x01,
	0xe7, 0x1d, 0x65, 0x3a, 0x47, 0xef, 0xc1, 0x62, 0x4c, 0xc7, 0x94, 0x2b, 0x24, 0x79, 0x40, 0x0e,
	0xd8, 0xe9, 0xe9, 0x29, 0x23, 0x5c, 0xa8, 0xb1, 0x02, 0x75, 0xc2, 0x09, 0x3c, 0xa8, 0xe1, 0x28,
	0xc3, 0x7b, 0x00, 0x3c, 0xe5, 0x61, 0xbc, 0x9b, 0x16, 0xc9, 0x15, 0x5a, 0xe5, 0x0b, 0xda, 0x01,
	0x3b, 0x27, 0xac, 0x88, 0x4b, 0x48, 0x6b, 0x73, 0x75, 0xbb, 0xbb, 0x15, 0x66, 0x74, 0x4b, 0x5f,
	0xbd, 0x40, 0x85, 0xe2, 0x0f, 0xd0, 0x9d, 0xe1, 0x3b, 0x60, 0x24, 0x67, 0xa6, 0x12, 0x4c, 0xc4,
	0xb4, 0xf5, 0x62, 0xac, 0x29, 0x31, 0xc7, 0xe0, 0x4d, 0xd3, 0x97, 0xd8, 0xc6, 0x06, 0xf2, 0x60,
	0xb9, 0x60, 0x24, 0xaf, 0x94, 0x78, 0x72, 0x46, 0x2e, 0x2c, 0x51, 0x36, 0x8a, 0xc6, 0x54, 0x96,
	0x78, 0x39, 0xb8, 0x3a, 0xe2, 0xaf, 0xe0, 0xeb, 0x05, 0x18, 0x5d, 0x5b, 0x9c, 0x72, 0xed, 0xc5,
	0x8c, 0x6b, 0x8f, 0x34, 0xae, 0x55, 0xd3, 0x9e, 0x38, 0xf7, 0x09, 0x3a, 0xa3, 0x28, 0xaa, 0x45,
	0xe9, 0x7d, 0x73, 0xc0, 0x2e, 0xb5, 0xbc, 0xdd, 0xbb, 0x2a, 0xb7, 0x3c, 0x35, 0xe8, 0x7a, 0x05,
	0xce, 0xff, 0x61, 0xe3, 0x23, 0xf0, 0x6b, 0x8d, 0x7f, 0xbb, 0x39, 0xf6, 0xc0, 0x7f, 0x3d, 0xce,
	0xf8, 0x37, 0x83, 0x55, 0xdb, 0x7f, 0x96, 0x61, 0xb5, 0x72, 0x87, 0x08, 0xd8, 0x72, 0x45, 0xa1,
	0x87, 0xc2, 0x65, 0xd3, 0x06, 0xf4, 0x7a, 0xa6, 0x6b, 0x35, 0x6d, 0xfe, 0xf7, 0x5f, 0xbf, 0x7f,
	0xb6, 0x1d, 0xbc, 0x26, 0xb7, 0xeb, 0x75, 0x04, 0x7b, 0xd9, 0x1a, 0xa0, 0x43, 0xb0, 0xf6, 0x09,
	0x47, 0x9e, 0xb6, 0xff, 0x25, 0x41, 0xd3, 0x6c, 0xe0, 0x9e, 0x40, 0x77, 0x91, 0x53, 0x43, 0x1f,
	0x5e, 0xd0, 0xe8, 0x12, 0x7d, 0x06, 0x5b, 0x1a, 0xab, 0x64, 0x98, 0x16, 0x98, 0x92, 0x61, 0xde,
	0x3e, 0x7d, 0x41, 0xd4, 0xf5, 0x0c, 0x44, 0xa5, 0x96, 0x33, 0xb0, 0xe5, 0xd2, 0x51, 0x5c, 0xa6,
	0x6d, 0xa5, 0xb8, 0xcc, 0x0b, 0x4a, 0x89, 0x1a, 0x98, 0x44, 0x7d, 0x84, 0x85, 0x72, 0x8e, 0x90,
	0x74, 0x46, 0xbf, 0xcb, 0x3c, 0x5f, 0x7f, 0xa9, 0x28, 0x3a, 0x82, 0xe2, 0x2e, 0xaa, 0x57, 0x05,
	0x9d, 0xc3, 0x4a, 0xf9, 0x4a, 0x8c, 0x26, 0x5a, 0xd7, 0xa1, 0x54, 0xd7, 0x8e, 0xd7, 0x6f, 0x88,
	0x50, 0x64, 0x8f, 0x05, 0x59, 0x0f, 0xf9, 0x7a, 0x3d, 0xc3, 0x42, 0x50, 0x15, 0xb0, 0x34, 0x8a,
	0xa2, 0xf2, 0x25, 0x92, 0x06, 0x19, 0x47, 0x56, 0x71, 0x36, 0xf5, 0x33, 0xde, 0x10, 0x9c, 0x7d,
	0xdc, 0xc8, 0x59, 0x56, 0xed, 0x1c, 0x96, 0xf6, 0x89, 0x50, 0xab, 0xfc, 0x34, 0x70, 0xde, 0xb4,
	0x6c, 0xf0, 0x33, 0xc1, 0xb8, 0x81, 0x9e, 0x34, 0x31, 0x0e, 0x2f, 0xe4, 0xa4, 0x5e, 0xa2, 0x1f,
	0x2d, 0x00, 0xd9, 0x6e, 0x82, 0xbb, 0xaf, 0xef, 0xbf, 0x7f, 0x54, 0xfd, 0x5c, 0xe4, 0x30, 0xf0,
	0xe6, 0xcb, 0xa1, 0x94, 0x7f, 0x01, 0x20, 0x1b, 0xf1, 0x66, 0x07, 0xe6, 0xe0, 0x57, 0x1e, 0x0c,
	0xe6, 0xe3, 0x3f, 0xb6, 0xc5, 0x1f, 0xac, 0x9d, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xbc,
	0xb9, 0x15, 0x98, 0x09, 0x00, 0x00,
}
