// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Modulation int32

const (
	// LoRa
	Modulation_LORA Modulation = 0
	// FSK
	Modulation_FSK Modulation = 1
)

var Modulation_name = map[int32]string{
	0: "LORA",
	1: "FSK",
}
var Modulation_value = map[string]int32{
	"LORA": 0,
	"FSK":  1,
}

func (x Modulation) String() string {
	return proto.EnumName(Modulation_name, int32(x))
}
func (Modulation) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type CreateGatewayRequest struct {
	// Hex encoded mac address.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	// A name for the gateway
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// A description for the gateway
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// Latitude of the gateway -90 to 90
	Latitude float64 `protobuf:"fixed64,4,opt,name=latitude" json:"latitude,omitempty"`
	// Longitude of the gateway -180 to 180
	Longitude float64 `protobuf:"fixed64,5,opt,name=longitude" json:"longitude,omitempty"`
	// Altitude of the gateway in meters
	Altitude float64 `protobuf:"fixed64,6,opt,name=altitude" json:"altitude,omitempty"`
	// ID of the organization to which this gateway belongs.
	OrganizationID int64 `protobuf:"varint,7,opt,name=organizationID" json:"organizationID,omitempty"`
	// ID of the channel-configuration.
	ChannelConfigurationID int64 `protobuf:"varint,8,opt,name=channelConfigurationID" json:"channelConfigurationID,omitempty"`
	// Gateway sends out a periodic ping.
	Ping bool `protobuf:"varint,9,opt,name=ping" json:"ping,omitempty"`
	// ID of the network-server to which the gateway is connected.
	NetworkServerID int64 `protobuf:"varint,10,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *CreateGatewayRequest) Reset()                    { *m = CreateGatewayRequest{} }
func (m *CreateGatewayRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateGatewayRequest) ProtoMessage()               {}
func (*CreateGatewayRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *CreateGatewayRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *CreateGatewayRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGatewayRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateGatewayRequest) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *CreateGatewayRequest) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *CreateGatewayRequest) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *CreateGatewayRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

func (m *CreateGatewayRequest) GetChannelConfigurationID() int64 {
	if m != nil {
		return m.ChannelConfigurationID
	}
	return 0
}

func (m *CreateGatewayRequest) GetPing() bool {
	if m != nil {
		return m.Ping
	}
	return false
}

func (m *CreateGatewayRequest) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type CreateGatewayResponse struct {
}

func (m *CreateGatewayResponse) Reset()                    { *m = CreateGatewayResponse{} }
func (m *CreateGatewayResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateGatewayResponse) ProtoMessage()               {}
func (*CreateGatewayResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

type GetGatewayRequest struct {
	// Hex encoded mac address of the node.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
}

func (m *GetGatewayRequest) Reset()                    { *m = GetGatewayRequest{} }
func (m *GetGatewayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetGatewayRequest) ProtoMessage()               {}
func (*GetGatewayRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *GetGatewayRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type GetGatewayResponse struct {
	// Hex encoded mac address.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	// A name for the gateway
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// A description for the gateway
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// Latitude of the gateway -90.0 to 90.0
	Latitude float64 `protobuf:"fixed64,4,opt,name=latitude" json:"latitude,omitempty"`
	// Longitude of the gateway -180.0 to 180.0
	Longitude float64 `protobuf:"fixed64,5,opt,name=longitude" json:"longitude,omitempty"`
	// Altitude of the gateway in meters
	Altitude float64 `protobuf:"fixed64,6,opt,name=altitude" json:"altitude,omitempty"`
	// Creation timestamp of the record
	CreatedAt string `protobuf:"bytes,7,opt,name=createdAt" json:"createdAt,omitempty"`
	// Last update timestamp of the record
	UpdatedAt string `protobuf:"bytes,8,opt,name=updatedAt" json:"updatedAt,omitempty"`
	// The timestamp of the first data from the gateway.
	FirstSeenAt string `protobuf:"bytes,9,opt,name=firstSeenAt" json:"firstSeenAt,omitempty"`
	// The timestamp of the most recent data from the gateway.
	LastSeenAt string `protobuf:"bytes,10,opt,name=lastSeenAt" json:"lastSeenAt,omitempty"`
	// ID of the organization to which this gateway belongs.
	OrganizationID int64 `protobuf:"varint,11,opt,name=organizationID" json:"organizationID,omitempty"`
	// ID of the channel-configuration.
	ChannelConfigurationID int64 `protobuf:"varint,12,opt,name=channelConfigurationID" json:"channelConfigurationID,omitempty"`
	// Gateway sends out a periodic ping.
	Ping bool `protobuf:"varint,13,opt,name=ping" json:"ping,omitempty"`
	// ID of the network-server to which the gateway is connected.
	NetworkServerID int64 `protobuf:"varint,14,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *GetGatewayResponse) Reset()                    { *m = GetGatewayResponse{} }
func (m *GetGatewayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetGatewayResponse) ProtoMessage()               {}
func (*GetGatewayResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *GetGatewayResponse) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *GetGatewayResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetGatewayResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetGatewayResponse) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GetGatewayResponse) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *GetGatewayResponse) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *GetGatewayResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetGatewayResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetGatewayResponse) GetFirstSeenAt() string {
	if m != nil {
		return m.FirstSeenAt
	}
	return ""
}

func (m *GetGatewayResponse) GetLastSeenAt() string {
	if m != nil {
		return m.LastSeenAt
	}
	return ""
}

func (m *GetGatewayResponse) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

func (m *GetGatewayResponse) GetChannelConfigurationID() int64 {
	if m != nil {
		return m.ChannelConfigurationID
	}
	return 0
}

func (m *GetGatewayResponse) GetPing() bool {
	if m != nil {
		return m.Ping
	}
	return false
}

func (m *GetGatewayResponse) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type DeleteGatewayRequest struct {
	// Hex encoded mac address.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
}

func (m *DeleteGatewayRequest) Reset()                    { *m = DeleteGatewayRequest{} }
func (m *DeleteGatewayRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteGatewayRequest) ProtoMessage()               {}
func (*DeleteGatewayRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *DeleteGatewayRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type GenerateGatewayTokenRequest struct {
	// Hex encoded mac address.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
}

func (m *GenerateGatewayTokenRequest) Reset()                    { *m = GenerateGatewayTokenRequest{} }
func (m *GenerateGatewayTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*GenerateGatewayTokenRequest) ProtoMessage()               {}
func (*GenerateGatewayTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *GenerateGatewayTokenRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type GenerateGatewayTokenResponse struct {
	// Generated token.
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GenerateGatewayTokenResponse) Reset()                    { *m = GenerateGatewayTokenResponse{} }
func (m *GenerateGatewayTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*GenerateGatewayTokenResponse) ProtoMessage()               {}
func (*GenerateGatewayTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *GenerateGatewayTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeleteGatewayResponse struct {
}

func (m *DeleteGatewayResponse) Reset()                    { *m = DeleteGatewayResponse{} }
func (m *DeleteGatewayResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteGatewayResponse) ProtoMessage()               {}
func (*DeleteGatewayResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

type ListGatewayRequest struct {
	// Max number of nodes to return in the result-set.
	Limit int32 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset of the result-set (for pagination).
	Offset int32 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	// ID of the organization for which to filter on, when left blank the
	// response will return all gateways to which the user has access to.
	OrganizationID int64 `protobuf:"varint,3,opt,name=organizationID" json:"organizationID,omitempty"`
	// Search on name or gateway MAC (optional).
	Search string `protobuf:"bytes,4,opt,name=search" json:"search,omitempty"`
}

func (m *ListGatewayRequest) Reset()                    { *m = ListGatewayRequest{} }
func (m *ListGatewayRequest) String() string            { return proto.CompactTextString(m) }
func (*ListGatewayRequest) ProtoMessage()               {}
func (*ListGatewayRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *ListGatewayRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListGatewayRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListGatewayRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

func (m *ListGatewayRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListGatewayItem struct {
	// Hex encoded mac address.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	// A name for the gateway
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// A description for the gateway
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// Creation timestamp of the record
	CreatedAt string `protobuf:"bytes,4,opt,name=createdAt" json:"createdAt,omitempty"`
	// Last update timestamp of the record
	UpdatedAt string `protobuf:"bytes,5,opt,name=updatedAt" json:"updatedAt,omitempty"`
	// ID of the organization to which this gateway belongs.
	OrganizationID int64 `protobuf:"varint,6,opt,name=organizationID" json:"organizationID,omitempty"`
	// ID of the network-server to which the gateway is connected.
	NetworkServerID int64 `protobuf:"varint,7,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *ListGatewayItem) Reset()                    { *m = ListGatewayItem{} }
func (m *ListGatewayItem) String() string            { return proto.CompactTextString(m) }
func (*ListGatewayItem) ProtoMessage()               {}
func (*ListGatewayItem) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *ListGatewayItem) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *ListGatewayItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListGatewayItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ListGatewayItem) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ListGatewayItem) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ListGatewayItem) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

func (m *ListGatewayItem) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type ListGatewayResponse struct {
	// Total number of nodes available within the result-set.
	TotalCount int32 `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	// Nodes within this result-set.
	Result []*ListGatewayItem `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListGatewayResponse) Reset()                    { *m = ListGatewayResponse{} }
func (m *ListGatewayResponse) String() string            { return proto.CompactTextString(m) }
func (*ListGatewayResponse) ProtoMessage()               {}
func (*ListGatewayResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *ListGatewayResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListGatewayResponse) GetResult() []*ListGatewayItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateGatewayRequest struct {
	// Hex encoded mac address.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	// A name for the gateway
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// A description for the gateway
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// Latitude of the gateway -90.0 to 90.0
	Latitude float64 `protobuf:"fixed64,4,opt,name=latitude" json:"latitude,omitempty"`
	// Longitude of the gateway -180.0 to 180.0
	Longitude float64 `protobuf:"fixed64,5,opt,name=longitude" json:"longitude,omitempty"`
	// Altitude of the gateway in meters
	Altitude float64 `protobuf:"fixed64,6,opt,name=altitude" json:"altitude,omitempty"`
	// ID of the organization to which this gateway belongs.
	OrganizationID int64 `protobuf:"varint,7,opt,name=organizationID" json:"organizationID,omitempty"`
	// ID of the channel-configuration.
	ChannelConfigurationID int64 `protobuf:"varint,8,opt,name=channelConfigurationID" json:"channelConfigurationID,omitempty"`
	// Gateway sends out a periodic ping.
	Ping bool `protobuf:"varint,9,opt,name=ping" json:"ping,omitempty"`
}

func (m *UpdateGatewayRequest) Reset()                    { *m = UpdateGatewayRequest{} }
func (m *UpdateGatewayRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateGatewayRequest) ProtoMessage()               {}
func (*UpdateGatewayRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11} }

func (m *UpdateGatewayRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *UpdateGatewayRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateGatewayRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateGatewayRequest) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *UpdateGatewayRequest) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *UpdateGatewayRequest) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *UpdateGatewayRequest) GetOrganizationID() int64 {
	if m != nil {
		return m.OrganizationID
	}
	return 0
}

func (m *UpdateGatewayRequest) GetChannelConfigurationID() int64 {
	if m != nil {
		return m.ChannelConfigurationID
	}
	return 0
}

func (m *UpdateGatewayRequest) GetPing() bool {
	if m != nil {
		return m.Ping
	}
	return false
}

type UpdateGatewayResponse struct {
}

func (m *UpdateGatewayResponse) Reset()                    { *m = UpdateGatewayResponse{} }
func (m *UpdateGatewayResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateGatewayResponse) ProtoMessage()               {}
func (*UpdateGatewayResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12} }

type GatewayStats struct {
	// Timestamp of the (aggregated) measurement.
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// Packets received by the gateway.
	RxPacketsReceived int32 `protobuf:"varint,2,opt,name=rxPacketsReceived" json:"rxPacketsReceived,omitempty"`
	// Packets received by the gateway that passed the CRC check.
	RxPacketsReceivedOK int32 `protobuf:"varint,3,opt,name=rxPacketsReceivedOK" json:"rxPacketsReceivedOK,omitempty"`
	// Packets received by the gateway for transmission.
	TxPacketsReceived int32 `protobuf:"varint,4,opt,name=txPacketsReceived" json:"txPacketsReceived,omitempty"`
	// Packets transmitted by the gateway.
	TxPacketsEmitted int32 `protobuf:"varint,5,opt,name=txPacketsEmitted" json:"txPacketsEmitted,omitempty"`
}

func (m *GatewayStats) Reset()                    { *m = GatewayStats{} }
func (m *GatewayStats) String() string            { return proto.CompactTextString(m) }
func (*GatewayStats) ProtoMessage()               {}
func (*GatewayStats) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{13} }

func (m *GatewayStats) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *GatewayStats) GetRxPacketsReceived() int32 {
	if m != nil {
		return m.RxPacketsReceived
	}
	return 0
}

func (m *GatewayStats) GetRxPacketsReceivedOK() int32 {
	if m != nil {
		return m.RxPacketsReceivedOK
	}
	return 0
}

func (m *GatewayStats) GetTxPacketsReceived() int32 {
	if m != nil {
		return m.TxPacketsReceived
	}
	return 0
}

func (m *GatewayStats) GetTxPacketsEmitted() int32 {
	if m != nil {
		return m.TxPacketsEmitted
	}
	return 0
}

type GetGatewayStatsRequest struct {
	// Hex encoded mac address.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	// Aggregation interval.  One of "second", "minute", "hour", "day", "week",
	// "month", "quarter", "year".  Case insensitive.
	Interval string `protobuf:"bytes,2,opt,name=interval" json:"interval,omitempty"`
	// Timestamp to start from.
	StartTimestamp string `protobuf:"bytes,3,opt,name=startTimestamp" json:"startTimestamp,omitempty"`
	// Timestamp until to get from.
	EndTimestamp string `protobuf:"bytes,4,opt,name=endTimestamp" json:"endTimestamp,omitempty"`
}

func (m *GetGatewayStatsRequest) Reset()                    { *m = GetGatewayStatsRequest{} }
func (m *GetGatewayStatsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetGatewayStatsRequest) ProtoMessage()               {}
func (*GetGatewayStatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{14} }

func (m *GetGatewayStatsRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *GetGatewayStatsRequest) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

func (m *GetGatewayStatsRequest) GetStartTimestamp() string {
	if m != nil {
		return m.StartTimestamp
	}
	return ""
}

func (m *GetGatewayStatsRequest) GetEndTimestamp() string {
	if m != nil {
		return m.EndTimestamp
	}
	return ""
}

type GetGatewayStatsResponse struct {
	Result []*GatewayStats `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *GetGatewayStatsResponse) Reset()                    { *m = GetGatewayStatsResponse{} }
func (m *GetGatewayStatsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetGatewayStatsResponse) ProtoMessage()               {}
func (*GetGatewayStatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{15} }

func (m *GetGatewayStatsResponse) GetResult() []*GatewayStats {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateChannelConfigurationRequest struct {
	// Name of the channel-configuration.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Channels active in this configuration. These channel indices must map
	// to the channel numbers as specified in the LoRaWAN Regional Parameters.
	Channels []int32 `protobuf:"varint,2,rep,packed,name=channels" json:"channels,omitempty"`
	// Network-server id.
	NetworkServerID int64 `protobuf:"varint,3,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *CreateChannelConfigurationRequest) Reset()         { *m = CreateChannelConfigurationRequest{} }
func (m *CreateChannelConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateChannelConfigurationRequest) ProtoMessage()    {}
func (*CreateChannelConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{16}
}

func (m *CreateChannelConfigurationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateChannelConfigurationRequest) GetChannels() []int32 {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *CreateChannelConfigurationRequest) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type CreateChannelConfigurationResponse struct {
	// ID of the channel-configuration.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateChannelConfigurationResponse) Reset()         { *m = CreateChannelConfigurationResponse{} }
func (m *CreateChannelConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateChannelConfigurationResponse) ProtoMessage()    {}
func (*CreateChannelConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{17}
}

func (m *CreateChannelConfigurationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetChannelConfigurationRequest struct {
	// ID of the channel-configuration.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Network-server id.
	NetworkServerID int64 `protobuf:"varint,2,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *GetChannelConfigurationRequest) Reset()                    { *m = GetChannelConfigurationRequest{} }
func (m *GetChannelConfigurationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetChannelConfigurationRequest) ProtoMessage()               {}
func (*GetChannelConfigurationRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{18} }

func (m *GetChannelConfigurationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetChannelConfigurationRequest) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type GetChannelConfigurationResponse struct {
	// ID of the channel-configuration.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Name of the channel-configuration.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Channels active in this configuration. These channel indices must map
	// to the channel numbers as specified in the LoRaWAN Regional Parameters.
	Channels []int32 `protobuf:"varint,3,rep,packed,name=channels" json:"channels,omitempty"`
	// The timestamp when the channel-configuration was created.
	CreatedAt string `protobuf:"bytes,4,opt,name=createdAt" json:"createdAt,omitempty"`
	// The timestamp when the channel-configuration was last updated.
	UpdatedAt string `protobuf:"bytes,5,opt,name=updatedAt" json:"updatedAt,omitempty"`
	// Network-server id.
	NetworkServerID int64 `protobuf:"varint,6,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *GetChannelConfigurationResponse) Reset()         { *m = GetChannelConfigurationResponse{} }
func (m *GetChannelConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*GetChannelConfigurationResponse) ProtoMessage()    {}
func (*GetChannelConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{19}
}

func (m *GetChannelConfigurationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetChannelConfigurationResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetChannelConfigurationResponse) GetChannels() []int32 {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *GetChannelConfigurationResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetChannelConfigurationResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetChannelConfigurationResponse) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type UpdateChannelConfigurationRequest struct {
	// ID of the channel-configuration.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Name of the channel-configuration.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Channels active in this configuration. These channel indices must map
	// to the channel numbers as specified in the LoRaWAN Regional Parameters.
	Channels []int32 `protobuf:"varint,3,rep,packed,name=channels" json:"channels,omitempty"`
	// Network-server id.
	NetworkServerID int64 `protobuf:"varint,4,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *UpdateChannelConfigurationRequest) Reset()         { *m = UpdateChannelConfigurationRequest{} }
func (m *UpdateChannelConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateChannelConfigurationRequest) ProtoMessage()    {}
func (*UpdateChannelConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{20}
}

func (m *UpdateChannelConfigurationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateChannelConfigurationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateChannelConfigurationRequest) GetChannels() []int32 {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *UpdateChannelConfigurationRequest) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type UpdateChannelConfigurationResponse struct {
}

func (m *UpdateChannelConfigurationResponse) Reset()         { *m = UpdateChannelConfigurationResponse{} }
func (m *UpdateChannelConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateChannelConfigurationResponse) ProtoMessage()    {}
func (*UpdateChannelConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{21}
}

type DeleteChannelConfigurationRequest struct {
	// ID of the channel-configuration.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Network-server id.
	NetworkServerID int64 `protobuf:"varint,2,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *DeleteChannelConfigurationRequest) Reset()         { *m = DeleteChannelConfigurationRequest{} }
func (m *DeleteChannelConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteChannelConfigurationRequest) ProtoMessage()    {}
func (*DeleteChannelConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{22}
}

func (m *DeleteChannelConfigurationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteChannelConfigurationRequest) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type DeleteChannelConfigurationResponse struct {
}

func (m *DeleteChannelConfigurationResponse) Reset()         { *m = DeleteChannelConfigurationResponse{} }
func (m *DeleteChannelConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteChannelConfigurationResponse) ProtoMessage()    {}
func (*DeleteChannelConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{23}
}

type ListChannelConfigurationsRequest struct {
	// Network-server id.
	NetworkServerID int64 `protobuf:"varint,1,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *ListChannelConfigurationsRequest) Reset()         { *m = ListChannelConfigurationsRequest{} }
func (m *ListChannelConfigurationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListChannelConfigurationsRequest) ProtoMessage()    {}
func (*ListChannelConfigurationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{24}
}

func (m *ListChannelConfigurationsRequest) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type ListChannelConfigurationsResponse struct {
	// Result-set.
	Result []*GetChannelConfigurationResponse `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *ListChannelConfigurationsResponse) Reset()         { *m = ListChannelConfigurationsResponse{} }
func (m *ListChannelConfigurationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListChannelConfigurationsResponse) ProtoMessage()    {}
func (*ListChannelConfigurationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{25}
}

func (m *ListChannelConfigurationsResponse) GetResult() []*GetChannelConfigurationResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateExtraChannelRequest struct {
	// ID of the channel-configuration.
	ChannelConfigurationID int64 `protobuf:"varint,1,opt,name=channelConfigurationID" json:"channelConfigurationID,omitempty"`
	// Modulation.
	Modulation Modulation `protobuf:"varint,2,opt,name=modulation,enum=api.Modulation" json:"modulation,omitempty"`
	// Frequency.
	Frequency int32 `protobuf:"varint,3,opt,name=frequency" json:"frequency,omitempty"`
	// Bandwidth.
	BandWidth int32 `protobuf:"varint,4,opt,name=bandWidth" json:"bandWidth,omitempty"`
	// Bit rate (in case of FSK modulation).
	BitRate int32 `protobuf:"varint,5,opt,name=bitRate" json:"bitRate,omitempty"`
	// Spread-factors (in case of LoRa modulation).
	SpreadFactors []int32 `protobuf:"varint,6,rep,packed,name=spreadFactors" json:"spreadFactors,omitempty"`
	// Network-server id.
	NetworkServerID int64 `protobuf:"varint,7,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *CreateExtraChannelRequest) Reset()                    { *m = CreateExtraChannelRequest{} }
func (m *CreateExtraChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateExtraChannelRequest) ProtoMessage()               {}
func (*CreateExtraChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{26} }

func (m *CreateExtraChannelRequest) GetChannelConfigurationID() int64 {
	if m != nil {
		return m.ChannelConfigurationID
	}
	return 0
}

func (m *CreateExtraChannelRequest) GetModulation() Modulation {
	if m != nil {
		return m.Modulation
	}
	return Modulation_LORA
}

func (m *CreateExtraChannelRequest) GetFrequency() int32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *CreateExtraChannelRequest) GetBandWidth() int32 {
	if m != nil {
		return m.BandWidth
	}
	return 0
}

func (m *CreateExtraChannelRequest) GetBitRate() int32 {
	if m != nil {
		return m.BitRate
	}
	return 0
}

func (m *CreateExtraChannelRequest) GetSpreadFactors() []int32 {
	if m != nil {
		return m.SpreadFactors
	}
	return nil
}

func (m *CreateExtraChannelRequest) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type CreateExtraChannelResponse struct {
	// ID of the extra channel.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateExtraChannelResponse) Reset()                    { *m = CreateExtraChannelResponse{} }
func (m *CreateExtraChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateExtraChannelResponse) ProtoMessage()               {}
func (*CreateExtraChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{27} }

func (m *CreateExtraChannelResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateExtraChannelRequest struct {
	// ID of the extra channel.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// ID of the channel-configuration.
	ChannelConfigurationID int64 `protobuf:"varint,2,opt,name=channelConfigurationID" json:"channelConfigurationID,omitempty"`
	// Modulation.
	Modulation Modulation `protobuf:"varint,3,opt,name=modulation,enum=api.Modulation" json:"modulation,omitempty"`
	// Frequency.
	Frequency int32 `protobuf:"varint,4,opt,name=frequency" json:"frequency,omitempty"`
	// Bandwidth.
	BandWidth int32 `protobuf:"varint,5,opt,name=bandWidth" json:"bandWidth,omitempty"`
	// Bit rate (in case of FSK modulation).
	BitRate int32 `protobuf:"varint,6,opt,name=bitRate" json:"bitRate,omitempty"`
	// Spread-factors (in case of LoRa modulation).
	SpreadFactors []int32 `protobuf:"varint,7,rep,packed,name=spreadFactors" json:"spreadFactors,omitempty"`
	// Network-server id.
	NetworkServerID int64 `protobuf:"varint,8,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *UpdateExtraChannelRequest) Reset()                    { *m = UpdateExtraChannelRequest{} }
func (m *UpdateExtraChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateExtraChannelRequest) ProtoMessage()               {}
func (*UpdateExtraChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{28} }

func (m *UpdateExtraChannelRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateExtraChannelRequest) GetChannelConfigurationID() int64 {
	if m != nil {
		return m.ChannelConfigurationID
	}
	return 0
}

func (m *UpdateExtraChannelRequest) GetModulation() Modulation {
	if m != nil {
		return m.Modulation
	}
	return Modulation_LORA
}

func (m *UpdateExtraChannelRequest) GetFrequency() int32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *UpdateExtraChannelRequest) GetBandWidth() int32 {
	if m != nil {
		return m.BandWidth
	}
	return 0
}

func (m *UpdateExtraChannelRequest) GetBitRate() int32 {
	if m != nil {
		return m.BitRate
	}
	return 0
}

func (m *UpdateExtraChannelRequest) GetSpreadFactors() []int32 {
	if m != nil {
		return m.SpreadFactors
	}
	return nil
}

func (m *UpdateExtraChannelRequest) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type UpdateExtraChannelResponse struct {
}

func (m *UpdateExtraChannelResponse) Reset()                    { *m = UpdateExtraChannelResponse{} }
func (m *UpdateExtraChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateExtraChannelResponse) ProtoMessage()               {}
func (*UpdateExtraChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{29} }

type DeleteExtraChannelRequest struct {
	// ID of the extra channel.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Network-server id.
	NetworkServerID int64 `protobuf:"varint,2,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *DeleteExtraChannelRequest) Reset()                    { *m = DeleteExtraChannelRequest{} }
func (m *DeleteExtraChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteExtraChannelRequest) ProtoMessage()               {}
func (*DeleteExtraChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{30} }

func (m *DeleteExtraChannelRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteExtraChannelRequest) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type DeleteExtraChannelResponse struct {
}

func (m *DeleteExtraChannelResponse) Reset()                    { *m = DeleteExtraChannelResponse{} }
func (m *DeleteExtraChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteExtraChannelResponse) ProtoMessage()               {}
func (*DeleteExtraChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{31} }

type GetExtraChannelResponse struct {
	// ID of the extra channel.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// ID of the channel-configuration.
	ChannelConfigurationID int64 `protobuf:"varint,2,opt,name=channelConfigurationID" json:"channelConfigurationID,omitempty"`
	// Created-at timestamp.
	CreatedAt string `protobuf:"bytes,3,opt,name=createdAt" json:"createdAt,omitempty"`
	// Updated-at timestamp.
	UpdatedAt string `protobuf:"bytes,4,opt,name=updatedAt" json:"updatedAt,omitempty"`
	// Modulation.
	Modulation Modulation `protobuf:"varint,5,opt,name=modulation,enum=api.Modulation" json:"modulation,omitempty"`
	// Frequency.
	Frequency int32 `protobuf:"varint,6,opt,name=frequency" json:"frequency,omitempty"`
	// Bandwidth.
	Bandwidth int32 `protobuf:"varint,7,opt,name=bandwidth" json:"bandwidth,omitempty"`
	// Bit rate (in case of FSK modulation).
	BitRate int32 `protobuf:"varint,8,opt,name=bitRate" json:"bitRate,omitempty"`
	// Spread-factors (in case of LoRa modulation).
	SpreadFactors []int32 `protobuf:"varint,9,rep,packed,name=spreadFactors" json:"spreadFactors,omitempty"`
}

func (m *GetExtraChannelResponse) Reset()                    { *m = GetExtraChannelResponse{} }
func (m *GetExtraChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*GetExtraChannelResponse) ProtoMessage()               {}
func (*GetExtraChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{32} }

func (m *GetExtraChannelResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetExtraChannelResponse) GetChannelConfigurationID() int64 {
	if m != nil {
		return m.ChannelConfigurationID
	}
	return 0
}

func (m *GetExtraChannelResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetExtraChannelResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetExtraChannelResponse) GetModulation() Modulation {
	if m != nil {
		return m.Modulation
	}
	return Modulation_LORA
}

func (m *GetExtraChannelResponse) GetFrequency() int32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *GetExtraChannelResponse) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *GetExtraChannelResponse) GetBitRate() int32 {
	if m != nil {
		return m.BitRate
	}
	return 0
}

func (m *GetExtraChannelResponse) GetSpreadFactors() []int32 {
	if m != nil {
		return m.SpreadFactors
	}
	return nil
}

type GetExtraChannelsForChannelConfigurationIDRequest struct {
	// ID of the channel-configuration.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Network-server id.
	NetworkServerID int64 `protobuf:"varint,2,opt,name=networkServerID" json:"networkServerID,omitempty"`
}

func (m *GetExtraChannelsForChannelConfigurationIDRequest) Reset() {
	*m = GetExtraChannelsForChannelConfigurationIDRequest{}
}
func (m *GetExtraChannelsForChannelConfigurationIDRequest) String() string {
	return proto.CompactTextString(m)
}
func (*GetExtraChannelsForChannelConfigurationIDRequest) ProtoMessage() {}
func (*GetExtraChannelsForChannelConfigurationIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{33}
}

func (m *GetExtraChannelsForChannelConfigurationIDRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetExtraChannelsForChannelConfigurationIDRequest) GetNetworkServerID() int64 {
	if m != nil {
		return m.NetworkServerID
	}
	return 0
}

type GetExtraChannelsForChannelConfigurationIDResponse struct {
	// Result-set.
	Result []*GetExtraChannelResponse `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *GetExtraChannelsForChannelConfigurationIDResponse) Reset() {
	*m = GetExtraChannelsForChannelConfigurationIDResponse{}
}
func (m *GetExtraChannelsForChannelConfigurationIDResponse) String() string {
	return proto.CompactTextString(m)
}
func (*GetExtraChannelsForChannelConfigurationIDResponse) ProtoMessage() {}
func (*GetExtraChannelsForChannelConfigurationIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{34}
}

func (m *GetExtraChannelsForChannelConfigurationIDResponse) GetResult() []*GetExtraChannelResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type PingRX struct {
	// Hex encoded mac address.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	// RSSI.
	Rssi int32 `protobuf:"varint,2,opt,name=rssi" json:"rssi,omitempty"`
	// LoRa SNR.
	LoraSNR float64 `protobuf:"fixed64,3,opt,name=loraSNR" json:"loraSNR,omitempty"`
	// Latitude of the gateway -90.0 to 90.0.
	Latitude float64 `protobuf:"fixed64,4,opt,name=latitude" json:"latitude,omitempty"`
	// Longitude of the gateway -180.0 to 180.0.
	Longitude float64 `protobuf:"fixed64,5,opt,name=longitude" json:"longitude,omitempty"`
	// Altitude of the gateway in meters.
	Altitude float64 `protobuf:"fixed64,6,opt,name=altitude" json:"altitude,omitempty"`
}

func (m *PingRX) Reset()                    { *m = PingRX{} }
func (m *PingRX) String() string            { return proto.CompactTextString(m) }
func (*PingRX) ProtoMessage()               {}
func (*PingRX) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{35} }

func (m *PingRX) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *PingRX) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *PingRX) GetLoraSNR() float64 {
	if m != nil {
		return m.LoraSNR
	}
	return 0
}

func (m *PingRX) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PingRX) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *PingRX) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

type GetLastPingRequest struct {
	// Hex encoded mac address.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
}

func (m *GetLastPingRequest) Reset()                    { *m = GetLastPingRequest{} }
func (m *GetLastPingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLastPingRequest) ProtoMessage()               {}
func (*GetLastPingRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{36} }

func (m *GetLastPingRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type GetLastPingResponse struct {
	// Created at.
	CreatedAt string `protobuf:"bytes,1,opt,name=createdAt" json:"createdAt,omitempty"`
	// Frequency.
	Frequency uint32 `protobuf:"varint,2,opt,name=frequency" json:"frequency,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,3,opt,name=dr" json:"dr,omitempty"`
	// Gateways and meta-data of reception.
	PingRX []*PingRX `protobuf:"bytes,4,rep,name=pingRX" json:"pingRX,omitempty"`
}

func (m *GetLastPingResponse) Reset()                    { *m = GetLastPingResponse{} }
func (m *GetLastPingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLastPingResponse) ProtoMessage()               {}
func (*GetLastPingResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{37} }

func (m *GetLastPingResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetLastPingResponse) GetFrequency() uint32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *GetLastPingResponse) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *GetLastPingResponse) GetPingRX() []*PingRX {
	if m != nil {
		return m.PingRX
	}
	return nil
}

type StreamGatewayFrameLogsRequest struct {
	// Hex encoded mac.
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
}

func (m *StreamGatewayFrameLogsRequest) Reset()                    { *m = StreamGatewayFrameLogsRequest{} }
func (m *StreamGatewayFrameLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamGatewayFrameLogsRequest) ProtoMessage()               {}
func (*StreamGatewayFrameLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{38} }

func (m *StreamGatewayFrameLogsRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type StreamGatewayFrameLogsResponse struct {
	// Contains zero or one uplink frame.
	UplinkFrames []*UplinkFrameLog `protobuf:"bytes,1,rep,name=uplinkFrames" json:"uplinkFrames,omitempty"`
	// Contains zero or one downlink frame.
	DownlinkFrames []*DownlinkFrameLog `protobuf:"bytes,2,rep,name=downlinkFrames" json:"downlinkFrames,omitempty"`
}

func (m *StreamGatewayFrameLogsResponse) Reset()                    { *m = StreamGatewayFrameLogsResponse{} }
func (m *StreamGatewayFrameLogsResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamGatewayFrameLogsResponse) ProtoMessage()               {}
func (*StreamGatewayFrameLogsResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{39} }

func (m *StreamGatewayFrameLogsResponse) GetUplinkFrames() []*UplinkFrameLog {
	if m != nil {
		return m.UplinkFrames
	}
	return nil
}

func (m *StreamGatewayFrameLogsResponse) GetDownlinkFrames() []*DownlinkFrameLog {
	if m != nil {
		return m.DownlinkFrames
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateGatewayRequest)(nil), "api.CreateGatewayRequest")
	proto.RegisterType((*CreateGatewayResponse)(nil), "api.CreateGatewayResponse")
	proto.RegisterType((*GetGatewayRequest)(nil), "api.GetGatewayRequest")
	proto.RegisterType((*GetGatewayResponse)(nil), "api.GetGatewayResponse")
	proto.RegisterType((*DeleteGatewayRequest)(nil), "api.DeleteGatewayRequest")
	proto.RegisterType((*GenerateGatewayTokenRequest)(nil), "api.GenerateGatewayTokenRequest")
	proto.RegisterType((*GenerateGatewayTokenResponse)(nil), "api.GenerateGatewayTokenResponse")
	proto.RegisterType((*DeleteGatewayResponse)(nil), "api.DeleteGatewayResponse")
	proto.RegisterType((*ListGatewayRequest)(nil), "api.ListGatewayRequest")
	proto.RegisterType((*ListGatewayItem)(nil), "api.ListGatewayItem")
	proto.RegisterType((*ListGatewayResponse)(nil), "api.ListGatewayResponse")
	proto.RegisterType((*UpdateGatewayRequest)(nil), "api.UpdateGatewayRequest")
	proto.RegisterType((*UpdateGatewayResponse)(nil), "api.UpdateGatewayResponse")
	proto.RegisterType((*GatewayStats)(nil), "api.GatewayStats")
	proto.RegisterType((*GetGatewayStatsRequest)(nil), "api.GetGatewayStatsRequest")
	proto.RegisterType((*GetGatewayStatsResponse)(nil), "api.GetGatewayStatsResponse")
	proto.RegisterType((*CreateChannelConfigurationRequest)(nil), "api.CreateChannelConfigurationRequest")
	proto.RegisterType((*CreateChannelConfigurationResponse)(nil), "api.CreateChannelConfigurationResponse")
	proto.RegisterType((*GetChannelConfigurationRequest)(nil), "api.GetChannelConfigurationRequest")
	proto.RegisterType((*GetChannelConfigurationResponse)(nil), "api.GetChannelConfigurationResponse")
	proto.RegisterType((*UpdateChannelConfigurationRequest)(nil), "api.UpdateChannelConfigurationRequest")
	proto.RegisterType((*UpdateChannelConfigurationResponse)(nil), "api.UpdateChannelConfigurationResponse")
	proto.RegisterType((*DeleteChannelConfigurationRequest)(nil), "api.DeleteChannelConfigurationRequest")
	proto.RegisterType((*DeleteChannelConfigurationResponse)(nil), "api.DeleteChannelConfigurationResponse")
	proto.RegisterType((*ListChannelConfigurationsRequest)(nil), "api.ListChannelConfigurationsRequest")
	proto.RegisterType((*ListChannelConfigurationsResponse)(nil), "api.ListChannelConfigurationsResponse")
	proto.RegisterType((*CreateExtraChannelRequest)(nil), "api.CreateExtraChannelRequest")
	proto.RegisterType((*CreateExtraChannelResponse)(nil), "api.CreateExtraChannelResponse")
	proto.RegisterType((*UpdateExtraChannelRequest)(nil), "api.UpdateExtraChannelRequest")
	proto.RegisterType((*UpdateExtraChannelResponse)(nil), "api.UpdateExtraChannelResponse")
	proto.RegisterType((*DeleteExtraChannelRequest)(nil), "api.DeleteExtraChannelRequest")
	proto.RegisterType((*DeleteExtraChannelResponse)(nil), "api.DeleteExtraChannelResponse")
	proto.RegisterType((*GetExtraChannelResponse)(nil), "api.GetExtraChannelResponse")
	proto.RegisterType((*GetExtraChannelsForChannelConfigurationIDRequest)(nil), "api.GetExtraChannelsForChannelConfigurationIDRequest")
	proto.RegisterType((*GetExtraChannelsForChannelConfigurationIDResponse)(nil), "api.GetExtraChannelsForChannelConfigurationIDResponse")
	proto.RegisterType((*PingRX)(nil), "api.PingRX")
	proto.RegisterType((*GetLastPingRequest)(nil), "api.GetLastPingRequest")
	proto.RegisterType((*GetLastPingResponse)(nil), "api.GetLastPingResponse")
	proto.RegisterType((*StreamGatewayFrameLogsRequest)(nil), "api.StreamGatewayFrameLogsRequest")
	proto.RegisterType((*StreamGatewayFrameLogsResponse)(nil), "api.StreamGatewayFrameLogsResponse")
	proto.RegisterEnum("api.Modulation", Modulation_name, Modulation_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Gateway service

type GatewayClient interface {
	// CreateChannelConfiguration creates the given channel-configuration.
	CreateChannelConfiguration(ctx context.Context, in *CreateChannelConfigurationRequest, opts ...grpc.CallOption) (*CreateChannelConfigurationResponse, error)
	// GetChannelConfiguration returns the channel-configuration for the given ID.
	GetChannelConfiguration(ctx context.Context, in *GetChannelConfigurationRequest, opts ...grpc.CallOption) (*GetChannelConfigurationResponse, error)
	// UpdateChannelConfiguration updates the given channel-configuration.
	UpdateChannelConfiguration(ctx context.Context, in *UpdateChannelConfigurationRequest, opts ...grpc.CallOption) (*UpdateChannelConfigurationResponse, error)
	// DeleteChannelConfiguration deletes the channel-configuration matching the
	// given ID.
	DeleteChannelConfiguration(ctx context.Context, in *DeleteChannelConfigurationRequest, opts ...grpc.CallOption) (*DeleteChannelConfigurationResponse, error)
	// ListChannelConfigurations returns all channel-configurations.
	ListChannelConfigurations(ctx context.Context, in *ListChannelConfigurationsRequest, opts ...grpc.CallOption) (*ListChannelConfigurationsResponse, error)
	// CreateExtraChannel creates the given extra channel.
	CreateExtraChannel(ctx context.Context, in *CreateExtraChannelRequest, opts ...grpc.CallOption) (*CreateExtraChannelResponse, error)
	// UpdateExtraChannel updates the given extra channel.
	UpdateExtraChannel(ctx context.Context, in *UpdateExtraChannelRequest, opts ...grpc.CallOption) (*UpdateExtraChannelResponse, error)
	// DeleteExtraChannel deletes the extra channel matching the given id.
	DeleteExtraChannel(ctx context.Context, in *DeleteExtraChannelRequest, opts ...grpc.CallOption) (*DeleteExtraChannelResponse, error)
	// GetExtraChannelsForChannelConfigurationID returns the extra channels for
	// the given channel-configuration id.
	GetExtraChannelsForChannelConfigurationID(ctx context.Context, in *GetExtraChannelsForChannelConfigurationIDRequest, opts ...grpc.CallOption) (*GetExtraChannelsForChannelConfigurationIDResponse, error)
	// Create creates the given gateway.
	Create(ctx context.Context, in *CreateGatewayRequest, opts ...grpc.CallOption) (*CreateGatewayResponse, error)
	// Get returns the gateway for the requested mac address.
	Get(ctx context.Context, in *GetGatewayRequest, opts ...grpc.CallOption) (*GetGatewayResponse, error)
	// Update updates the gateway matching the given mac address.
	Update(ctx context.Context, in *UpdateGatewayRequest, opts ...grpc.CallOption) (*UpdateGatewayResponse, error)
	// Delete deletes the gateway matching the given mac address.
	Delete(ctx context.Context, in *DeleteGatewayRequest, opts ...grpc.CallOption) (*DeleteGatewayResponse, error)
	// GenerateToken issues a JWT token which can be used by the gateway
	// for authentication.
	GenerateToken(ctx context.Context, in *GenerateGatewayTokenRequest, opts ...grpc.CallOption) (*GenerateGatewayTokenResponse, error)
	// List lists the gateways.
	List(ctx context.Context, in *ListGatewayRequest, opts ...grpc.CallOption) (*ListGatewayResponse, error)
	// GetStats lists the gateway stats given the query parameters.
	GetStats(ctx context.Context, in *GetGatewayStatsRequest, opts ...grpc.CallOption) (*GetGatewayStatsResponse, error)
	// GetLastPing returns the last emitted ping and gateways receiving this ping.
	GetLastPing(ctx context.Context, in *GetLastPingRequest, opts ...grpc.CallOption) (*GetLastPingResponse, error)
	// StreamFrameLogs streams the uplink and downlink frame-logs for the given mac.
	// Note: these are the raw LoRaWAN frames and this endpoint is intended for debugging.
	StreamFrameLogs(ctx context.Context, in *StreamGatewayFrameLogsRequest, opts ...grpc.CallOption) (Gateway_StreamFrameLogsClient, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) CreateChannelConfiguration(ctx context.Context, in *CreateChannelConfigurationRequest, opts ...grpc.CallOption) (*CreateChannelConfigurationResponse, error) {
	out := new(CreateChannelConfigurationResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/CreateChannelConfiguration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetChannelConfiguration(ctx context.Context, in *GetChannelConfigurationRequest, opts ...grpc.CallOption) (*GetChannelConfigurationResponse, error) {
	out := new(GetChannelConfigurationResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/GetChannelConfiguration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) UpdateChannelConfiguration(ctx context.Context, in *UpdateChannelConfigurationRequest, opts ...grpc.CallOption) (*UpdateChannelConfigurationResponse, error) {
	out := new(UpdateChannelConfigurationResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/UpdateChannelConfiguration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) DeleteChannelConfiguration(ctx context.Context, in *DeleteChannelConfigurationRequest, opts ...grpc.CallOption) (*DeleteChannelConfigurationResponse, error) {
	out := new(DeleteChannelConfigurationResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/DeleteChannelConfiguration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ListChannelConfigurations(ctx context.Context, in *ListChannelConfigurationsRequest, opts ...grpc.CallOption) (*ListChannelConfigurationsResponse, error) {
	out := new(ListChannelConfigurationsResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/ListChannelConfigurations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CreateExtraChannel(ctx context.Context, in *CreateExtraChannelRequest, opts ...grpc.CallOption) (*CreateExtraChannelResponse, error) {
	out := new(CreateExtraChannelResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/CreateExtraChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) UpdateExtraChannel(ctx context.Context, in *UpdateExtraChannelRequest, opts ...grpc.CallOption) (*UpdateExtraChannelResponse, error) {
	out := new(UpdateExtraChannelResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/UpdateExtraChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) DeleteExtraChannel(ctx context.Context, in *DeleteExtraChannelRequest, opts ...grpc.CallOption) (*DeleteExtraChannelResponse, error) {
	out := new(DeleteExtraChannelResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/DeleteExtraChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetExtraChannelsForChannelConfigurationID(ctx context.Context, in *GetExtraChannelsForChannelConfigurationIDRequest, opts ...grpc.CallOption) (*GetExtraChannelsForChannelConfigurationIDResponse, error) {
	out := new(GetExtraChannelsForChannelConfigurationIDResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/GetExtraChannelsForChannelConfigurationID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Create(ctx context.Context, in *CreateGatewayRequest, opts ...grpc.CallOption) (*CreateGatewayResponse, error) {
	out := new(CreateGatewayResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Get(ctx context.Context, in *GetGatewayRequest, opts ...grpc.CallOption) (*GetGatewayResponse, error) {
	out := new(GetGatewayResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Update(ctx context.Context, in *UpdateGatewayRequest, opts ...grpc.CallOption) (*UpdateGatewayResponse, error) {
	out := new(UpdateGatewayResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Delete(ctx context.Context, in *DeleteGatewayRequest, opts ...grpc.CallOption) (*DeleteGatewayResponse, error) {
	out := new(DeleteGatewayResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GenerateToken(ctx context.Context, in *GenerateGatewayTokenRequest, opts ...grpc.CallOption) (*GenerateGatewayTokenResponse, error) {
	out := new(GenerateGatewayTokenResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/GenerateToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) List(ctx context.Context, in *ListGatewayRequest, opts ...grpc.CallOption) (*ListGatewayResponse, error) {
	out := new(ListGatewayResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetStats(ctx context.Context, in *GetGatewayStatsRequest, opts ...grpc.CallOption) (*GetGatewayStatsResponse, error) {
	out := new(GetGatewayStatsResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/GetStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetLastPing(ctx context.Context, in *GetLastPingRequest, opts ...grpc.CallOption) (*GetLastPingResponse, error) {
	out := new(GetLastPingResponse)
	err := grpc.Invoke(ctx, "/api.Gateway/GetLastPing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) StreamFrameLogs(ctx context.Context, in *StreamGatewayFrameLogsRequest, opts ...grpc.CallOption) (Gateway_StreamFrameLogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Gateway_serviceDesc.Streams[0], c.cc, "/api.Gateway/StreamFrameLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayStreamFrameLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Gateway_StreamFrameLogsClient interface {
	Recv() (*StreamGatewayFrameLogsResponse, error)
	grpc.ClientStream
}

type gatewayStreamFrameLogsClient struct {
	grpc.ClientStream
}

func (x *gatewayStreamFrameLogsClient) Recv() (*StreamGatewayFrameLogsResponse, error) {
	m := new(StreamGatewayFrameLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Gateway service

type GatewayServer interface {
	// CreateChannelConfiguration creates the given channel-configuration.
	CreateChannelConfiguration(context.Context, *CreateChannelConfigurationRequest) (*CreateChannelConfigurationResponse, error)
	// GetChannelConfiguration returns the channel-configuration for the given ID.
	GetChannelConfiguration(context.Context, *GetChannelConfigurationRequest) (*GetChannelConfigurationResponse, error)
	// UpdateChannelConfiguration updates the given channel-configuration.
	UpdateChannelConfiguration(context.Context, *UpdateChannelConfigurationRequest) (*UpdateChannelConfigurationResponse, error)
	// DeleteChannelConfiguration deletes the channel-configuration matching the
	// given ID.
	DeleteChannelConfiguration(context.Context, *DeleteChannelConfigurationRequest) (*DeleteChannelConfigurationResponse, error)
	// ListChannelConfigurations returns all channel-configurations.
	ListChannelConfigurations(context.Context, *ListChannelConfigurationsRequest) (*ListChannelConfigurationsResponse, error)
	// CreateExtraChannel creates the given extra channel.
	CreateExtraChannel(context.Context, *CreateExtraChannelRequest) (*CreateExtraChannelResponse, error)
	// UpdateExtraChannel updates the given extra channel.
	UpdateExtraChannel(context.Context, *UpdateExtraChannelRequest) (*UpdateExtraChannelResponse, error)
	// DeleteExtraChannel deletes the extra channel matching the given id.
	DeleteExtraChannel(context.Context, *DeleteExtraChannelRequest) (*DeleteExtraChannelResponse, error)
	// GetExtraChannelsForChannelConfigurationID returns the extra channels for
	// the given channel-configuration id.
	GetExtraChannelsForChannelConfigurationID(context.Context, *GetExtraChannelsForChannelConfigurationIDRequest) (*GetExtraChannelsForChannelConfigurationIDResponse, error)
	// Create creates the given gateway.
	Create(context.Context, *CreateGatewayRequest) (*CreateGatewayResponse, error)
	// Get returns the gateway for the requested mac address.
	Get(context.Context, *GetGatewayRequest) (*GetGatewayResponse, error)
	// Update updates the gateway matching the given mac address.
	Update(context.Context, *UpdateGatewayRequest) (*UpdateGatewayResponse, error)
	// Delete deletes the gateway matching the given mac address.
	Delete(context.Context, *DeleteGatewayRequest) (*DeleteGatewayResponse, error)
	// GenerateToken issues a JWT token which can be used by the gateway
	// for authentication.
	GenerateToken(context.Context, *GenerateGatewayTokenRequest) (*GenerateGatewayTokenResponse, error)
	// List lists the gateways.
	List(context.Context, *ListGatewayRequest) (*ListGatewayResponse, error)
	// GetStats lists the gateway stats given the query parameters.
	GetStats(context.Context, *GetGatewayStatsRequest) (*GetGatewayStatsResponse, error)
	// GetLastPing returns the last emitted ping and gateways receiving this ping.
	GetLastPing(context.Context, *GetLastPingRequest) (*GetLastPingResponse, error)
	// StreamFrameLogs streams the uplink and downlink frame-logs for the given mac.
	// Note: these are the raw LoRaWAN frames and this endpoint is intended for debugging.
	StreamFrameLogs(*StreamGatewayFrameLogsRequest, Gateway_StreamFrameLogsServer) error
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_CreateChannelConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CreateChannelConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/CreateChannelConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CreateChannelConfiguration(ctx, req.(*CreateChannelConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetChannelConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetChannelConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/GetChannelConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetChannelConfiguration(ctx, req.(*GetChannelConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_UpdateChannelConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChannelConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).UpdateChannelConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/UpdateChannelConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).UpdateChannelConfiguration(ctx, req.(*UpdateChannelConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_DeleteChannelConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChannelConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).DeleteChannelConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/DeleteChannelConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).DeleteChannelConfiguration(ctx, req.(*DeleteChannelConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ListChannelConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelConfigurationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ListChannelConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/ListChannelConfigurations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ListChannelConfigurations(ctx, req.(*ListChannelConfigurationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CreateExtraChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExtraChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CreateExtraChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/CreateExtraChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CreateExtraChannel(ctx, req.(*CreateExtraChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_UpdateExtraChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExtraChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).UpdateExtraChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/UpdateExtraChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).UpdateExtraChannel(ctx, req.(*UpdateExtraChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_DeleteExtraChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExtraChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).DeleteExtraChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/DeleteExtraChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).DeleteExtraChannel(ctx, req.(*DeleteExtraChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetExtraChannelsForChannelConfigurationID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtraChannelsForChannelConfigurationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetExtraChannelsForChannelConfigurationID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/GetExtraChannelsForChannelConfigurationID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetExtraChannelsForChannelConfigurationID(ctx, req.(*GetExtraChannelsForChannelConfigurationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Create(ctx, req.(*CreateGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Get(ctx, req.(*GetGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Update(ctx, req.(*UpdateGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Delete(ctx, req.(*DeleteGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateGatewayTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/GenerateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GenerateToken(ctx, req.(*GenerateGatewayTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).List(ctx, req.(*ListGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetStats(ctx, req.(*GetGatewayStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetLastPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetLastPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Gateway/GetLastPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetLastPing(ctx, req.(*GetLastPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_StreamFrameLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamGatewayFrameLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServer).StreamFrameLogs(m, &gatewayStreamFrameLogsServer{stream})
}

type Gateway_StreamFrameLogsServer interface {
	Send(*StreamGatewayFrameLogsResponse) error
	grpc.ServerStream
}

type gatewayStreamFrameLogsServer struct {
	grpc.ServerStream
}

func (x *gatewayStreamFrameLogsServer) Send(m *StreamGatewayFrameLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChannelConfiguration",
			Handler:    _Gateway_CreateChannelConfiguration_Handler,
		},
		{
			MethodName: "GetChannelConfiguration",
			Handler:    _Gateway_GetChannelConfiguration_Handler,
		},
		{
			MethodName: "UpdateChannelConfiguration",
			Handler:    _Gateway_UpdateChannelConfiguration_Handler,
		},
		{
			MethodName: "DeleteChannelConfiguration",
			Handler:    _Gateway_DeleteChannelConfiguration_Handler,
		},
		{
			MethodName: "ListChannelConfigurations",
			Handler:    _Gateway_ListChannelConfigurations_Handler,
		},
		{
			MethodName: "CreateExtraChannel",
			Handler:    _Gateway_CreateExtraChannel_Handler,
		},
		{
			MethodName: "UpdateExtraChannel",
			Handler:    _Gateway_UpdateExtraChannel_Handler,
		},
		{
			MethodName: "DeleteExtraChannel",
			Handler:    _Gateway_DeleteExtraChannel_Handler,
		},
		{
			MethodName: "GetExtraChannelsForChannelConfigurationID",
			Handler:    _Gateway_GetExtraChannelsForChannelConfigurationID_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Gateway_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Gateway_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Gateway_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Gateway_Delete_Handler,
		},
		{
			MethodName: "GenerateToken",
			Handler:    _Gateway_GenerateToken_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Gateway_List_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Gateway_GetStats_Handler,
		},
		{
			MethodName: "GetLastPing",
			Handler:    _Gateway_GetLastPing_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFrameLogs",
			Handler:       _Gateway_StreamFrameLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway.proto",
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 1857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x5b, 0x6f, 0x1b, 0xc7,
	0x15, 0xee, 0xf0, 0x26, 0xf2, 0xe8, 0xea, 0xd1, 0x8d, 0x5a, 0xb1, 0x32, 0xb5, 0x92, 0x55, 0x5a,
	0x75, 0x45, 0xf9, 0x52, 0xb7, 0x28, 0xda, 0x02, 0x86, 0x64, 0x09, 0x86, 0xd5, 0xda, 0x58, 0xd9,
	0xe8, 0x05, 0x2d, 0x8a, 0x31, 0x77, 0x44, 0x2d, 0xb4, 0xdc, 0x65, 0x77, 0x87, 0x96, 0x5d, 0x43,
	0x68, 0xe1, 0x87, 0xbe, 0xf5, 0xa5, 0x01, 0x9c, 0xbc, 0x24, 0x01, 0xf2, 0x14, 0xe4, 0x27, 0xe4,
	0x0f, 0x04, 0xc8, 0x43, 0x1e, 0x92, 0xb7, 0x3c, 0x07, 0xc9, 0xdf, 0x08, 0x76, 0x76, 0x76, 0xb9,
	0xbb, 0x9c, 0x5d, 0x92, 0x71, 0x0c, 0xe4, 0x21, 0x6f, 0x9c, 0x33, 0xb7, 0xef, 0x7c, 0xf3, 0x9d,
	0x33, 0x67, 0x87, 0x30, 0xdd, 0x26, 0x8c, 0x9e, 0x93, 0xe7, 0x3b, 0x5d, 0xc7, 0x66, 0x36, 0xce,
	0x93, 0xae, 0xa1, 0xd4, 0xda, 0xb6, 0xdd, 0x36, 0x69, 0x93, 0x74, 0x8d, 0x26, 0xb1, 0x2c, 0x9b,
	0x11, 0x66, 0xd8, 0x96, 0xeb, 0x0f, 0x51, 0xa6, 0x5a, 0x76, 0xa7, 0x63, 0x5b, 0x7e, 0x4b, 0xfd,
	0x3c, 0x07, 0x0b, 0x7b, 0x0e, 0x25, 0x8c, 0x1e, 0xfa, 0x0b, 0x69, 0xf4, 0x9f, 0x3d, 0xea, 0x32,
	0x3c, 0x07, 0xf9, 0x0e, 0x69, 0x55, 0x51, 0x1d, 0x35, 0x2a, 0x9a, 0xf7, 0x13, 0x63, 0x28, 0x58,
	0xa4, 0x43, 0xab, 0x39, 0x6e, 0xe2, 0xbf, 0x71, 0x1d, 0x26, 0x75, 0xea, 0xb6, 0x1c, 0xa3, 0xeb,
	0x6d, 0x51, 0xcd, 0xf3, 0xae, 0xa8, 0x09, 0x2b, 0x50, 0x36, 0x09, 0x33, 0x58, 0x4f, 0xa7, 0xd5,
	0x42, 0x1d, 0x35, 0x90, 0x16, 0xb6, 0x71, 0x0d, 0x2a, 0xa6, 0x6d, 0xb5, 0xfd, 0xce, 0x22, 0xef,
	0xec, 0x1b, 0xbc, 0x99, 0xc4, 0x14, 0x33, 0x4b, 0xfe, 0xcc, 0xa0, 0x8d, 0xb7, 0x60, 0xc6, 0x76,
	0xda, 0xc4, 0x32, 0xfe, 0xc5, 0x7d, 0xbb, 0xb7, 0x5f, 0x9d, 0xa8, 0xa3, 0x46, 0x5e, 0x4b, 0x58,
	0xf1, 0x6d, 0x58, 0x6a, 0x9d, 0x12, 0xcb, 0xa2, 0xe6, 0x9e, 0x6d, 0x9d, 0x18, 0xed, 0x9e, 0x13,
	0x8c, 0x2f, 0xf3, 0xf1, 0x29, 0xbd, 0x9e, 0xaf, 0x5d, 0xc3, 0x6a, 0x57, 0x2b, 0x75, 0xd4, 0x28,
	0x6b, 0xfc, 0x37, 0x6e, 0xc0, 0xac, 0x45, 0xd9, 0xb9, 0xed, 0x9c, 0x1d, 0x53, 0xe7, 0x29, 0x75,
	0xee, 0xed, 0x57, 0x81, 0x2f, 0x92, 0x34, 0xab, 0xcb, 0xb0, 0x98, 0xe0, 0xd4, 0xed, 0xda, 0x96,
	0x4b, 0xd5, 0x2b, 0x70, 0xe9, 0x90, 0xb2, 0x61, 0x4c, 0xab, 0x9f, 0xe5, 0x01, 0x47, 0xc7, 0xf9,
	0xb3, 0x7f, 0xe0, 0x47, 0x52, 0x83, 0x4a, 0x8b, 0x3b, 0xad, 0xdf, 0x61, 0xfc, 0x34, 0x2a, 0x5a,
	0xdf, 0xe0, 0xf5, 0xf6, 0xba, 0xba, 0xe8, 0x2d, 0xfb, 0xbd, 0xa1, 0xc1, 0xc3, 0x7c, 0x62, 0x38,
	0x2e, 0x3b, 0xa6, 0xd4, 0xba, 0xc3, 0x38, 0xeb, 0x15, 0x2d, 0x6a, 0xc2, 0x6b, 0x00, 0x26, 0x09,
	0x07, 0x00, 0x1f, 0x10, 0xb1, 0x48, 0x04, 0x31, 0x39, 0xa6, 0x20, 0xa6, 0x46, 0x12, 0xc4, 0x74,
	0xb6, 0x20, 0x66, 0xe4, 0x82, 0x68, 0xc0, 0xc2, 0x3e, 0x35, 0xe9, 0xf0, 0x20, 0x53, 0x9b, 0xb0,
	0x7a, 0x48, 0x2d, 0xea, 0xf4, 0xc5, 0xf3, 0xc8, 0x3e, 0xa3, 0x56, 0xfa, 0x84, 0x5b, 0x50, 0x93,
	0x4f, 0x10, 0xa2, 0x59, 0x80, 0x22, 0xf3, 0x0c, 0x62, 0x8e, 0xdf, 0xf0, 0x14, 0x9a, 0x00, 0x24,
	0x14, 0xfa, 0x12, 0x01, 0x3e, 0x32, 0xdc, 0xa4, 0x46, 0x17, 0xa0, 0x68, 0x1a, 0x1d, 0x83, 0xf1,
	0x55, 0x8a, 0x9a, 0xdf, 0xc0, 0x4b, 0x50, 0xb2, 0x4f, 0x4e, 0x5c, 0xca, 0xb8, 0x00, 0x8b, 0x9a,
	0x68, 0x49, 0x0e, 0x23, 0x2f, 0x3d, 0x8c, 0x25, 0x28, 0xb9, 0x94, 0x38, 0xad, 0x53, 0x2e, 0xc3,
	0x8a, 0x26, 0x5a, 0xea, 0x37, 0x08, 0x66, 0x23, 0x20, 0xee, 0x31, 0xda, 0xf9, 0xde, 0xc4, 0x1f,
	0x93, 0x69, 0x21, 0x53, 0xa6, 0xc5, 0xa4, 0x4c, 0x07, 0xfd, 0x2a, 0x49, 0xfd, 0x92, 0x08, 0x63,
	0x42, 0x2e, 0x8c, 0x16, 0xcc, 0xc7, 0xd8, 0x16, 0x87, 0xb6, 0x06, 0xc0, 0x6c, 0x46, 0xcc, 0x3d,
	0xbb, 0x67, 0x05, 0x9c, 0x47, 0x2c, 0xf8, 0x1a, 0x94, 0x1c, 0xea, 0xf6, 0x4c, 0x8f, 0xf8, 0x7c,
	0x63, 0xf2, 0xc6, 0xc2, 0x0e, 0xe9, 0x1a, 0x3b, 0x09, 0xca, 0x34, 0x31, 0x46, 0xfd, 0x30, 0x07,
	0x0b, 0x8f, 0xb9, 0x13, 0x3f, 0xe6, 0xf8, 0xec, 0x1c, 0xef, 0xc5, 0x45, 0x82, 0x29, 0x11, 0x17,
	0x5f, 0x23, 0x98, 0x12, 0xb6, 0x63, 0x46, 0x98, 0xeb, 0xf9, 0xc5, 0x8c, 0x0e, 0x75, 0x19, 0xe9,
	0x74, 0x05, 0x83, 0x7d, 0x03, 0xbe, 0x06, 0x97, 0x9c, 0x67, 0x0f, 0x49, 0xeb, 0x8c, 0x32, 0x57,
	0xa3, 0x2d, 0x6a, 0x3c, 0xa5, 0xba, 0x08, 0x92, 0xc1, 0x0e, 0xbc, 0x0b, 0xf3, 0x03, 0xc6, 0x07,
	0xf7, 0x39, 0xd3, 0x45, 0x4d, 0xd6, 0xe5, 0xad, 0xcf, 0x06, 0xd6, 0x2f, 0xf8, 0xeb, 0x0f, 0x74,
	0xe0, 0x6d, 0x98, 0x0b, 0x8d, 0x77, 0x3b, 0x06, 0x63, 0x54, 0xe7, 0x47, 0x51, 0xd4, 0x06, 0xec,
	0xea, 0xff, 0x11, 0x2c, 0xf5, 0xef, 0x1e, 0xee, 0x6b, 0xba, 0x5c, 0x14, 0x28, 0x1b, 0x16, 0xa3,
	0xce, 0x53, 0x62, 0x0a, 0xc9, 0x84, 0x6d, 0xef, 0xf8, 0x5c, 0x46, 0x1c, 0xf6, 0x28, 0x64, 0xc9,
	0x57, 0x4e, 0xc2, 0x8a, 0x55, 0x98, 0xa2, 0x96, 0xde, 0x1f, 0xe5, 0xc7, 0x64, 0xcc, 0xa6, 0xee,
	0xc3, 0xf2, 0x00, 0x26, 0x11, 0x2a, 0x57, 0xc3, 0x50, 0x40, 0x3c, 0x14, 0x2e, 0xf1, 0x50, 0x88,
	0x0d, 0x0d, 0xe2, 0xe0, 0x02, 0xd6, 0xfd, 0x6b, 0x79, 0x4f, 0x22, 0x88, 0xc0, 0xc9, 0x20, 0x02,
	0x50, 0x24, 0x02, 0x14, 0x28, 0x0b, 0x0d, 0xb9, 0x3c, 0xe0, 0x8a, 0x5a, 0xd8, 0x96, 0xc5, 0x7a,
	0x5e, 0x1e, 0xeb, 0xb7, 0x40, 0xcd, 0xda, 0x5e, 0xf8, 0x33, 0x03, 0x39, 0x43, 0xe7, 0xbb, 0xe7,
	0xb5, 0x9c, 0xa1, 0xab, 0x7f, 0x85, 0xb5, 0x43, 0xca, 0xb2, 0x10, 0x27, 0x66, 0xc8, 0x10, 0xe5,
	0xe4, 0x88, 0x3e, 0x41, 0x70, 0x39, 0x75, 0x71, 0x39, 0x1e, 0x69, 0x86, 0x88, 0xf2, 0x93, 0x4f,
	0xf0, 0xf3, 0x3a, 0xf9, 0x56, 0xe2, 0x49, 0x49, 0xee, 0xc9, 0xff, 0x10, 0xac, 0xfb, 0x81, 0x3b,
	0x0e, 0x53, 0xe3, 0xfa, 0x22, 0xc1, 0x53, 0x90, 0xe3, 0xd9, 0x04, 0x35, 0x0b, 0x8e, 0x48, 0x2a,
	0x7f, 0x87, 0x75, 0xff, 0x16, 0x7e, 0x33, 0xc7, 0xbb, 0x09, 0x6a, 0xd6, 0xf2, 0x02, 0xc4, 0x11,
	0xd4, 0xbd, 0x8b, 0x43, 0x36, 0x26, 0x8c, 0x7c, 0xc9, 0x9e, 0x48, 0xbe, 0x27, 0x81, 0xf5, 0x8c,
	0xd5, 0x84, 0xa6, 0x7e, 0x9b, 0x88, 0xd9, 0x4d, 0x3f, 0x66, 0xb3, 0x95, 0x18, 0x86, 0xf1, 0x47,
	0x39, 0x58, 0xf1, 0x03, 0xe9, 0xee, 0x33, 0xe6, 0x10, 0x31, 0x27, 0x80, 0x9a, 0x7e, 0x1b, 0xa0,
	0xcc, 0xdb, 0xa0, 0x09, 0xd0, 0xb1, 0xf5, 0x9e, 0xc9, 0xdb, 0x9c, 0xd1, 0x99, 0x1b, 0xb3, 0x1c,
	0xd7, 0x1f, 0x42, 0xb3, 0x16, 0x19, 0xe2, 0x49, 0xf7, 0xc4, 0xf1, 0x36, 0xb5, 0x5a, 0xcf, 0x45,
	0xaa, 0xee, 0x1b, 0xbc, 0xde, 0x27, 0xc4, 0xd2, 0xff, 0x64, 0xe8, 0xec, 0x54, 0x24, 0xe6, 0xbe,
	0x01, 0x57, 0x61, 0xe2, 0x89, 0xc1, 0x34, 0xc2, 0xa8, 0xc8, 0xc3, 0x41, 0x13, 0x6f, 0xc2, 0xb4,
	0xdb, 0x75, 0x28, 0xd1, 0x0f, 0x48, 0x8b, 0xd9, 0x8e, 0x5b, 0x2d, 0x71, 0x0d, 0xc6, 0x8d, 0x63,
	0x14, 0x18, 0xd7, 0x40, 0x91, 0x71, 0x95, 0x92, 0x6c, 0x3e, 0xce, 0xc1, 0x8a, 0xaf, 0x5b, 0x19,
	0xb5, 0x49, 0x25, 0xa6, 0x53, 0x9d, 0x1b, 0x83, 0xea, 0xfc, 0x98, 0x54, 0x17, 0x32, 0xa9, 0x2e,
	0x66, 0x50, 0x5d, 0x1a, 0x42, 0xf5, 0xc4, 0x88, 0x54, 0x97, 0xe5, 0x54, 0xd7, 0x40, 0x91, 0x71,
	0x27, 0xc2, 0xec, 0x31, 0xac, 0xf8, 0xc1, 0x38, 0x0a, 0xb3, 0xa3, 0xc7, 0x78, 0x0d, 0x14, 0xd9,
	0xb2, 0x62, 0xd3, 0x4f, 0x73, 0xfc, 0xe2, 0x1c, 0xe5, 0xec, 0xbf, 0xf3, 0x69, 0xc6, 0x12, 0x7c,
	0x3e, 0x33, 0xc1, 0x17, 0x92, 0x09, 0x3e, 0xae, 0x84, 0xe2, 0x98, 0x4a, 0x28, 0xa5, 0x28, 0xe1,
	0x9c, 0x2b, 0x61, 0xa2, 0xaf, 0x84, 0xf3, 0xa4, 0x12, 0xca, 0x43, 0x94, 0x50, 0x91, 0x28, 0x41,
	0x35, 0x61, 0x37, 0xc1, 0xa5, 0x7b, 0x60, 0x3b, 0x7b, 0x52, 0x56, 0x5e, 0xff, 0x60, 0x0d, 0xb8,
	0x3e, 0xc6, 0x6e, 0xe2, 0x4c, 0x6f, 0x25, 0x12, 0x6b, 0x2d, 0x48, 0xac, 0x32, 0x05, 0x84, 0x09,
	0xf5, 0x3d, 0x04, 0xa5, 0x87, 0x86, 0xd5, 0xd6, 0xfe, 0x2c, 0xff, 0x22, 0x70, 0x5c, 0xd7, 0x10,
	0xc5, 0x2b, 0xff, 0xed, 0x31, 0x69, 0xda, 0x0e, 0x39, 0xfe, 0xa3, 0xc6, 0x0f, 0x1c, 0x69, 0x41,
	0xf3, 0xcd, 0x7c, 0x09, 0xa8, 0x5b, 0xfc, 0x39, 0xe4, 0x88, 0xb8, 0x8c, 0xc3, 0x4c, 0xfd, 0x16,
	0xfe, 0x2f, 0x82, 0xf9, 0xd8, 0x40, 0x41, 0x4b, 0x4c, 0xa2, 0x48, 0x22, 0xd1, 0xbe, 0xa6, 0x3c,
	0x37, 0xa7, 0xa3, 0x9a, 0x9a, 0x81, 0x9c, 0xee, 0x70, 0x37, 0xa7, 0xb5, 0x9c, 0xee, 0xe0, 0x0d,
	0x28, 0x75, 0x39, 0x57, 0xd5, 0x02, 0xa7, 0x78, 0x92, 0x53, 0xec, 0xd3, 0xa7, 0x89, 0x2e, 0xf5,
	0x3a, 0xfc, 0xf4, 0x98, 0x39, 0x94, 0x74, 0x44, 0x1d, 0x7a, 0xe0, 0x90, 0x0e, 0x3d, 0xb2, 0xdb,
	0xe9, 0xa5, 0xb4, 0xfa, 0x0e, 0x82, 0xb5, 0xb4, 0x39, 0xc2, 0x8d, 0x5f, 0xc1, 0x54, 0xaf, 0x6b,
	0x1a, 0xd6, 0x19, 0xef, 0x72, 0xc5, 0x19, 0xcf, 0x73, 0x00, 0x8f, 0xfb, 0x1d, 0x47, 0x76, 0x5b,
	0x8b, 0x0d, 0xc4, 0xbf, 0x83, 0x19, 0xdd, 0x3e, 0xb7, 0x22, 0x53, 0xfd, 0xcf, 0xc6, 0x45, 0x3e,
	0x75, 0x3f, 0xda, 0xe5, 0x4d, 0x4e, 0x0c, 0xde, 0xbe, 0x0c, 0xd0, 0x0f, 0x47, 0x5c, 0x86, 0xc2,
	0xd1, 0x03, 0xed, 0xce, 0xdc, 0x4f, 0xf0, 0x04, 0xe4, 0x0f, 0x8e, 0xef, 0xcf, 0xa1, 0x1b, 0xaf,
	0x30, 0x4c, 0x08, 0xd4, 0xf8, 0x5d, 0x14, 0xdc, 0x38, 0x32, 0xad, 0xe2, 0x2d, 0xbe, 0xe5, 0xd0,
	0x32, 0x5c, 0xf9, 0xd9, 0xd0, 0x71, 0x22, 0xc5, 0xed, 0xbc, 0xfc, 0xe2, 0xab, 0xb7, 0x72, 0x0d,
	0x75, 0x83, 0x3f, 0x77, 0x8a, 0xd7, 0x50, 0xb7, 0x29, 0x92, 0x55, 0x2b, 0x56, 0x80, 0xfc, 0x06,
	0x6d, 0xe3, 0x57, 0x88, 0xa7, 0x44, 0x29, 0xb8, 0x8d, 0xec, 0x3a, 0xc4, 0x47, 0x36, 0x52, 0xb1,
	0xa2, 0xee, 0x72, 0x58, 0xdb, 0xb8, 0x31, 0x02, 0xac, 0xe6, 0x0b, 0x43, 0xbf, 0xc0, 0x1f, 0xa0,
	0xe0, 0xfe, 0xc8, 0x20, 0x6e, 0x68, 0x8d, 0x2b, 0x88, 0x1b, 0xa1, 0xf8, 0xbc, 0xc9, 0x11, 0xfe,
	0x42, 0x19, 0x19, 0xa1, 0xc7, 0xde, 0xfb, 0x28, 0xb8, 0x6f, 0x32, 0x40, 0x0e, 0xad, 0x69, 0x05,
	0xc8, 0x11, 0x8a, 0x53, 0x41, 0xe3, 0xf6, 0xe8, 0x34, 0xbe, 0x8d, 0x60, 0x25, 0xb5, 0x02, 0xc5,
	0x57, 0xc2, 0x87, 0x92, 0xac, 0x7a, 0x57, 0xd9, 0x1a, 0x36, 0x4c, 0xc0, 0xfb, 0x39, 0x87, 0x77,
	0x05, 0x8f, 0x22, 0x3e, 0x7c, 0x01, 0x78, 0xb0, 0x14, 0xc3, 0x6b, 0x11, 0xa1, 0x4b, 0x4a, 0x03,
	0xe5, 0x72, 0x6a, 0xbf, 0xc0, 0xb0, 0xc5, 0x31, 0xd4, 0xd5, 0xd5, 0x38, 0x06, 0xea, 0x8d, 0x0d,
	0xbe, 0x5c, 0xbc, 0xa3, 0x7b, 0x89, 0x00, 0x0f, 0xd6, 0x27, 0x62, 0xff, 0xd4, 0xa2, 0x4f, 0xec,
	0x9f, 0x51, 0xd8, 0x08, 0x0e, 0x94, 0x7a, 0xc6, 0xfe, 0xa1, 0x7e, 0xfe, 0x0d, 0x78, 0xb0, 0x5c,
	0x11, 0x18, 0x52, 0xcb, 0x23, 0x81, 0x21, 0xa3, 0xce, 0x69, 0x70, 0x0c, 0xea, 0xf6, 0x50, 0x0c,
	0xf8, 0x4b, 0x04, 0x57, 0x47, 0xbe, 0x57, 0xf1, 0x2f, 0x65, 0xf7, 0xe7, 0xd0, 0x5b, 0x5f, 0xb9,
	0x3d, 0xee, 0x34, 0xe1, 0xc6, 0xef, 0xb9, 0x1b, 0xbf, 0xc6, 0xb7, 0x47, 0x55, 0x7b, 0xdc, 0x43,
	0xfc, 0x17, 0x28, 0xf9, 0x42, 0xc1, 0x2b, 0x11, 0xd5, 0xc4, 0x1f, 0xfd, 0x14, 0x45, 0xd6, 0x25,
	0x00, 0x54, 0x39, 0x00, 0xac, 0x4e, 0xc7, 0x00, 0x78, 0x07, 0x77, 0x0c, 0xf9, 0x43, 0xca, 0xf0,
	0x52, 0xe0, 0x59, 0x62, 0xd1, 0xe5, 0x01, 0xbb, 0x58, 0x71, 0x95, 0xaf, 0xb8, 0x88, 0xe7, 0xe3,
	0x2e, 0xbd, 0xe8, 0x90, 0xd6, 0x05, 0xfe, 0x07, 0x94, 0x7c, 0x61, 0x09, 0xbc, 0xb2, 0x47, 0x4a,
	0x81, 0x57, 0xfe, 0x2a, 0xb7, 0xc6, 0x57, 0xaf, 0x2a, 0xb2, 0xd5, 0x3d, 0xd4, 0x7f, 0x83, 0x92,
	0xaf, 0x1a, 0xb1, 0x81, 0xec, 0x11, 0x5e, 0x6c, 0x20, 0x7f, 0x0e, 0x17, 0xf0, 0xb7, 0xa5, 0xf0,
	0xcf, 0x61, 0x3a, 0x78, 0x7a, 0xe7, 0x6f, 0xee, 0xb8, 0x2e, 0x58, 0x48, 0x7d, 0xbf, 0x57, 0xd6,
	0x33, 0x46, 0x88, 0x2d, 0xd7, 0xf9, 0x96, 0xab, 0xea, 0x8a, 0x64, 0xcb, 0x26, 0x7f, 0xbd, 0xc7,
	0x0f, 0xa1, 0xe0, 0xe5, 0x26, 0xbc, 0x9c, 0x7c, 0xf6, 0x0d, 0xb6, 0xa9, 0x0e, 0x76, 0x88, 0xd5,
	0x17, 0xf9, 0xea, 0xb3, 0x38, 0x7e, 0xc2, 0xf8, 0x14, 0xca, 0x87, 0x94, 0xf9, 0x2f, 0x9b, 0xab,
	0x89, 0xb3, 0x8c, 0xbe, 0x01, 0x2a, 0x35, 0x79, 0x67, 0x1c, 0x3b, 0x96, 0x62, 0x77, 0xf9, 0xea,
	0xa7, 0x30, 0x19, 0x29, 0xd1, 0x70, 0x28, 0x9c, 0x44, 0x75, 0x27, 0x5c, 0x90, 0x54, 0x73, 0x41,
	0xc2, 0xc3, 0x6b, 0xb2, 0x4d, 0xbc, 0x02, 0xcc, 0x6d, 0x9a, 0xc4, 0x65, 0xf8, 0x3f, 0x08, 0x66,
	0xfd, 0x8a, 0x2a, 0x2c, 0xa5, 0xb0, 0xca, 0x57, 0xcd, 0xac, 0xcd, 0x94, 0x8d, 0xcc, 0x31, 0x02,
	0x84, 0xca, 0x41, 0xd4, 0xb0, 0x22, 0x03, 0x71, 0xc2, 0xeb, 0xa6, 0x5d, 0xf4, 0xa4, 0xc4, 0xff,
	0x64, 0xbd, 0xf9, 0x6d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x4f, 0x24, 0xaf, 0xa6, 0x1d, 0x00,
	0x00,
}
