// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	node.proto
	application.proto
	downlinkQueue.proto
	common.proto
	user.proto
	gateway.proto
	organization.proto

It has these top-level messages:
	CreateNodeRequest
	CreateNodeResponse
	GetNodeRequest
	GetNodeResponse
	DeleteNodeRequest
	DeleteNodeResponse
	ListNodeByApplicationIDRequest
	ListNodeResponse
	UpdateNodeRequest
	UpdateNodeResponse
	ActivateNodeRequest
	ActivateNodeResponse
	GetNodeActivationRequest
	GetNodeActivationResponse
	GetRandomDevAddrRequest
	GetRandomDevAddrResponse
	GetFrameLogsRequest
	GetFrameLogsResponse
	FrameLog
	DataRate
	RXInfo
	TXInfo
	CreateApplicationRequest
	CreateApplicationResponse
	GetApplicationRequest
	GetApplicationResponse
	UpdateApplicationRequest
	UpdateApplicationResponse
	DeleteApplicationRequest
	DeleteApplicationResponse
	ListApplicationRequest
	ListApplicationResponse
	ListApplicationUsersRequest
	GetApplicationUserResponse
	ListApplicationUsersResponse
	AddApplicationUserRequest
	ApplicationUserRequest
	UpdateApplicationUserRequest
	EmptyApplicationUserResponse
	EmptyResponse
	HTTPIntegrationHeader
	HTTPIntegration
	GetHTTPIntegrationRequest
	DeleteIntegrationRequest
	ListIntegrationRequest
	ListIntegrationResponse
	EnqueueDownlinkQueueItemRequest
	EnqueueDownlinkQueueItemResponse
	DeleteDownlinkQeueueItemRequest
	DeleteDownlinkQueueItemResponse
	DownlinkQueueItem
	ListDownlinkQueueItemsRequest
	ListDownlinkQueueItemsResponse
	ApplicationLink
	OrganizationLink
	UserProfile
	ProfileRequest
	ProfileResponse
	ProfileSettings
	LoginRequest
	LoginResponse
	ListUserRequest
	UserRequest
	AddUserResponse
	UserSettings
	UserInfo
	GetUserResponse
	AddUserRequest
	AddUserOrganization
	AddUserApplication
	UpdateUserRequest
	ListUserResponse
	UserEmptyResponse
	UpdateUserPasswordRequest
	CreateGatewayRequest
	CreateGatewayResponse
	GetGatewayRequest
	GetGatewayResponse
	DeleteGatewayRequest
	GenerateGatewayTokenRequest
	GenerateGatewayTokenResponse
	DeleteGatewayResponse
	ListGatewayRequest
	ListGatewayItem
	ListGatewayResponse
	UpdateGatewayRequest
	UpdateGatewayResponse
	GatewayStats
	GetGatewayStatsRequest
	GetGatewayStatsResponse
	CreateChannelConfigurationRequest
	CreateChannelConfigurationResponse
	GetChannelConfigurationRequest
	GetChannelConfigurationResponse
	UpdateChannelConfigurationRequest
	UpdateChannelConfigurationResponse
	DeleteChannelConfigurationRequest
	DeleteChannelConfigurationResponse
	ListChannelConfigurationsRequest
	ListChannelConfigurationsResponse
	CreateExtraChannelRequest
	CreateExtraChannelResponse
	UpdateExtraChannelRequest
	UpdateExtraChannelResponse
	DeleteExtraChannelRequest
	DeleteExtraChannelResponse
	GetExtraChannelResponse
	GetExtraChannelsForChannelConfigurationIDRequest
	GetExtraChannelsForChannelConfigurationIDResponse
	ListOrganizationRequest
	OrganizationRequest
	GetOrganizationResponse
	CreateOrganizationRequest
	CreateOrganizationResponse
	UpdateOrganizationRequest
	ListOrganizationResponse
	OrganizationEmptyResponse
	OrganizationUserRequest
	DeleteOrganizationUserRequest
	ListOrganizationUsersRequest
	GetOrganizationUserRequest
	GetOrganizationUserResponse
	ListOrganizationUsersResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateNodeRequest struct {
	// Hex encoded DevEUI.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Hex encoded AppEUI.
	AppEUI string `protobuf:"bytes,2,opt,name=appEUI" json:"appEUI,omitempty"`
	// Hex encoded AppKey. When isABP is set to true, this field is not needed.
	AppKey string `protobuf:"bytes,3,opt,name=appKey" json:"appKey,omitempty"`
	// RX delay.
	RxDelay uint32 `protobuf:"varint,4,opt,name=rxDelay" json:"rxDelay,omitempty"`
	// RX1 data-rate offset.
	Rx1DROffset uint32 `protobuf:"varint,5,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	// RX window to use.
	RxWindow RXWindow `protobuf:"varint,7,opt,name=rxWindow,enum=api.RXWindow" json:"rxWindow,omitempty"`
	// Data-rate to use for RX2.
	Rx2DR uint32 `protobuf:"varint,8,opt,name=rx2DR" json:"rx2DR,omitempty"`
	// Name of the node (if left blank, it will be set to the DevEUI).
	Name string `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	// Relax frame-counter mode is enabled.
	RelaxFCnt bool `protobuf:"varint,10,opt,name=relaxFCnt" json:"relaxFCnt,omitempty"`
	// Interval (in frames) in which the ADR engine may adapt the data-rate of the node (0 = disabled).
	AdrInterval uint32 `protobuf:"varint,11,opt,name=adrInterval" json:"adrInterval,omitempty"`
	// Installation-margin to use for ADR calculation.
	InstallationMargin float64 `protobuf:"fixed64,12,opt,name=installationMargin" json:"installationMargin,omitempty"`
	// ID of the application to which the node must be added.
	ApplicationID int64 `protobuf:"varint,13,opt,name=applicationID" json:"applicationID,omitempty"`
	// Description of the node.
	Description string `protobuf:"bytes,14,opt,name=description" json:"description,omitempty"`
	// Node is activated by ABP.
	IsABP bool `protobuf:"varint,15,opt,name=isABP" json:"isABP,omitempty"`
	// Node operates in Class-C.
	IsClassC bool `protobuf:"varint,16,opt,name=isClassC" json:"isClassC,omitempty"`
	// When set to true, the application settings will be used to populate the node network settings.
	UseApplicationSettings bool `protobuf:"varint,17,opt,name=useApplicationSettings" json:"useApplicationSettings,omitempty"`
}

func (m *CreateNodeRequest) Reset()                    { *m = CreateNodeRequest{} }
func (m *CreateNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeRequest) ProtoMessage()               {}
func (*CreateNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateNodeRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *CreateNodeRequest) GetAppEUI() string {
	if m != nil {
		return m.AppEUI
	}
	return ""
}

func (m *CreateNodeRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *CreateNodeRequest) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *CreateNodeRequest) GetRx1DROffset() uint32 {
	if m != nil {
		return m.Rx1DROffset
	}
	return 0
}

func (m *CreateNodeRequest) GetRxWindow() RXWindow {
	if m != nil {
		return m.RxWindow
	}
	return RXWindow_RX1
}

func (m *CreateNodeRequest) GetRx2DR() uint32 {
	if m != nil {
		return m.Rx2DR
	}
	return 0
}

func (m *CreateNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateNodeRequest) GetRelaxFCnt() bool {
	if m != nil {
		return m.RelaxFCnt
	}
	return false
}

func (m *CreateNodeRequest) GetAdrInterval() uint32 {
	if m != nil {
		return m.AdrInterval
	}
	return 0
}

func (m *CreateNodeRequest) GetInstallationMargin() float64 {
	if m != nil {
		return m.InstallationMargin
	}
	return 0
}

func (m *CreateNodeRequest) GetApplicationID() int64 {
	if m != nil {
		return m.ApplicationID
	}
	return 0
}

func (m *CreateNodeRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateNodeRequest) GetIsABP() bool {
	if m != nil {
		return m.IsABP
	}
	return false
}

func (m *CreateNodeRequest) GetIsClassC() bool {
	if m != nil {
		return m.IsClassC
	}
	return false
}

func (m *CreateNodeRequest) GetUseApplicationSettings() bool {
	if m != nil {
		return m.UseApplicationSettings
	}
	return false
}

type CreateNodeResponse struct {
}

func (m *CreateNodeResponse) Reset()                    { *m = CreateNodeResponse{} }
func (m *CreateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeResponse) ProtoMessage()               {}
func (*CreateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetNodeRequest struct {
	// Hex encoded DevEUI of the node.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *GetNodeRequest) Reset()                    { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()               {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetNodeRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

type GetNodeResponse struct {
	// Hex encoded DevEUI.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Hex encoded AppEUI.
	AppEUI string `protobuf:"bytes,2,opt,name=appEUI" json:"appEUI,omitempty"`
	// Hex encoded AppKey.
	AppKey string `protobuf:"bytes,3,opt,name=appKey" json:"appKey,omitempty"`
	// RX delay.
	RxDelay uint32 `protobuf:"varint,4,opt,name=rxDelay" json:"rxDelay,omitempty"`
	// RX1 data-rate offset.
	Rx1DROffset uint32 `protobuf:"varint,5,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	// RX window to use.
	RxWindow RXWindow `protobuf:"varint,7,opt,name=rxWindow,enum=api.RXWindow" json:"rxWindow,omitempty"`
	// Data-rate to use for RX2.
	Rx2DR uint32 `protobuf:"varint,8,opt,name=rx2DR" json:"rx2DR,omitempty"`
	// Name of the node.
	Name string `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	// Relax frame-counter mode is enabled.
	RelaxFCnt bool `protobuf:"varint,10,opt,name=relaxFCnt" json:"relaxFCnt,omitempty"`
	// Interval (in frames) in which the ADR engine may adapt the data-rate of the node (0 = disabled).
	AdrInterval uint32 `protobuf:"varint,11,opt,name=adrInterval" json:"adrInterval,omitempty"`
	// Installation-margin to use for ADR calculation.
	InstallationMargin float64 `protobuf:"fixed64,12,opt,name=installationMargin" json:"installationMargin,omitempty"`
	// Description of the node.
	Description string `protobuf:"bytes,13,opt,name=description" json:"description,omitempty"`
	// Node is activated by ABP.
	IsABP bool `protobuf:"varint,14,opt,name=isABP" json:"isABP,omitempty"`
	// ID of the application owning the node.
	ApplicationID int64 `protobuf:"varint,15,opt,name=applicationID" json:"applicationID,omitempty"`
	// Node operates in Class-C.
	IsClassC bool `protobuf:"varint,16,opt,name=isClassC" json:"isClassC,omitempty"`
	// When set to true, the application settings will be used to populate the node network settings.
	UseApplicationSettings bool `protobuf:"varint,17,opt,name=useApplicationSettings" json:"useApplicationSettings,omitempty"`
}

func (m *GetNodeResponse) Reset()                    { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()               {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetNodeResponse) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *GetNodeResponse) GetAppEUI() string {
	if m != nil {
		return m.AppEUI
	}
	return ""
}

func (m *GetNodeResponse) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *GetNodeResponse) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *GetNodeResponse) GetRx1DROffset() uint32 {
	if m != nil {
		return m.Rx1DROffset
	}
	return 0
}

func (m *GetNodeResponse) GetRxWindow() RXWindow {
	if m != nil {
		return m.RxWindow
	}
	return RXWindow_RX1
}

func (m *GetNodeResponse) GetRx2DR() uint32 {
	if m != nil {
		return m.Rx2DR
	}
	return 0
}

func (m *GetNodeResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetNodeResponse) GetRelaxFCnt() bool {
	if m != nil {
		return m.RelaxFCnt
	}
	return false
}

func (m *GetNodeResponse) GetAdrInterval() uint32 {
	if m != nil {
		return m.AdrInterval
	}
	return 0
}

func (m *GetNodeResponse) GetInstallationMargin() float64 {
	if m != nil {
		return m.InstallationMargin
	}
	return 0
}

func (m *GetNodeResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetNodeResponse) GetIsABP() bool {
	if m != nil {
		return m.IsABP
	}
	return false
}

func (m *GetNodeResponse) GetApplicationID() int64 {
	if m != nil {
		return m.ApplicationID
	}
	return 0
}

func (m *GetNodeResponse) GetIsClassC() bool {
	if m != nil {
		return m.IsClassC
	}
	return false
}

func (m *GetNodeResponse) GetUseApplicationSettings() bool {
	if m != nil {
		return m.UseApplicationSettings
	}
	return false
}

type DeleteNodeRequest struct {
	// Hex encoded DevEUI of the node.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *DeleteNodeRequest) Reset()                    { *m = DeleteNodeRequest{} }
func (m *DeleteNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeRequest) ProtoMessage()               {}
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteNodeRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

type DeleteNodeResponse struct {
}

func (m *DeleteNodeResponse) Reset()                    { *m = DeleteNodeResponse{} }
func (m *DeleteNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeResponse) ProtoMessage()               {}
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ListNodeByApplicationIDRequest struct {
	// ID of the application for which to list the nodes.
	ApplicationID int64 `protobuf:"varint,3,opt,name=applicationID" json:"applicationID,omitempty"`
	// Max number of nodes to return in the result-set.
	Limit int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset of the result-set (for pagination).
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *ListNodeByApplicationIDRequest) Reset()                    { *m = ListNodeByApplicationIDRequest{} }
func (m *ListNodeByApplicationIDRequest) String() string            { return proto.CompactTextString(m) }
func (*ListNodeByApplicationIDRequest) ProtoMessage()               {}
func (*ListNodeByApplicationIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ListNodeByApplicationIDRequest) GetApplicationID() int64 {
	if m != nil {
		return m.ApplicationID
	}
	return 0
}

func (m *ListNodeByApplicationIDRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListNodeByApplicationIDRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListNodeResponse struct {
	// Total number of nodes available within the result-set.
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	// Nodes within this result-set.
	Result []*GetNodeResponse `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListNodeResponse) Reset()                    { *m = ListNodeResponse{} }
func (m *ListNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*ListNodeResponse) ProtoMessage()               {}
func (*ListNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListNodeResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListNodeResponse) GetResult() []*GetNodeResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateNodeRequest struct {
	// Hex encoded DevEUI of the node to update.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Hex encoded AppEUI.
	AppEUI string `protobuf:"bytes,2,opt,name=appEUI" json:"appEUI,omitempty"`
	// Hex encoded AppKey.
	AppKey string `protobuf:"bytes,3,opt,name=appKey" json:"appKey,omitempty"`
	// RX delay.
	RxDelay uint32 `protobuf:"varint,4,opt,name=rxDelay" json:"rxDelay,omitempty"`
	// RX1 data-rate offset.
	Rx1DROffset uint32 `protobuf:"varint,5,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	// RX window to use.
	RxWindow RXWindow `protobuf:"varint,7,opt,name=rxWindow,enum=api.RXWindow" json:"rxWindow,omitempty"`
	// Data-rate to use for RX2.
	Rx2DR uint32 `protobuf:"varint,8,opt,name=rx2DR" json:"rx2DR,omitempty"`
	// Name of the node (note that renaming the node affects its api endpoint)
	Name string `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	// Relax frame-counter mode is enabled.
	RelaxFCnt bool `protobuf:"varint,10,opt,name=relaxFCnt" json:"relaxFCnt,omitempty"`
	// Interval (in frames) in which the ADR engine may adapt the data-rate of the node (0 = disabled).
	AdrInterval uint32 `protobuf:"varint,11,opt,name=adrInterval" json:"adrInterval,omitempty"`
	// Installation-margin to use for ADR calculation.
	InstallationMargin float64 `protobuf:"fixed64,12,opt,name=installationMargin" json:"installationMargin,omitempty"`
	// ID of the application owning the node.
	ApplicationID int64 `protobuf:"varint,13,opt,name=applicationID" json:"applicationID,omitempty"`
	// Description of the node.
	Description string `protobuf:"bytes,14,opt,name=description" json:"description,omitempty"`
	// Node is activated by ABP.
	IsABP bool `protobuf:"varint,15,opt,name=isABP" json:"isABP,omitempty"`
	// Node operates in Class-C.
	IsClassC bool `protobuf:"varint,16,opt,name=isClassC" json:"isClassC,omitempty"`
	// When set to true, the application settings will be used to populate the node network settings.
	UseApplicationSettings bool `protobuf:"varint,17,opt,name=useApplicationSettings" json:"useApplicationSettings,omitempty"`
}

func (m *UpdateNodeRequest) Reset()                    { *m = UpdateNodeRequest{} }
func (m *UpdateNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeRequest) ProtoMessage()               {}
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateNodeRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *UpdateNodeRequest) GetAppEUI() string {
	if m != nil {
		return m.AppEUI
	}
	return ""
}

func (m *UpdateNodeRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *UpdateNodeRequest) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *UpdateNodeRequest) GetRx1DROffset() uint32 {
	if m != nil {
		return m.Rx1DROffset
	}
	return 0
}

func (m *UpdateNodeRequest) GetRxWindow() RXWindow {
	if m != nil {
		return m.RxWindow
	}
	return RXWindow_RX1
}

func (m *UpdateNodeRequest) GetRx2DR() uint32 {
	if m != nil {
		return m.Rx2DR
	}
	return 0
}

func (m *UpdateNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateNodeRequest) GetRelaxFCnt() bool {
	if m != nil {
		return m.RelaxFCnt
	}
	return false
}

func (m *UpdateNodeRequest) GetAdrInterval() uint32 {
	if m != nil {
		return m.AdrInterval
	}
	return 0
}

func (m *UpdateNodeRequest) GetInstallationMargin() float64 {
	if m != nil {
		return m.InstallationMargin
	}
	return 0
}

func (m *UpdateNodeRequest) GetApplicationID() int64 {
	if m != nil {
		return m.ApplicationID
	}
	return 0
}

func (m *UpdateNodeRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateNodeRequest) GetIsABP() bool {
	if m != nil {
		return m.IsABP
	}
	return false
}

func (m *UpdateNodeRequest) GetIsClassC() bool {
	if m != nil {
		return m.IsClassC
	}
	return false
}

func (m *UpdateNodeRequest) GetUseApplicationSettings() bool {
	if m != nil {
		return m.UseApplicationSettings
	}
	return false
}

type UpdateNodeResponse struct {
}

func (m *UpdateNodeResponse) Reset()                    { *m = UpdateNodeResponse{} }
func (m *UpdateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeResponse) ProtoMessage()               {}
func (*UpdateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ActivateNodeRequest struct {
	// Hex encoded DevEUI of the node to activate.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Hex encoded DevAddr.
	DevAddr string `protobuf:"bytes,2,opt,name=devAddr" json:"devAddr,omitempty"`
	// Hex encoded AppSKey.
	AppSKey string `protobuf:"bytes,3,opt,name=appSKey" json:"appSKey,omitempty"`
	// Hex encoded NwkSKey.
	NwkSKey string `protobuf:"bytes,4,opt,name=nwkSKey" json:"nwkSKey,omitempty"`
	// Uplink frame-counter.
	FCntUp uint32 `protobuf:"varint,5,opt,name=fCntUp" json:"fCntUp,omitempty"`
	// Downlink frame-counter.
	FCntDown uint32 `protobuf:"varint,6,opt,name=fCntDown" json:"fCntDown,omitempty"`
}

func (m *ActivateNodeRequest) Reset()                    { *m = ActivateNodeRequest{} }
func (m *ActivateNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*ActivateNodeRequest) ProtoMessage()               {}
func (*ActivateNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ActivateNodeRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *ActivateNodeRequest) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func (m *ActivateNodeRequest) GetAppSKey() string {
	if m != nil {
		return m.AppSKey
	}
	return ""
}

func (m *ActivateNodeRequest) GetNwkSKey() string {
	if m != nil {
		return m.NwkSKey
	}
	return ""
}

func (m *ActivateNodeRequest) GetFCntUp() uint32 {
	if m != nil {
		return m.FCntUp
	}
	return 0
}

func (m *ActivateNodeRequest) GetFCntDown() uint32 {
	if m != nil {
		return m.FCntDown
	}
	return 0
}

type ActivateNodeResponse struct {
}

func (m *ActivateNodeResponse) Reset()                    { *m = ActivateNodeResponse{} }
func (m *ActivateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*ActivateNodeResponse) ProtoMessage()               {}
func (*ActivateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type GetNodeActivationRequest struct {
	// Hex encoded DevEUI of the node.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *GetNodeActivationRequest) Reset()                    { *m = GetNodeActivationRequest{} }
func (m *GetNodeActivationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeActivationRequest) ProtoMessage()               {}
func (*GetNodeActivationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetNodeActivationRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

type GetNodeActivationResponse struct {
	// Hex encoded DevAddr.
	DevAddr string `protobuf:"bytes,1,opt,name=devAddr" json:"devAddr,omitempty"`
	// Hex encoded AppSKey.
	AppSKey string `protobuf:"bytes,2,opt,name=appSKey" json:"appSKey,omitempty"`
	// Hex encoded NwkSKey.
	NwkSKey string `protobuf:"bytes,3,opt,name=nwkSKey" json:"nwkSKey,omitempty"`
	// Uplink frame-counter.
	FCntUp uint32 `protobuf:"varint,4,opt,name=fCntUp" json:"fCntUp,omitempty"`
	// Downlink frame-counter.
	FCntDown uint32 `protobuf:"varint,5,opt,name=fCntDown" json:"fCntDown,omitempty"`
}

func (m *GetNodeActivationResponse) Reset()                    { *m = GetNodeActivationResponse{} }
func (m *GetNodeActivationResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNodeActivationResponse) ProtoMessage()               {}
func (*GetNodeActivationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetNodeActivationResponse) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func (m *GetNodeActivationResponse) GetAppSKey() string {
	if m != nil {
		return m.AppSKey
	}
	return ""
}

func (m *GetNodeActivationResponse) GetNwkSKey() string {
	if m != nil {
		return m.NwkSKey
	}
	return ""
}

func (m *GetNodeActivationResponse) GetFCntUp() uint32 {
	if m != nil {
		return m.FCntUp
	}
	return 0
}

func (m *GetNodeActivationResponse) GetFCntDown() uint32 {
	if m != nil {
		return m.FCntDown
	}
	return 0
}

type GetRandomDevAddrRequest struct {
}

func (m *GetRandomDevAddrRequest) Reset()                    { *m = GetRandomDevAddrRequest{} }
func (m *GetRandomDevAddrRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRandomDevAddrRequest) ProtoMessage()               {}
func (*GetRandomDevAddrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type GetRandomDevAddrResponse struct {
	// Hex encoded DevAddr.
	DevAddr string `protobuf:"bytes,1,opt,name=devAddr" json:"devAddr,omitempty"`
}

func (m *GetRandomDevAddrResponse) Reset()                    { *m = GetRandomDevAddrResponse{} }
func (m *GetRandomDevAddrResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRandomDevAddrResponse) ProtoMessage()               {}
func (*GetRandomDevAddrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetRandomDevAddrResponse) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

type GetFrameLogsRequest struct {
	// Hex encoded DevEUI.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Max number of frames to return in the result-set.
	Limit int64 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	// Offset of the result-set (for pagination).
	Offset int64 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *GetFrameLogsRequest) Reset()                    { *m = GetFrameLogsRequest{} }
func (m *GetFrameLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFrameLogsRequest) ProtoMessage()               {}
func (*GetFrameLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetFrameLogsRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *GetFrameLogsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetFrameLogsRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetFrameLogsResponse struct {
	// Total number of logs.
	TotalCount int32 `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	// The result-set.
	Result []*FrameLog `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *GetFrameLogsResponse) Reset()                    { *m = GetFrameLogsResponse{} }
func (m *GetFrameLogsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFrameLogsResponse) ProtoMessage()               {}
func (*GetFrameLogsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetFrameLogsResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *GetFrameLogsResponse) GetResult() []*FrameLog {
	if m != nil {
		return m.Result
	}
	return nil
}

type FrameLog struct {
	// Timestamp of when the frame was logged.
	CreatedAt string `protobuf:"bytes,1,opt,name=createdAt" json:"createdAt,omitempty"`
	// RX-info set (in case of an uplink).
	RxInfoSet []*RXInfo `protobuf:"bytes,2,rep,name=rxInfoSet" json:"rxInfoSet,omitempty"`
	// TX-info (in case of a downlink).
	TxInfo *TXInfo `protobuf:"bytes,3,opt,name=txInfo" json:"txInfo,omitempty"`
	// LoRaWAN PHYPayload as a JSON string.
	PhyPayloadJSON string `protobuf:"bytes,4,opt,name=phyPayloadJSON" json:"phyPayloadJSON,omitempty"`
}

func (m *FrameLog) Reset()                    { *m = FrameLog{} }
func (m *FrameLog) String() string            { return proto.CompactTextString(m) }
func (*FrameLog) ProtoMessage()               {}
func (*FrameLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *FrameLog) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *FrameLog) GetRxInfoSet() []*RXInfo {
	if m != nil {
		return m.RxInfoSet
	}
	return nil
}

func (m *FrameLog) GetTxInfo() *TXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *FrameLog) GetPhyPayloadJSON() string {
	if m != nil {
		return m.PhyPayloadJSON
	}
	return ""
}

type DataRate struct {
	Modulation   string `protobuf:"bytes,1,opt,name=modulation" json:"modulation,omitempty"`
	BandWidth    uint32 `protobuf:"varint,2,opt,name=bandWidth" json:"bandWidth,omitempty"`
	SpreadFactor uint32 `protobuf:"varint,3,opt,name=spreadFactor" json:"spreadFactor,omitempty"`
	Bitrate      uint32 `protobuf:"varint,4,opt,name=bitrate" json:"bitrate,omitempty"`
}

func (m *DataRate) Reset()                    { *m = DataRate{} }
func (m *DataRate) String() string            { return proto.CompactTextString(m) }
func (*DataRate) ProtoMessage()               {}
func (*DataRate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DataRate) GetModulation() string {
	if m != nil {
		return m.Modulation
	}
	return ""
}

func (m *DataRate) GetBandWidth() uint32 {
	if m != nil {
		return m.BandWidth
	}
	return 0
}

func (m *DataRate) GetSpreadFactor() uint32 {
	if m != nil {
		return m.SpreadFactor
	}
	return 0
}

func (m *DataRate) GetBitrate() uint32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

type RXInfo struct {
	// Channel number on which the frame was received.
	Channel int32 `protobuf:"varint,1,opt,name=channel" json:"channel,omitempty"`
	// Code-rate.
	CodeRate string `protobuf:"bytes,2,opt,name=codeRate" json:"codeRate,omitempty"`
	// frequency.
	Frequency int64 `protobuf:"varint,3,opt,name=frequency" json:"frequency,omitempty"`
	// LoRa SNR.
	LoRaSNR float64 `protobuf:"fixed64,4,opt,name=loRaSNR" json:"loRaSNR,omitempty"`
	// RSSI / signal strength.
	Rssi int32 `protobuf:"varint,5,opt,name=rssi" json:"rssi,omitempty"`
	// Time (when the gateway has a GPS).
	Time string `protobuf:"bytes,6,opt,name=time" json:"time,omitempty"`
	// Gateway internal timestamp.
	Timestamp uint32 `protobuf:"varint,7,opt,name=timestamp" json:"timestamp,omitempty"`
	// Data-rate.
	DataRate *DataRate `protobuf:"bytes,8,opt,name=dataRate" json:"dataRate,omitempty"`
	// HEX encoded gateway MAC.
	Mac string `protobuf:"bytes,9,opt,name=mac" json:"mac,omitempty"`
}

func (m *RXInfo) Reset()                    { *m = RXInfo{} }
func (m *RXInfo) String() string            { return proto.CompactTextString(m) }
func (*RXInfo) ProtoMessage()               {}
func (*RXInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *RXInfo) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *RXInfo) GetCodeRate() string {
	if m != nil {
		return m.CodeRate
	}
	return ""
}

func (m *RXInfo) GetFrequency() int64 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *RXInfo) GetLoRaSNR() float64 {
	if m != nil {
		return m.LoRaSNR
	}
	return 0
}

func (m *RXInfo) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *RXInfo) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *RXInfo) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RXInfo) GetDataRate() *DataRate {
	if m != nil {
		return m.DataRate
	}
	return nil
}

func (m *RXInfo) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type TXInfo struct {
	// Code-rate.
	CodeRate string `protobuf:"bytes,1,opt,name=codeRate" json:"codeRate,omitempty"`
	// Frequency.
	Frequency int64 `protobuf:"varint,2,opt,name=frequency" json:"frequency,omitempty"`
	// Immediately.
	Immediately bool `protobuf:"varint,3,opt,name=immediately" json:"immediately,omitempty"`
	// HEX encoded gateway MAC.
	Mac string `protobuf:"bytes,4,opt,name=mac" json:"mac,omitempty"`
	// TX power.
	Power int32 `protobuf:"varint,5,opt,name=power" json:"power,omitempty"`
	// Gateway internal timestamp.
	Timestamp uint32 `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	// Data-rate.
	DataRate *DataRate `protobuf:"bytes,7,opt,name=dataRate" json:"dataRate,omitempty"`
}

func (m *TXInfo) Reset()                    { *m = TXInfo{} }
func (m *TXInfo) String() string            { return proto.CompactTextString(m) }
func (*TXInfo) ProtoMessage()               {}
func (*TXInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *TXInfo) GetCodeRate() string {
	if m != nil {
		return m.CodeRate
	}
	return ""
}

func (m *TXInfo) GetFrequency() int64 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *TXInfo) GetImmediately() bool {
	if m != nil {
		return m.Immediately
	}
	return false
}

func (m *TXInfo) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *TXInfo) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *TXInfo) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TXInfo) GetDataRate() *DataRate {
	if m != nil {
		return m.DataRate
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateNodeRequest)(nil), "api.CreateNodeRequest")
	proto.RegisterType((*CreateNodeResponse)(nil), "api.CreateNodeResponse")
	proto.RegisterType((*GetNodeRequest)(nil), "api.GetNodeRequest")
	proto.RegisterType((*GetNodeResponse)(nil), "api.GetNodeResponse")
	proto.RegisterType((*DeleteNodeRequest)(nil), "api.DeleteNodeRequest")
	proto.RegisterType((*DeleteNodeResponse)(nil), "api.DeleteNodeResponse")
	proto.RegisterType((*ListNodeByApplicationIDRequest)(nil), "api.ListNodeByApplicationIDRequest")
	proto.RegisterType((*ListNodeResponse)(nil), "api.ListNodeResponse")
	proto.RegisterType((*UpdateNodeRequest)(nil), "api.UpdateNodeRequest")
	proto.RegisterType((*UpdateNodeResponse)(nil), "api.UpdateNodeResponse")
	proto.RegisterType((*ActivateNodeRequest)(nil), "api.ActivateNodeRequest")
	proto.RegisterType((*ActivateNodeResponse)(nil), "api.ActivateNodeResponse")
	proto.RegisterType((*GetNodeActivationRequest)(nil), "api.GetNodeActivationRequest")
	proto.RegisterType((*GetNodeActivationResponse)(nil), "api.GetNodeActivationResponse")
	proto.RegisterType((*GetRandomDevAddrRequest)(nil), "api.GetRandomDevAddrRequest")
	proto.RegisterType((*GetRandomDevAddrResponse)(nil), "api.GetRandomDevAddrResponse")
	proto.RegisterType((*GetFrameLogsRequest)(nil), "api.GetFrameLogsRequest")
	proto.RegisterType((*GetFrameLogsResponse)(nil), "api.GetFrameLogsResponse")
	proto.RegisterType((*FrameLog)(nil), "api.FrameLog")
	proto.RegisterType((*DataRate)(nil), "api.DataRate")
	proto.RegisterType((*RXInfo)(nil), "api.RXInfo")
	proto.RegisterType((*TXInfo)(nil), "api.TXInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	// Create creates the given node.
	Create(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	// Get returns the node for the requested DevEUI.
	Get(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// Delete deletes the node matching the given DevEUI.
	Delete(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error)
	// ListByApplicationID lists the nodes by the given application ID, sorted by the name of the node.
	ListByApplicationID(ctx context.Context, in *ListNodeByApplicationIDRequest, opts ...grpc.CallOption) (*ListNodeResponse, error)
	// Update updates the node matching the given DevEUI.
	Update(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error)
	// Activate (re)activates the node (only when ABP is set to true).
	Activate(ctx context.Context, in *ActivateNodeRequest, opts ...grpc.CallOption) (*ActivateNodeResponse, error)
	// GetActivation returns the current activation details of the node (OTAA and ABP).
	GetActivation(ctx context.Context, in *GetNodeActivationRequest, opts ...grpc.CallOption) (*GetNodeActivationResponse, error)
	// GetRandomDevAddr returns a random DevAddr taking the NwkID prefix into account.
	GetRandomDevAddr(ctx context.Context, in *GetRandomDevAddrRequest, opts ...grpc.CallOption) (*GetRandomDevAddrResponse, error)
	// GetFrameLogs returns the uplink / downlink frame log for the given DevEUI.
	GetFrameLogs(ctx context.Context, in *GetFrameLogsRequest, opts ...grpc.CallOption) (*GetFrameLogsResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Create(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	out := new(CreateNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Get(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	out := new(GetNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Delete(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error) {
	out := new(DeleteNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ListByApplicationID(ctx context.Context, in *ListNodeByApplicationIDRequest, opts ...grpc.CallOption) (*ListNodeResponse, error) {
	out := new(ListNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/ListByApplicationID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Update(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error) {
	out := new(UpdateNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Activate(ctx context.Context, in *ActivateNodeRequest, opts ...grpc.CallOption) (*ActivateNodeResponse, error) {
	out := new(ActivateNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Activate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetActivation(ctx context.Context, in *GetNodeActivationRequest, opts ...grpc.CallOption) (*GetNodeActivationResponse, error) {
	out := new(GetNodeActivationResponse)
	err := grpc.Invoke(ctx, "/api.Node/GetActivation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetRandomDevAddr(ctx context.Context, in *GetRandomDevAddrRequest, opts ...grpc.CallOption) (*GetRandomDevAddrResponse, error) {
	out := new(GetRandomDevAddrResponse)
	err := grpc.Invoke(ctx, "/api.Node/GetRandomDevAddr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetFrameLogs(ctx context.Context, in *GetFrameLogsRequest, opts ...grpc.CallOption) (*GetFrameLogsResponse, error) {
	out := new(GetFrameLogsResponse)
	err := grpc.Invoke(ctx, "/api.Node/GetFrameLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	// Create creates the given node.
	Create(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	// Get returns the node for the requested DevEUI.
	Get(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// Delete deletes the node matching the given DevEUI.
	Delete(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error)
	// ListByApplicationID lists the nodes by the given application ID, sorted by the name of the node.
	ListByApplicationID(context.Context, *ListNodeByApplicationIDRequest) (*ListNodeResponse, error)
	// Update updates the node matching the given DevEUI.
	Update(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error)
	// Activate (re)activates the node (only when ABP is set to true).
	Activate(context.Context, *ActivateNodeRequest) (*ActivateNodeResponse, error)
	// GetActivation returns the current activation details of the node (OTAA and ABP).
	GetActivation(context.Context, *GetNodeActivationRequest) (*GetNodeActivationResponse, error)
	// GetRandomDevAddr returns a random DevAddr taking the NwkID prefix into account.
	GetRandomDevAddr(context.Context, *GetRandomDevAddrRequest) (*GetRandomDevAddrResponse, error)
	// GetFrameLogs returns the uplink / downlink frame log for the given DevEUI.
	GetFrameLogs(context.Context, *GetFrameLogsRequest) (*GetFrameLogsResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Create(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Get(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Delete(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ListByApplicationID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeByApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ListByApplicationID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/ListByApplicationID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ListByApplicationID(ctx, req.(*ListNodeByApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Update(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Activate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Activate(ctx, req.(*ActivateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/GetActivation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetActivation(ctx, req.(*GetNodeActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetRandomDevAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomDevAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetRandomDevAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/GetRandomDevAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetRandomDevAddr(ctx, req.(*GetRandomDevAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetFrameLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrameLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetFrameLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/GetFrameLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetFrameLogs(ctx, req.(*GetFrameLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Node_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Node_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Node_Delete_Handler,
		},
		{
			MethodName: "ListByApplicationID",
			Handler:    _Node_ListByApplicationID_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Node_Update_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _Node_Activate_Handler,
		},
		{
			MethodName: "GetActivation",
			Handler:    _Node_GetActivation_Handler,
		},
		{
			MethodName: "GetRandomDevAddr",
			Handler:    _Node_GetRandomDevAddr_Handler,
		},
		{
			MethodName: "GetFrameLogs",
			Handler:    _Node_GetFrameLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}

func init() { proto.RegisterFile("node.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4d, 0x6f, 0x23, 0x45,
	0x13, 0xd6, 0xf8, 0x2b, 0x4e, 0x25, 0x4e, 0xb2, 0x1d, 0x6f, 0x76, 0xd6, 0x9b, 0x8d, 0xac, 0xc9,
	0xfb, 0x2e, 0xce, 0x82, 0x62, 0x11, 0x10, 0x07, 0x6e, 0x5e, 0x9b, 0x8d, 0xc2, 0x7e, 0xaa, 0xc3,
	0xb2, 0x20, 0x84, 0x44, 0xaf, 0xa7, 0xed, 0x0c, 0xcc, 0x74, 0x0f, 0x33, 0x9d, 0xc4, 0xd6, 0x6a,
	0x2f, 0x7b, 0xe0, 0x84, 0xb8, 0x70, 0x46, 0x42, 0xfc, 0x01, 0x7e, 0x0c, 0xe2, 0x1f, 0xf0, 0x27,
	0xb8, 0xa1, 0xfe, 0x98, 0xf1, 0xd8, 0x1e, 0x27, 0x39, 0xc0, 0x2d, 0xa7, 0x4c, 0x3d, 0xd5, 0xae,
	0xaa, 0xa7, 0xe7, 0xe9, 0xaa, 0x9e, 0x00, 0x30, 0xee, 0xd2, 0xfd, 0x30, 0xe2, 0x82, 0xa3, 0x22,
	0x09, 0xbd, 0xc6, 0xf6, 0x90, 0xf3, 0xa1, 0x4f, 0xdb, 0x24, 0xf4, 0xda, 0x84, 0x31, 0x2e, 0x88,
	0xf0, 0x38, 0x8b, 0xf5, 0x92, 0xc6, 0x6a, 0x9f, 0x07, 0x01, 0x67, 0xda, 0x72, 0x7e, 0x2a, 0xc1,
	0x8d, 0x6e, 0x44, 0x89, 0xa0, 0x4f, 0xb9, 0x4b, 0x31, 0xfd, 0xfe, 0x94, 0xc6, 0x02, 0x6d, 0x41,
	0xc5, 0xa5, 0x67, 0x9f, 0xbc, 0x38, 0xb2, 0xad, 0xa6, 0xd5, 0x5a, 0xc6, 0xc6, 0x92, 0x38, 0x09,
	0x43, 0x89, 0x17, 0x34, 0xae, 0x2d, 0x83, 0x3f, 0xa2, 0x63, 0xbb, 0x98, 0xe2, 0x8f, 0xe8, 0x18,
	0xd9, 0xb0, 0x14, 0x8d, 0x7a, 0xd4, 0x27, 0x63, 0xbb, 0xd4, 0xb4, 0x5a, 0x35, 0x9c, 0x98, 0xa8,
	0x09, 0x2b, 0xd1, 0xe8, 0xfd, 0x1e, 0x7e, 0x36, 0x18, 0xc4, 0x54, 0xd8, 0x65, 0xe5, 0xcd, 0x42,
	0x68, 0x0f, 0xaa, 0xd1, 0xe8, 0xa5, 0xc7, 0x5c, 0x7e, 0x6e, 0x2f, 0x35, 0xad, 0xd6, 0xda, 0x41,
	0x6d, 0x9f, 0x84, 0xde, 0x3e, 0xfe, 0x42, 0x83, 0x38, 0x75, 0xa3, 0x3a, 0x94, 0xa3, 0xd1, 0x41,
	0x0f, 0xdb, 0x55, 0x15, 0x46, 0x1b, 0x08, 0x41, 0x89, 0x91, 0x80, 0xda, 0xcb, 0xaa, 0x24, 0xf5,
	0x8c, 0xb6, 0x61, 0x39, 0xa2, 0x3e, 0x19, 0x3d, 0xec, 0x32, 0x61, 0x43, 0xd3, 0x6a, 0x55, 0xf1,
	0x04, 0x90, 0x45, 0x11, 0x37, 0x3a, 0x62, 0x82, 0x46, 0x67, 0xc4, 0xb7, 0x57, 0x74, 0x51, 0x19,
	0x08, 0xed, 0x03, 0xf2, 0x58, 0x2c, 0x88, 0xef, 0xab, 0x3d, 0x7d, 0x42, 0xa2, 0xa1, 0xc7, 0xec,
	0xd5, 0xa6, 0xd5, 0xb2, 0x70, 0x8e, 0x07, 0xfd, 0x0f, 0x6a, 0x24, 0x0c, 0x7d, 0xaf, 0xaf, 0xc0,
	0xa3, 0x9e, 0x5d, 0x6b, 0x5a, 0xad, 0x22, 0x9e, 0x06, 0x65, 0x5e, 0x97, 0xc6, 0xfd, 0xc8, 0x0b,
	0x25, 0x60, 0xaf, 0xa9, 0x82, 0xb3, 0x90, 0x64, 0xe8, 0xc5, 0x9d, 0x07, 0xcf, 0xed, 0x75, 0x55,
	0xb3, 0x36, 0x50, 0x03, 0xaa, 0x5e, 0xdc, 0xf5, 0x49, 0x1c, 0x77, 0xed, 0x0d, 0xe5, 0x48, 0x6d,
	0xf4, 0x11, 0x6c, 0x9d, 0xc6, 0xb4, 0x33, 0xc9, 0x73, 0x4c, 0x85, 0xf0, 0xd8, 0x30, 0xb6, 0x6f,
	0xa8, 0x95, 0x0b, 0xbc, 0x4e, 0x1d, 0x50, 0x56, 0x0f, 0x71, 0xc8, 0x59, 0x4c, 0x9d, 0x16, 0xac,
	0x1d, 0x52, 0x71, 0x05, 0x89, 0x38, 0x3f, 0x96, 0x60, 0x3d, 0x5d, 0xaa, 0x7f, 0x7d, 0x2d, 0xa7,
	0x7f, 0x4b, 0x4e, 0x33, 0x42, 0xa9, 0x5d, 0x20, 0x94, 0xb5, 0xac, 0x50, 0xe6, 0x64, 0xb8, 0x9e,
	0x27, 0xc3, 0xff, 0x42, 0x4e, 0xef, 0xc2, 0x8d, 0x1e, 0xf5, 0xe9, 0x95, 0xda, 0x8b, 0xd4, 0x5e,
	0x76, 0xb1, 0xd1, 0x9e, 0x80, 0x9d, 0xc7, 0x5e, 0xac, 0x14, 0xf5, 0x60, 0xdc, 0xc9, 0x56, 0x9c,
	0xc4, 0x9b, 0xa3, 0x57, 0xcc, 0xa3, 0x57, 0x87, 0xb2, 0xef, 0x05, 0x9e, 0x50, 0x49, 0x8b, 0x58,
	0x1b, 0xb2, 0x16, 0xae, 0x45, 0x53, 0x50, 0xb0, 0xb1, 0x9c, 0x6f, 0x60, 0x23, 0xc9, 0x9a, 0xea,
	0x78, 0x07, 0x40, 0x70, 0x41, 0xfc, 0x2e, 0x3f, 0x65, 0x49, 0x98, 0x0c, 0x82, 0xde, 0x83, 0x4a,
	0x44, 0xe3, 0x53, 0x5f, 0xc6, 0x2a, 0xb6, 0x56, 0x0e, 0xea, 0x4a, 0x61, 0x33, 0xa7, 0x01, 0x9b,
	0x35, 0xaa, 0xf5, 0xbe, 0x08, 0xdd, 0xeb, 0xd6, 0x7b, 0xdd, 0x7a, 0xd3, 0xd6, 0x9b, 0xd5, 0x83,
	0x91, 0xff, 0xef, 0x16, 0x6c, 0x76, 0xfa, 0xc2, 0x3b, 0xbb, 0xa2, 0x50, 0x6c, 0x58, 0x72, 0xe9,
	0x59, 0xc7, 0x75, 0x23, 0xa3, 0x94, 0xc4, 0x94, 0x1e, 0x12, 0x86, 0xc7, 0x13, 0xad, 0x24, 0xa6,
	0xf4, 0xb0, 0xf3, 0xef, 0x94, 0xa7, 0xa4, 0x3d, 0xc6, 0x94, 0x59, 0x06, 0x5d, 0x26, 0x5e, 0x84,
	0x46, 0x27, 0xc6, 0x92, 0xfc, 0xe5, 0x53, 0x8f, 0x9f, 0x33, 0xbb, 0xa2, 0x3c, 0xa9, 0xed, 0x6c,
	0x41, 0x7d, 0xba, 0x60, 0xc3, 0xe4, 0x00, 0x6c, 0x73, 0x16, 0x8c, 0xdb, 0xe3, 0xec, 0xb2, 0x96,
	0xf0, 0x8b, 0x05, 0xb7, 0x73, 0x7e, 0x64, 0x0e, 0x64, 0x86, 0xab, 0xb5, 0x90, 0x6b, 0x61, 0x21,
	0xd7, 0xe2, 0x22, 0xae, 0xa5, 0x85, 0x5c, 0xcb, 0x33, 0x5c, 0x6f, 0xc3, 0xad, 0x43, 0x2a, 0x30,
	0x61, 0x2e, 0x0f, 0x7a, 0x3a, 0xb7, 0xa1, 0xe4, 0x7c, 0xa8, 0xe8, 0xce, 0xb8, 0x2e, 0x2b, 0xdc,
	0xf9, 0x0a, 0x36, 0x0f, 0xa9, 0x78, 0x18, 0x91, 0x80, 0x3e, 0xe6, 0xc3, 0xf8, 0xb2, 0xb7, 0x9d,
	0x36, 0xb5, 0x42, 0x7e, 0x53, 0x2b, 0x4e, 0x35, 0xb5, 0xaf, 0xa1, 0x3e, 0x1d, 0x7c, 0x61, 0x63,
	0x2b, 0x4f, 0x35, 0xb6, 0xff, 0xcf, 0x34, 0x36, 0xdd, 0x0e, 0x92, 0x38, 0x69, 0x47, 0xfb, 0xd5,
	0x82, 0x6a, 0x02, 0xca, 0xf3, 0xde, 0x57, 0x17, 0x09, 0xb7, 0x23, 0x4c, 0xd1, 0x13, 0x00, 0xed,
	0xc1, 0x72, 0x34, 0x3a, 0x62, 0x03, 0x7e, 0x4c, 0x93, 0xa0, 0x2b, 0xa6, 0xc7, 0x48, 0x14, 0x4f,
	0xbc, 0x68, 0x17, 0x2a, 0x42, 0x19, 0x8a, 0x4c, 0xb2, 0xee, 0x33, 0xbd, 0xce, 0xb8, 0xd0, 0x3d,
	0x58, 0x0b, 0x4f, 0xc6, 0xcf, 0xc9, 0xd8, 0xe7, 0xc4, 0xfd, 0xf4, 0xf8, 0xd9, 0x53, 0x23, 0xe4,
	0x19, 0xd4, 0xf9, 0xc1, 0x82, 0x6a, 0x8f, 0x08, 0x82, 0x89, 0x50, 0xb4, 0x03, 0xee, 0x9e, 0xea,
	0xb6, 0x61, 0x6a, 0xcc, 0x20, 0x92, 0xc2, 0x2b, 0xc2, 0xdc, 0x97, 0x9e, 0x2b, 0x4e, 0xd4, 0x06,
	0xd7, 0xf0, 0x04, 0x40, 0x0e, 0xac, 0xc6, 0x61, 0x44, 0x89, 0xfb, 0x90, 0xf4, 0x05, 0x8f, 0x54,
	0x75, 0x35, 0x3c, 0x85, 0xc9, 0xf7, 0xfc, 0xca, 0x13, 0x11, 0x11, 0x34, 0xe9, 0xc2, 0xc6, 0x74,
	0xfe, 0xb6, 0xa0, 0xa2, 0xb9, 0xca, 0x45, 0xfd, 0x13, 0xc2, 0x18, 0xf5, 0xcd, 0xd6, 0x27, 0xa6,
	0x54, 0x5e, 0x5f, 0x9e, 0x20, 0xf9, 0x7b, 0x2d, 0xe3, 0xd4, 0x96, 0xc5, 0x0d, 0x22, 0xa9, 0x0e,
	0xd6, 0x1f, 0x9b, 0xd7, 0x3c, 0x01, 0x64, 0x4c, 0x9f, 0x63, 0x72, 0xfc, 0x14, 0xab, 0xc4, 0x16,
	0x4e, 0x4c, 0xd9, 0x9b, 0xa3, 0x38, 0xf6, 0x94, 0x92, 0xcb, 0x58, 0x3d, 0x4b, 0x4c, 0x78, 0x01,
	0x55, 0x27, 0x79, 0x19, 0xab, 0x67, 0x19, 0x5f, 0xfe, 0x8d, 0x05, 0x09, 0x42, 0x35, 0x05, 0x6a,
	0x78, 0x02, 0xc8, 0x11, 0xe1, 0x9a, 0x6d, 0x54, 0xad, 0x3f, 0xd1, 0x44, 0xb2, 0xb7, 0x38, 0x75,
	0xa3, 0x0d, 0x28, 0x06, 0xa4, 0x6f, 0x66, 0x81, 0x7c, 0x74, 0xfe, 0xb4, 0xa0, 0xa2, 0xdf, 0xdf,
	0x14, 0x43, 0xeb, 0x22, 0x86, 0x85, 0x59, 0x86, 0x4d, 0x58, 0xf1, 0x82, 0x80, 0xba, 0x1e, 0x11,
	0xd4, 0xd7, 0x3b, 0x50, 0xc5, 0x59, 0x28, 0x49, 0x5c, 0x4a, 0x13, 0xcb, 0xd3, 0x12, 0xf2, 0x73,
	0x1a, 0x19, 0xf2, 0xda, 0x98, 0x66, 0x5a, 0xb9, 0x88, 0xe9, 0xd2, 0x85, 0x4c, 0x0f, 0x7e, 0x5b,
	0x82, 0x92, 0xec, 0x54, 0xe8, 0x39, 0x54, 0xf4, 0x25, 0x1a, 0x6d, 0xa9, 0xb5, 0x73, 0x5f, 0x58,
	0x8d, 0x5b, 0x73, 0xb8, 0x69, 0x92, 0x37, 0xdf, 0xfe, 0xf1, 0xd7, 0xcf, 0x85, 0x75, 0x07, 0xd4,
	0xe7, 0x9b, 0xfc, 0xb4, 0x8b, 0x3f, 0xb6, 0xee, 0xa3, 0x27, 0x50, 0x3c, 0xa4, 0x02, 0x6d, 0x4e,
	0xdf, 0x28, 0x74, 0xac, 0xdc, 0x6b, 0x86, 0x73, 0x47, 0x05, 0xba, 0x89, 0x36, 0x27, 0x81, 0xda,
	0xaf, 0x75, 0xd7, 0x78, 0x83, 0x3e, 0x87, 0x8a, 0xbe, 0x69, 0x99, 0x02, 0xe7, 0xee, 0x68, 0xa6,
	0xc0, 0x9c, 0xeb, 0x98, 0x89, 0x7b, 0x3f, 0x37, 0xee, 0x5b, 0x0b, 0x36, 0xe5, 0xb5, 0x69, 0xe6,
	0xa2, 0x86, 0x76, 0x55, 0xb4, 0x8b, 0xaf, 0x71, 0x8d, 0x9b, 0x53, 0x8b, 0xd2, 0x84, 0x6d, 0x95,
	0x70, 0x0f, 0xbd, 0xa3, 0x3f, 0x68, 0x27, 0xbf, 0x8c, 0xdb, 0xaf, 0xa7, 0x86, 0xf9, 0x1b, 0x5d,
	0x0d, 0xfa, 0x12, 0x2a, 0x7a, 0x8e, 0x1a, 0x72, 0x73, 0x97, 0x2c, 0x43, 0x2e, 0x67, 0xd8, 0xee,
	0xa8, 0x5c, 0x76, 0x23, 0x8f, 0x9c, 0x7c, 0x0d, 0xdf, 0x42, 0x35, 0x19, 0x6d, 0xc8, 0x56, 0x41,
	0x72, 0x46, 0x73, 0xe3, 0x76, 0x8e, 0xc7, 0x24, 0xd8, 0x53, 0x09, 0x76, 0x9d, 0x9d, 0x9c, 0x04,
	0x6d, 0x92, 0x4e, 0x38, 0x99, 0xeb, 0x0c, 0x6a, 0x87, 0x54, 0x4c, 0xa6, 0x1e, 0xba, 0x9b, 0x7d,
	0xcf, 0x73, 0x23, 0xb4, 0xb1, 0xb3, 0xc8, 0x6d, 0x52, 0xdf, 0x53, 0xa9, 0x9b, 0xe8, 0x92, 0xd4,
	0x48, 0xc0, 0xc6, 0xec, 0xdc, 0x42, 0xdb, 0x49, 0xec, 0xbc, 0x49, 0xd7, 0xb8, 0xbb, 0xc0, 0x6b,
	0x12, 0xef, 0xaa, 0xc4, 0x77, 0x9d, 0x3b, 0x99, 0xc4, 0xc3, 0xd9, 0x0c, 0x43, 0x58, 0xcd, 0x8e,
	0x26, 0xb3, 0xbb, 0x39, 0xa3, 0xd0, 0xec, 0x6e, 0xde, 0x1c, 0x73, 0x1c, 0x95, 0x69, 0x1b, 0x35,
	0xf2, 0x28, 0x0e, 0xe4, 0xf2, 0xf8, 0x55, 0x45, 0xfd, 0xe3, 0xe3, 0x83, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x74, 0xab, 0x8c, 0x51, 0x37, 0x11, 0x00, 0x00,
}
