// Code generated by protoc-gen-go.
// source: node.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateNodeRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// hex encoded AppEUI
	AppEUI string `protobuf:"bytes,2,opt,name=appEUI" json:"appEUI,omitempty"`
	// hex encoded AppKey
	AppKey             string   `protobuf:"bytes,3,opt,name=appKey" json:"appKey,omitempty"`
	RxDelay            uint32   `protobuf:"varint,4,opt,name=rxDelay" json:"rxDelay,omitempty"`
	Rx1DROffset        uint32   `protobuf:"varint,5,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	ChannelListID      int64    `protobuf:"varint,6,opt,name=channelListID" json:"channelListID,omitempty"`
	RxWindow           RXWindow `protobuf:"varint,7,opt,name=rxWindow,enum=api.RXWindow" json:"rxWindow,omitempty"`
	Rx2DR              uint32   `protobuf:"varint,8,opt,name=rx2DR" json:"rx2DR,omitempty"`
	Name               string   `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	RelaxFCnt          bool     `protobuf:"varint,10,opt,name=relaxFCnt" json:"relaxFCnt,omitempty"`
	AdrInterval        uint32   `protobuf:"varint,11,opt,name=adrInterval" json:"adrInterval,omitempty"`
	InstallationMargin float64  `protobuf:"fixed64,12,opt,name=installationMargin" json:"installationMargin,omitempty"`
	// name of the application to which the node must be linked
	ApplicationName string `protobuf:"bytes,13,opt,name=applicationName" json:"applicationName,omitempty"`
}

func (m *CreateNodeRequest) Reset()                    { *m = CreateNodeRequest{} }
func (m *CreateNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeRequest) ProtoMessage()               {}
func (*CreateNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *CreateNodeRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *CreateNodeRequest) GetAppEUI() string {
	if m != nil {
		return m.AppEUI
	}
	return ""
}

func (m *CreateNodeRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *CreateNodeRequest) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *CreateNodeRequest) GetRx1DROffset() uint32 {
	if m != nil {
		return m.Rx1DROffset
	}
	return 0
}

func (m *CreateNodeRequest) GetChannelListID() int64 {
	if m != nil {
		return m.ChannelListID
	}
	return 0
}

func (m *CreateNodeRequest) GetRxWindow() RXWindow {
	if m != nil {
		return m.RxWindow
	}
	return RXWindow_RX1
}

func (m *CreateNodeRequest) GetRx2DR() uint32 {
	if m != nil {
		return m.Rx2DR
	}
	return 0
}

func (m *CreateNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateNodeRequest) GetRelaxFCnt() bool {
	if m != nil {
		return m.RelaxFCnt
	}
	return false
}

func (m *CreateNodeRequest) GetAdrInterval() uint32 {
	if m != nil {
		return m.AdrInterval
	}
	return 0
}

func (m *CreateNodeRequest) GetInstallationMargin() float64 {
	if m != nil {
		return m.InstallationMargin
	}
	return 0
}

func (m *CreateNodeRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

type CreateNodeResponse struct {
}

func (m *CreateNodeResponse) Reset()                    { *m = CreateNodeResponse{} }
func (m *CreateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeResponse) ProtoMessage()               {}
func (*CreateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type GetNodeRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// name of the application to which the node is linked
	ApplicationName string `protobuf:"bytes,2,opt,name=applicationName" json:"applicationName,omitempty"`
}

func (m *GetNodeRequest) Reset()                    { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()               {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetNodeRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *GetNodeRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

type GetNodeResponse struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// hex encoded AppEUI
	AppEUI string `protobuf:"bytes,2,opt,name=appEUI" json:"appEUI,omitempty"`
	// hex encoded AppKey
	AppKey             string   `protobuf:"bytes,3,opt,name=appKey" json:"appKey,omitempty"`
	RxDelay            uint32   `protobuf:"varint,4,opt,name=rxDelay" json:"rxDelay,omitempty"`
	Rx1DROffset        uint32   `protobuf:"varint,5,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	ChannelListID      int64    `protobuf:"varint,6,opt,name=channelListID" json:"channelListID,omitempty"`
	RxWindow           RXWindow `protobuf:"varint,7,opt,name=rxWindow,enum=api.RXWindow" json:"rxWindow,omitempty"`
	Rx2DR              uint32   `protobuf:"varint,8,opt,name=rx2DR" json:"rx2DR,omitempty"`
	Name               string   `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	RelaxFCnt          bool     `protobuf:"varint,10,opt,name=relaxFCnt" json:"relaxFCnt,omitempty"`
	AdrInterval        uint32   `protobuf:"varint,11,opt,name=adrInterval" json:"adrInterval,omitempty"`
	InstallationMargin float64  `protobuf:"fixed64,12,opt,name=installationMargin" json:"installationMargin,omitempty"`
}

func (m *GetNodeResponse) Reset()                    { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()               {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GetNodeResponse) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *GetNodeResponse) GetAppEUI() string {
	if m != nil {
		return m.AppEUI
	}
	return ""
}

func (m *GetNodeResponse) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *GetNodeResponse) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *GetNodeResponse) GetRx1DROffset() uint32 {
	if m != nil {
		return m.Rx1DROffset
	}
	return 0
}

func (m *GetNodeResponse) GetChannelListID() int64 {
	if m != nil {
		return m.ChannelListID
	}
	return 0
}

func (m *GetNodeResponse) GetRxWindow() RXWindow {
	if m != nil {
		return m.RxWindow
	}
	return RXWindow_RX1
}

func (m *GetNodeResponse) GetRx2DR() uint32 {
	if m != nil {
		return m.Rx2DR
	}
	return 0
}

func (m *GetNodeResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetNodeResponse) GetRelaxFCnt() bool {
	if m != nil {
		return m.RelaxFCnt
	}
	return false
}

func (m *GetNodeResponse) GetAdrInterval() uint32 {
	if m != nil {
		return m.AdrInterval
	}
	return 0
}

func (m *GetNodeResponse) GetInstallationMargin() float64 {
	if m != nil {
		return m.InstallationMargin
	}
	return 0
}

type DeleteNodeRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// name of the application to which the node is linked
	ApplicationName string `protobuf:"bytes,2,opt,name=applicationName" json:"applicationName,omitempty"`
}

func (m *DeleteNodeRequest) Reset()                    { *m = DeleteNodeRequest{} }
func (m *DeleteNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeRequest) ProtoMessage()               {}
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *DeleteNodeRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *DeleteNodeRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

type DeleteNodeResponse struct {
}

func (m *DeleteNodeResponse) Reset()                    { *m = DeleteNodeResponse{} }
func (m *DeleteNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeResponse) ProtoMessage()               {}
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type ListNodeRequest struct {
	Limit  int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	// name of the application for which to list the nodes
	ApplicationName string `protobuf:"bytes,3,opt,name=applicationName" json:"applicationName,omitempty"`
}

func (m *ListNodeRequest) Reset()                    { *m = ListNodeRequest{} }
func (m *ListNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*ListNodeRequest) ProtoMessage()               {}
func (*ListNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ListNodeRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListNodeRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListNodeRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

type ListNodeResponse struct {
	TotalCount int64              `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	Result     []*GetNodeResponse `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListNodeResponse) Reset()                    { *m = ListNodeResponse{} }
func (m *ListNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*ListNodeResponse) ProtoMessage()               {}
func (*ListNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ListNodeResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListNodeResponse) GetResult() []*GetNodeResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateNodeRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// hex encoded AppEUI
	AppEUI string `protobuf:"bytes,2,opt,name=appEUI" json:"appEUI,omitempty"`
	// hex encoded AppKey
	AppKey             string   `protobuf:"bytes,3,opt,name=appKey" json:"appKey,omitempty"`
	RxDelay            uint32   `protobuf:"varint,4,opt,name=rxDelay" json:"rxDelay,omitempty"`
	Rx1DROffset        uint32   `protobuf:"varint,5,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	ChannelListID      int64    `protobuf:"varint,6,opt,name=channelListID" json:"channelListID,omitempty"`
	RxWindow           RXWindow `protobuf:"varint,7,opt,name=rxWindow,enum=api.RXWindow" json:"rxWindow,omitempty"`
	Rx2DR              uint32   `protobuf:"varint,8,opt,name=rx2DR" json:"rx2DR,omitempty"`
	Name               string   `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	RelaxFCnt          bool     `protobuf:"varint,10,opt,name=relaxFCnt" json:"relaxFCnt,omitempty"`
	AdrInterval        uint32   `protobuf:"varint,11,opt,name=adrInterval" json:"adrInterval,omitempty"`
	InstallationMargin float64  `protobuf:"fixed64,12,opt,name=installationMargin" json:"installationMargin,omitempty"`
	// name of the application to which the node is linked
	ApplicationName string `protobuf:"bytes,13,opt,name=applicationName" json:"applicationName,omitempty"`
}

func (m *UpdateNodeRequest) Reset()                    { *m = UpdateNodeRequest{} }
func (m *UpdateNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeRequest) ProtoMessage()               {}
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *UpdateNodeRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *UpdateNodeRequest) GetAppEUI() string {
	if m != nil {
		return m.AppEUI
	}
	return ""
}

func (m *UpdateNodeRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *UpdateNodeRequest) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *UpdateNodeRequest) GetRx1DROffset() uint32 {
	if m != nil {
		return m.Rx1DROffset
	}
	return 0
}

func (m *UpdateNodeRequest) GetChannelListID() int64 {
	if m != nil {
		return m.ChannelListID
	}
	return 0
}

func (m *UpdateNodeRequest) GetRxWindow() RXWindow {
	if m != nil {
		return m.RxWindow
	}
	return RXWindow_RX1
}

func (m *UpdateNodeRequest) GetRx2DR() uint32 {
	if m != nil {
		return m.Rx2DR
	}
	return 0
}

func (m *UpdateNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateNodeRequest) GetRelaxFCnt() bool {
	if m != nil {
		return m.RelaxFCnt
	}
	return false
}

func (m *UpdateNodeRequest) GetAdrInterval() uint32 {
	if m != nil {
		return m.AdrInterval
	}
	return 0
}

func (m *UpdateNodeRequest) GetInstallationMargin() float64 {
	if m != nil {
		return m.InstallationMargin
	}
	return 0
}

func (m *UpdateNodeRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

type UpdateNodeResponse struct {
}

func (m *UpdateNodeResponse) Reset()                    { *m = UpdateNodeResponse{} }
func (m *UpdateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeResponse) ProtoMessage()               {}
func (*UpdateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func init() {
	proto.RegisterType((*CreateNodeRequest)(nil), "api.CreateNodeRequest")
	proto.RegisterType((*CreateNodeResponse)(nil), "api.CreateNodeResponse")
	proto.RegisterType((*GetNodeRequest)(nil), "api.GetNodeRequest")
	proto.RegisterType((*GetNodeResponse)(nil), "api.GetNodeResponse")
	proto.RegisterType((*DeleteNodeRequest)(nil), "api.DeleteNodeRequest")
	proto.RegisterType((*DeleteNodeResponse)(nil), "api.DeleteNodeResponse")
	proto.RegisterType((*ListNodeRequest)(nil), "api.ListNodeRequest")
	proto.RegisterType((*ListNodeResponse)(nil), "api.ListNodeResponse")
	proto.RegisterType((*UpdateNodeRequest)(nil), "api.UpdateNodeRequest")
	proto.RegisterType((*UpdateNodeResponse)(nil), "api.UpdateNodeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	// Create creates the given node.
	Create(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	// Get returns the node for the requested DevEUI.
	Get(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// Delete deletes the node matching the given DevEUI.
	Delete(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error)
	// List lists the nodes.
	List(ctx context.Context, in *ListNodeRequest, opts ...grpc.CallOption) (*ListNodeResponse, error)
	// Update updates the node matching the given DevEUI.
	Update(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Create(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	out := new(CreateNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Get(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	out := new(GetNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Delete(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error) {
	out := new(DeleteNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) List(ctx context.Context, in *ListNodeRequest, opts ...grpc.CallOption) (*ListNodeResponse, error) {
	out := new(ListNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Update(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error) {
	out := new(UpdateNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	// Create creates the given node.
	Create(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	// Get returns the node for the requested DevEUI.
	Get(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// Delete deletes the node matching the given DevEUI.
	Delete(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error)
	// List lists the nodes.
	List(context.Context, *ListNodeRequest) (*ListNodeResponse, error)
	// Update updates the node matching the given DevEUI.
	Update(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Create(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Get(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Delete(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).List(ctx, req.(*ListNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Update(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Node_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Node_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Node_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Node_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Node_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}

func init() { proto.RegisterFile("node.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 642 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xec, 0x96, 0xd1, 0x4a, 0x1b, 0x4d,
	0x14, 0xc7, 0xd9, 0x6c, 0x5c, 0xf5, 0x68, 0xf4, 0xf3, 0x7c, 0xa9, 0x5d, 0x82, 0x94, 0x65, 0xe9,
	0xc5, 0x6a, 0x4b, 0x82, 0xa9, 0x50, 0x10, 0x7a, 0x65, 0x5a, 0x11, 0x5b, 0x0b, 0x03, 0xd2, 0x5e,
	0x76, 0x6a, 0x46, 0x3b, 0x30, 0x99, 0xd9, 0xee, 0x4e, 0x6c, 0x44, 0x84, 0xd2, 0x57, 0xe8, 0x6b,
	0xf4, 0x19, 0xfa, 0x12, 0x7d, 0x85, 0x3e, 0x48, 0xd9, 0x99, 0xd1, 0xac, 0xc9, 0x5e, 0x04, 0x2f,
	0x0a, 0x05, 0xef, 0x72, 0xfe, 0xb3, 0xcc, 0xef, 0x9c, 0x39, 0xff, 0x33, 0x13, 0x00, 0xa9, 0xfa,
	0xac, 0x9d, 0x66, 0x4a, 0x2b, 0xf4, 0x69, 0xca, 0x5b, 0x1b, 0x67, 0x4a, 0x9d, 0x09, 0xd6, 0xa1,
	0x29, 0xef, 0x50, 0x29, 0x95, 0xa6, 0x9a, 0x2b, 0x99, 0xdb, 0x4f, 0x5a, 0xcb, 0x27, 0x6a, 0x30,
	0x50, 0xd2, 0x46, 0xf1, 0x0f, 0x1f, 0xd6, 0xf6, 0x32, 0x46, 0x35, 0x3b, 0x52, 0x7d, 0x46, 0xd8,
	0xe7, 0x21, 0xcb, 0x35, 0xae, 0x43, 0xd0, 0x67, 0xe7, 0x2f, 0x8f, 0x0f, 0x42, 0x2f, 0xf2, 0x92,
	0x45, 0xe2, 0xa2, 0x42, 0xa7, 0x69, 0x5a, 0xe8, 0x35, 0xab, 0xdb, 0xc8, 0xe9, 0x87, 0xec, 0x22,
	0xf4, 0x6f, 0xf4, 0x43, 0x76, 0x81, 0x21, 0xcc, 0x67, 0xa3, 0x1e, 0x13, 0xf4, 0x22, 0xac, 0x47,
	0x5e, 0xd2, 0x20, 0xd7, 0x21, 0x46, 0xb0, 0x94, 0x8d, 0xb6, 0x7b, 0xe4, 0xed, 0xe9, 0x69, 0xce,
	0x74, 0x38, 0x67, 0x56, 0xcb, 0x12, 0x3e, 0x86, 0xc6, 0xc9, 0x27, 0x2a, 0x25, 0x13, 0xaf, 0x79,
	0xae, 0x0f, 0x7a, 0x61, 0x10, 0x79, 0x89, 0x4f, 0x6e, 0x8b, 0xb8, 0x09, 0x0b, 0xd9, 0xe8, 0x1d,
	0x97, 0x7d, 0xf5, 0x25, 0x9c, 0x8f, 0xbc, 0x64, 0xa5, 0xdb, 0x68, 0xd3, 0x94, 0xb7, 0xc9, 0x7b,
	0x2b, 0x92, 0x9b, 0x65, 0x6c, 0xc2, 0x5c, 0x36, 0xea, 0xf6, 0x48, 0xb8, 0x60, 0x60, 0x36, 0x40,
	0x84, 0xba, 0xa4, 0x03, 0x16, 0x2e, 0x9a, 0xc4, 0xcd, 0x6f, 0xdc, 0x80, 0xc5, 0x8c, 0x09, 0x3a,
	0x7a, 0xb5, 0x27, 0x75, 0x08, 0x91, 0x97, 0x2c, 0x90, 0xb1, 0x50, 0xa4, 0x4e, 0xfb, 0xd9, 0x81,
	0xd4, 0x2c, 0x3b, 0xa7, 0x22, 0x5c, 0xb2, 0xa9, 0x97, 0x24, 0x6c, 0x03, 0x72, 0x99, 0x6b, 0x2a,
	0x84, 0x39, 0xf9, 0x37, 0x34, 0x3b, 0xe3, 0x32, 0x5c, 0x8e, 0xbc, 0xc4, 0x23, 0x15, 0x2b, 0x98,
	0xc0, 0x2a, 0x4d, 0x53, 0xc1, 0x4f, 0x8c, 0x78, 0x54, 0xa4, 0xd3, 0x30, 0xe9, 0x4c, 0xca, 0x71,
	0x13, 0xb0, 0xdc, 0xad, 0x3c, 0x55, 0x32, 0x67, 0x31, 0x81, 0x95, 0x7d, 0xa6, 0x67, 0x69, 0x60,
	0x05, 0xa9, 0x56, 0x4d, 0xfa, 0xea, 0xc3, 0xea, 0xcd, 0xa6, 0x96, 0x73, 0x6f, 0x8b, 0xbf, 0x6a,
	0x8b, 0xf8, 0x18, 0xd6, 0x7a, 0x4c, 0xb0, 0xd9, 0x46, 0x73, 0xf6, 0xce, 0x36, 0x01, 0xcb, 0xdb,
	0x3a, 0x0f, 0x71, 0x58, 0x2d, 0xce, 0xae, 0x8c, 0x6a, 0xc2, 0x9c, 0xe0, 0x03, 0xae, 0x0d, 0xc9,
	0x27, 0x36, 0x28, 0x12, 0x50, 0xb6, 0x3b, 0x35, 0x23, 0xbb, 0xa8, 0x2a, 0x01, 0xbf, 0x3a, 0x81,
	0x0f, 0xf0, 0xdf, 0x18, 0xe5, 0xac, 0xf5, 0x08, 0x40, 0x2b, 0x4d, 0xc5, 0x9e, 0x1a, 0xca, 0x6b,
	0x60, 0x49, 0xc1, 0xa7, 0x10, 0x64, 0x2c, 0x1f, 0x8a, 0x82, 0xea, 0x27, 0x4b, 0xdd, 0xa6, 0x69,
	0xe7, 0x84, 0x41, 0x89, 0xfb, 0xc6, 0xdc, 0x6a, 0xc7, 0x69, 0xff, 0xfe, 0x56, 0xfb, 0x67, 0x6e,
	0xb5, 0x72, 0xb7, 0x6c, 0x33, 0xbb, 0x3f, 0xeb, 0x50, 0x2f, 0x04, 0x54, 0x10, 0xd8, 0x4b, 0x0f,
	0xd7, 0xcd, 0x29, 0x4c, 0xbd, 0x57, 0xad, 0x87, 0x53, 0xba, 0x73, 0xf5, 0xce, 0xb7, 0x5f, 0xbf,
	0xbf, 0xd7, 0xda, 0xf1, 0xa6, 0x7d, 0x0c, 0xc7, 0xdc, 0xbc, 0x73, 0x39, 0x91, 0xc5, 0x55, 0xa7,
	0x78, 0x47, 0xf3, 0x5d, 0x6f, 0x0b, 0x05, 0xf8, 0xfb, 0x4c, 0xe3, 0xff, 0xb7, 0x3d, 0x66, 0x51,
	0x95, 0xc6, 0x8b, 0x77, 0x0d, 0x67, 0x07, 0xbb, 0x33, 0x73, 0x3a, 0x97, 0xd6, 0x7d, 0x57, 0x38,
	0x84, 0xc0, 0xce, 0xa3, 0x2b, 0x6f, 0x6a, 0xe6, 0x5d, 0x79, 0x15, 0x43, 0xeb, 0xb0, 0x5b, 0x77,
	0xc1, 0x9e, 0x42, 0xbd, 0x70, 0x1b, 0xda, 0x82, 0x26, 0x66, 0xbf, 0xf5, 0x60, 0x42, 0x75, 0xc0,
	0x6d, 0x03, 0x7c, 0x82, 0xb3, 0x9f, 0x27, 0x8e, 0x20, 0xb0, 0xcd, 0x75, 0xe5, 0x4d, 0xcd, 0xa5,
	0x2b, 0x6f, 0xda, 0x01, 0xf1, 0x0b, 0x43, 0x7b, 0xde, 0xba, 0x43, 0x79, 0xbb, 0xde, 0xd6, 0xc7,
	0xc0, 0xfc, 0xc5, 0x79, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0xad, 0x23, 0x4c, 0x4a, 0x21, 0x09,
	0x00, 0x00,
}
