// Code generated by protoc-gen-go.
// source: nodeSession.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateNodeSessionRequest struct {
	// hex encoded DevAddr
	DevAddr string `protobuf:"bytes,1,opt,name=devAddr" json:"devAddr,omitempty"`
	// name of the application to which the node is linked
	ApplicationName string `protobuf:"bytes,2,opt,name=applicationName" json:"applicationName,omitempty"`
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,3,opt,name=devEUI" json:"devEUI,omitempty"`
	// hex encoded AppSKey
	AppSKey string `protobuf:"bytes,4,opt,name=appSKey" json:"appSKey,omitempty"`
	// hex encoded NwkSKey
	NwkSKey            string   `protobuf:"bytes,5,opt,name=nwkSKey" json:"nwkSKey,omitempty"`
	FCntUp             uint32   `protobuf:"varint,6,opt,name=fCntUp" json:"fCntUp,omitempty"`
	FCntDown           uint32   `protobuf:"varint,7,opt,name=fCntDown" json:"fCntDown,omitempty"`
	RxDelay            uint32   `protobuf:"varint,8,opt,name=rxDelay" json:"rxDelay,omitempty"`
	Rx1DROffset        uint32   `protobuf:"varint,9,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	CFList             []uint32 `protobuf:"varint,10,rep,packed,name=cFList" json:"cFList,omitempty"`
	RxWindow           RXWindow `protobuf:"varint,11,opt,name=rxWindow,enum=api.RXWindow" json:"rxWindow,omitempty"`
	Rx2DR              uint32   `protobuf:"varint,12,opt,name=rx2DR" json:"rx2DR,omitempty"`
	RelaxFCnt          bool     `protobuf:"varint,13,opt,name=relaxFCnt" json:"relaxFCnt,omitempty"`
	AdrInterval        uint32   `protobuf:"varint,14,opt,name=adrInterval" json:"adrInterval,omitempty"`
	InstallationMargin float64  `protobuf:"fixed64,15,opt,name=installationMargin" json:"installationMargin,omitempty"`
}

func (m *CreateNodeSessionRequest) Reset()                    { *m = CreateNodeSessionRequest{} }
func (m *CreateNodeSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeSessionRequest) ProtoMessage()               {}
func (*CreateNodeSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *CreateNodeSessionRequest) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func (m *CreateNodeSessionRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *CreateNodeSessionRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *CreateNodeSessionRequest) GetAppSKey() string {
	if m != nil {
		return m.AppSKey
	}
	return ""
}

func (m *CreateNodeSessionRequest) GetNwkSKey() string {
	if m != nil {
		return m.NwkSKey
	}
	return ""
}

func (m *CreateNodeSessionRequest) GetFCntUp() uint32 {
	if m != nil {
		return m.FCntUp
	}
	return 0
}

func (m *CreateNodeSessionRequest) GetFCntDown() uint32 {
	if m != nil {
		return m.FCntDown
	}
	return 0
}

func (m *CreateNodeSessionRequest) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *CreateNodeSessionRequest) GetRx1DROffset() uint32 {
	if m != nil {
		return m.Rx1DROffset
	}
	return 0
}

func (m *CreateNodeSessionRequest) GetCFList() []uint32 {
	if m != nil {
		return m.CFList
	}
	return nil
}

func (m *CreateNodeSessionRequest) GetRxWindow() RXWindow {
	if m != nil {
		return m.RxWindow
	}
	return RXWindow_RX1
}

func (m *CreateNodeSessionRequest) GetRx2DR() uint32 {
	if m != nil {
		return m.Rx2DR
	}
	return 0
}

func (m *CreateNodeSessionRequest) GetRelaxFCnt() bool {
	if m != nil {
		return m.RelaxFCnt
	}
	return false
}

func (m *CreateNodeSessionRequest) GetAdrInterval() uint32 {
	if m != nil {
		return m.AdrInterval
	}
	return 0
}

func (m *CreateNodeSessionRequest) GetInstallationMargin() float64 {
	if m != nil {
		return m.InstallationMargin
	}
	return 0
}

type CreateNodeSessionResponse struct {
}

func (m *CreateNodeSessionResponse) Reset()                    { *m = CreateNodeSessionResponse{} }
func (m *CreateNodeSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeSessionResponse) ProtoMessage()               {}
func (*CreateNodeSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type GetNodeSessionRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// name of the application to which the node is linked
	ApplicationName string `protobuf:"bytes,2,opt,name=applicationName" json:"applicationName,omitempty"`
}

func (m *GetNodeSessionRequest) Reset()                    { *m = GetNodeSessionRequest{} }
func (m *GetNodeSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeSessionRequest) ProtoMessage()               {}
func (*GetNodeSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *GetNodeSessionRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *GetNodeSessionRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

type GetNodeSessionResponse struct {
	// hex encoded DevAddr
	DevAddr string `protobuf:"bytes,1,opt,name=devAddr" json:"devAddr,omitempty"`
	// hex encoded AppEUI
	AppEUI string `protobuf:"bytes,2,opt,name=appEUI" json:"appEUI,omitempty"`
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,3,opt,name=devEUI" json:"devEUI,omitempty"`
	// hex encoded AppSKey
	AppSKey string `protobuf:"bytes,4,opt,name=appSKey" json:"appSKey,omitempty"`
	// hex encoded NwkSKey
	NwkSKey            string   `protobuf:"bytes,5,opt,name=nwkSKey" json:"nwkSKey,omitempty"`
	FCntUp             uint32   `protobuf:"varint,6,opt,name=fCntUp" json:"fCntUp,omitempty"`
	FCntDown           uint32   `protobuf:"varint,7,opt,name=fCntDown" json:"fCntDown,omitempty"`
	RxDelay            uint32   `protobuf:"varint,8,opt,name=rxDelay" json:"rxDelay,omitempty"`
	Rx1DROffset        uint32   `protobuf:"varint,9,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	CFList             []uint32 `protobuf:"varint,10,rep,packed,name=cFList" json:"cFList,omitempty"`
	RxWindow           RXWindow `protobuf:"varint,11,opt,name=rxWindow,enum=api.RXWindow" json:"rxWindow,omitempty"`
	Rx2DR              uint32   `protobuf:"varint,12,opt,name=rx2DR" json:"rx2DR,omitempty"`
	RelaxFCnt          bool     `protobuf:"varint,13,opt,name=relaxFCnt" json:"relaxFCnt,omitempty"`
	AdrInterval        uint32   `protobuf:"varint,14,opt,name=adrInterval" json:"adrInterval,omitempty"`
	InstallationMargin float64  `protobuf:"fixed64,15,opt,name=installationMargin" json:"installationMargin,omitempty"`
	NbTrans            uint32   `protobuf:"varint,16,opt,name=nbTrans" json:"nbTrans,omitempty"`
	TxPower            uint32   `protobuf:"varint,17,opt,name=txPower" json:"txPower,omitempty"`
}

func (m *GetNodeSessionResponse) Reset()                    { *m = GetNodeSessionResponse{} }
func (m *GetNodeSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNodeSessionResponse) ProtoMessage()               {}
func (*GetNodeSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *GetNodeSessionResponse) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func (m *GetNodeSessionResponse) GetAppEUI() string {
	if m != nil {
		return m.AppEUI
	}
	return ""
}

func (m *GetNodeSessionResponse) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *GetNodeSessionResponse) GetAppSKey() string {
	if m != nil {
		return m.AppSKey
	}
	return ""
}

func (m *GetNodeSessionResponse) GetNwkSKey() string {
	if m != nil {
		return m.NwkSKey
	}
	return ""
}

func (m *GetNodeSessionResponse) GetFCntUp() uint32 {
	if m != nil {
		return m.FCntUp
	}
	return 0
}

func (m *GetNodeSessionResponse) GetFCntDown() uint32 {
	if m != nil {
		return m.FCntDown
	}
	return 0
}

func (m *GetNodeSessionResponse) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *GetNodeSessionResponse) GetRx1DROffset() uint32 {
	if m != nil {
		return m.Rx1DROffset
	}
	return 0
}

func (m *GetNodeSessionResponse) GetCFList() []uint32 {
	if m != nil {
		return m.CFList
	}
	return nil
}

func (m *GetNodeSessionResponse) GetRxWindow() RXWindow {
	if m != nil {
		return m.RxWindow
	}
	return RXWindow_RX1
}

func (m *GetNodeSessionResponse) GetRx2DR() uint32 {
	if m != nil {
		return m.Rx2DR
	}
	return 0
}

func (m *GetNodeSessionResponse) GetRelaxFCnt() bool {
	if m != nil {
		return m.RelaxFCnt
	}
	return false
}

func (m *GetNodeSessionResponse) GetAdrInterval() uint32 {
	if m != nil {
		return m.AdrInterval
	}
	return 0
}

func (m *GetNodeSessionResponse) GetInstallationMargin() float64 {
	if m != nil {
		return m.InstallationMargin
	}
	return 0
}

func (m *GetNodeSessionResponse) GetNbTrans() uint32 {
	if m != nil {
		return m.NbTrans
	}
	return 0
}

func (m *GetNodeSessionResponse) GetTxPower() uint32 {
	if m != nil {
		return m.TxPower
	}
	return 0
}

type UpdateNodeSessionRequest struct {
	// hex encoded DevAddr
	DevAddr string `protobuf:"bytes,1,opt,name=devAddr" json:"devAddr,omitempty"`
	// name of the application to which the node is linked
	ApplicationName string `protobuf:"bytes,2,opt,name=applicationName" json:"applicationName,omitempty"`
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,3,opt,name=devEUI" json:"devEUI,omitempty"`
	// hex encoded AppSKey
	AppSKey string `protobuf:"bytes,4,opt,name=appSKey" json:"appSKey,omitempty"`
	// hex encoded NwkSKey
	NwkSKey            string   `protobuf:"bytes,5,opt,name=nwkSKey" json:"nwkSKey,omitempty"`
	FCntUp             uint32   `protobuf:"varint,6,opt,name=fCntUp" json:"fCntUp,omitempty"`
	FCntDown           uint32   `protobuf:"varint,7,opt,name=fCntDown" json:"fCntDown,omitempty"`
	RxDelay            uint32   `protobuf:"varint,8,opt,name=rxDelay" json:"rxDelay,omitempty"`
	Rx1DROffset        uint32   `protobuf:"varint,9,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	CFList             []uint32 `protobuf:"varint,10,rep,packed,name=cFList" json:"cFList,omitempty"`
	RxWindow           RXWindow `protobuf:"varint,11,opt,name=rxWindow,enum=api.RXWindow" json:"rxWindow,omitempty"`
	Rx2DR              uint32   `protobuf:"varint,12,opt,name=rx2DR" json:"rx2DR,omitempty"`
	RelaxFCnt          bool     `protobuf:"varint,13,opt,name=relaxFCnt" json:"relaxFCnt,omitempty"`
	AdrInterval        uint32   `protobuf:"varint,14,opt,name=adrInterval" json:"adrInterval,omitempty"`
	InstallationMargin float64  `protobuf:"fixed64,15,opt,name=installationMargin" json:"installationMargin,omitempty"`
}

func (m *UpdateNodeSessionRequest) Reset()                    { *m = UpdateNodeSessionRequest{} }
func (m *UpdateNodeSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeSessionRequest) ProtoMessage()               {}
func (*UpdateNodeSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *UpdateNodeSessionRequest) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func (m *UpdateNodeSessionRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *UpdateNodeSessionRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *UpdateNodeSessionRequest) GetAppSKey() string {
	if m != nil {
		return m.AppSKey
	}
	return ""
}

func (m *UpdateNodeSessionRequest) GetNwkSKey() string {
	if m != nil {
		return m.NwkSKey
	}
	return ""
}

func (m *UpdateNodeSessionRequest) GetFCntUp() uint32 {
	if m != nil {
		return m.FCntUp
	}
	return 0
}

func (m *UpdateNodeSessionRequest) GetFCntDown() uint32 {
	if m != nil {
		return m.FCntDown
	}
	return 0
}

func (m *UpdateNodeSessionRequest) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *UpdateNodeSessionRequest) GetRx1DROffset() uint32 {
	if m != nil {
		return m.Rx1DROffset
	}
	return 0
}

func (m *UpdateNodeSessionRequest) GetCFList() []uint32 {
	if m != nil {
		return m.CFList
	}
	return nil
}

func (m *UpdateNodeSessionRequest) GetRxWindow() RXWindow {
	if m != nil {
		return m.RxWindow
	}
	return RXWindow_RX1
}

func (m *UpdateNodeSessionRequest) GetRx2DR() uint32 {
	if m != nil {
		return m.Rx2DR
	}
	return 0
}

func (m *UpdateNodeSessionRequest) GetRelaxFCnt() bool {
	if m != nil {
		return m.RelaxFCnt
	}
	return false
}

func (m *UpdateNodeSessionRequest) GetAdrInterval() uint32 {
	if m != nil {
		return m.AdrInterval
	}
	return 0
}

func (m *UpdateNodeSessionRequest) GetInstallationMargin() float64 {
	if m != nil {
		return m.InstallationMargin
	}
	return 0
}

type UpdateNodeSessionResponse struct {
}

func (m *UpdateNodeSessionResponse) Reset()                    { *m = UpdateNodeSessionResponse{} }
func (m *UpdateNodeSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeSessionResponse) ProtoMessage()               {}
func (*UpdateNodeSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

type DeleteNodeSessionRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// name of the application to which the node is linked
	ApplicationName string `protobuf:"bytes,2,opt,name=applicationName" json:"applicationName,omitempty"`
}

func (m *DeleteNodeSessionRequest) Reset()                    { *m = DeleteNodeSessionRequest{} }
func (m *DeleteNodeSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeSessionRequest) ProtoMessage()               {}
func (*DeleteNodeSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *DeleteNodeSessionRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *DeleteNodeSessionRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

type DeleteNodeSessionResponse struct {
}

func (m *DeleteNodeSessionResponse) Reset()                    { *m = DeleteNodeSessionResponse{} }
func (m *DeleteNodeSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeSessionResponse) ProtoMessage()               {}
func (*DeleteNodeSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

type GetRandomDevAddrRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// name of the application to which the node is linked
	ApplicationName string `protobuf:"bytes,2,opt,name=applicationName" json:"applicationName,omitempty"`
}

func (m *GetRandomDevAddrRequest) Reset()                    { *m = GetRandomDevAddrRequest{} }
func (m *GetRandomDevAddrRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRandomDevAddrRequest) ProtoMessage()               {}
func (*GetRandomDevAddrRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *GetRandomDevAddrRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *GetRandomDevAddrRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

type GetRandomDevAddrResponse struct {
	// hex encoded DevAddr
	DevAddr string `protobuf:"bytes,1,opt,name=devAddr" json:"devAddr,omitempty"`
}

func (m *GetRandomDevAddrResponse) Reset()                    { *m = GetRandomDevAddrResponse{} }
func (m *GetRandomDevAddrResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRandomDevAddrResponse) ProtoMessage()               {}
func (*GetRandomDevAddrResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *GetRandomDevAddrResponse) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateNodeSessionRequest)(nil), "api.CreateNodeSessionRequest")
	proto.RegisterType((*CreateNodeSessionResponse)(nil), "api.CreateNodeSessionResponse")
	proto.RegisterType((*GetNodeSessionRequest)(nil), "api.GetNodeSessionRequest")
	proto.RegisterType((*GetNodeSessionResponse)(nil), "api.GetNodeSessionResponse")
	proto.RegisterType((*UpdateNodeSessionRequest)(nil), "api.UpdateNodeSessionRequest")
	proto.RegisterType((*UpdateNodeSessionResponse)(nil), "api.UpdateNodeSessionResponse")
	proto.RegisterType((*DeleteNodeSessionRequest)(nil), "api.DeleteNodeSessionRequest")
	proto.RegisterType((*DeleteNodeSessionResponse)(nil), "api.DeleteNodeSessionResponse")
	proto.RegisterType((*GetRandomDevAddrRequest)(nil), "api.GetRandomDevAddrRequest")
	proto.RegisterType((*GetRandomDevAddrResponse)(nil), "api.GetRandomDevAddrResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeSession service

type NodeSessionClient interface {
	// Create creates the given node-session. The DevAddr must contain the same NwkID as the configured NetID. Node-sessions will expire automatically after the configured TTL.
	Create(ctx context.Context, in *CreateNodeSessionRequest, opts ...grpc.CallOption) (*CreateNodeSessionResponse, error)
	// Get returns the node-session matching the given DevEUI.
	Get(ctx context.Context, in *GetNodeSessionRequest, opts ...grpc.CallOption) (*GetNodeSessionResponse, error)
	// Update updates the given node-session.
	Update(ctx context.Context, in *UpdateNodeSessionRequest, opts ...grpc.CallOption) (*UpdateNodeSessionResponse, error)
	// Delete deletes the node-session matching the given DevEUI.
	Delete(ctx context.Context, in *DeleteNodeSessionRequest, opts ...grpc.CallOption) (*DeleteNodeSessionResponse, error)
	// GetRandomDevAddr returns a random DevAddr taking the NwkID prefix into account.
	GetRandomDevAddr(ctx context.Context, in *GetRandomDevAddrRequest, opts ...grpc.CallOption) (*GetRandomDevAddrResponse, error)
}

type nodeSessionClient struct {
	cc *grpc.ClientConn
}

func NewNodeSessionClient(cc *grpc.ClientConn) NodeSessionClient {
	return &nodeSessionClient{cc}
}

func (c *nodeSessionClient) Create(ctx context.Context, in *CreateNodeSessionRequest, opts ...grpc.CallOption) (*CreateNodeSessionResponse, error) {
	out := new(CreateNodeSessionResponse)
	err := grpc.Invoke(ctx, "/api.NodeSession/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeSessionClient) Get(ctx context.Context, in *GetNodeSessionRequest, opts ...grpc.CallOption) (*GetNodeSessionResponse, error) {
	out := new(GetNodeSessionResponse)
	err := grpc.Invoke(ctx, "/api.NodeSession/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeSessionClient) Update(ctx context.Context, in *UpdateNodeSessionRequest, opts ...grpc.CallOption) (*UpdateNodeSessionResponse, error) {
	out := new(UpdateNodeSessionResponse)
	err := grpc.Invoke(ctx, "/api.NodeSession/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeSessionClient) Delete(ctx context.Context, in *DeleteNodeSessionRequest, opts ...grpc.CallOption) (*DeleteNodeSessionResponse, error) {
	out := new(DeleteNodeSessionResponse)
	err := grpc.Invoke(ctx, "/api.NodeSession/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeSessionClient) GetRandomDevAddr(ctx context.Context, in *GetRandomDevAddrRequest, opts ...grpc.CallOption) (*GetRandomDevAddrResponse, error) {
	out := new(GetRandomDevAddrResponse)
	err := grpc.Invoke(ctx, "/api.NodeSession/GetRandomDevAddr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeSession service

type NodeSessionServer interface {
	// Create creates the given node-session. The DevAddr must contain the same NwkID as the configured NetID. Node-sessions will expire automatically after the configured TTL.
	Create(context.Context, *CreateNodeSessionRequest) (*CreateNodeSessionResponse, error)
	// Get returns the node-session matching the given DevEUI.
	Get(context.Context, *GetNodeSessionRequest) (*GetNodeSessionResponse, error)
	// Update updates the given node-session.
	Update(context.Context, *UpdateNodeSessionRequest) (*UpdateNodeSessionResponse, error)
	// Delete deletes the node-session matching the given DevEUI.
	Delete(context.Context, *DeleteNodeSessionRequest) (*DeleteNodeSessionResponse, error)
	// GetRandomDevAddr returns a random DevAddr taking the NwkID prefix into account.
	GetRandomDevAddr(context.Context, *GetRandomDevAddrRequest) (*GetRandomDevAddrResponse, error)
}

func RegisterNodeSessionServer(s *grpc.Server, srv NodeSessionServer) {
	s.RegisterService(&_NodeSession_serviceDesc, srv)
}

func _NodeSession_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeSessionServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NodeSession/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeSessionServer).Create(ctx, req.(*CreateNodeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeSession_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeSessionServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NodeSession/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeSessionServer).Get(ctx, req.(*GetNodeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeSession_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeSessionServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NodeSession/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeSessionServer).Update(ctx, req.(*UpdateNodeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeSession_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeSessionServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NodeSession/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeSessionServer).Delete(ctx, req.(*DeleteNodeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeSession_GetRandomDevAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomDevAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeSessionServer).GetRandomDevAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NodeSession/GetRandomDevAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeSessionServer).GetRandomDevAddr(ctx, req.(*GetRandomDevAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeSession_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.NodeSession",
	HandlerType: (*NodeSessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NodeSession_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _NodeSession_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _NodeSession_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _NodeSession_Delete_Handler,
		},
		{
			MethodName: "GetRandomDevAddr",
			Handler:    _NodeSession_GetRandomDevAddr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodeSession.proto",
}

func init() { proto.RegisterFile("nodeSession.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xec, 0x56, 0xcf, 0x4f, 0x13, 0x41,
	0x14, 0xce, 0x52, 0x28, 0xe5, 0xf1, 0x7b, 0xa2, 0x38, 0x2c, 0x60, 0x36, 0x3d, 0x55, 0x0e, 0x6d,
	0x44, 0x4f, 0xc4, 0xc4, 0x68, 0x0b, 0x84, 0xa0, 0x68, 0x16, 0x89, 0x1a, 0xbd, 0x0c, 0xec, 0xd0,
	0x6c, 0xdc, 0xce, 0x8c, 0x33, 0x23, 0x2d, 0x21, 0x5c, 0xf0, 0x68, 0xe2, 0xc5, 0xab, 0xff, 0x95,
	0x7f, 0x81, 0xd1, 0x3f, 0xc4, 0xec, 0xcc, 0x94, 0xd6, 0xba, 0xab, 0xc6, 0x7a, 0x30, 0x86, 0x5b,
	0xbf, 0xf9, 0xb6, 0xdf, 0xfb, 0xf6, 0xbd, 0x2f, 0x6f, 0x16, 0xe6, 0x19, 0x8f, 0xe8, 0x1e, 0x55,
	0x2a, 0xe6, 0xac, 0x2a, 0x24, 0xd7, 0x1c, 0x15, 0x88, 0x88, 0xfd, 0xe5, 0x26, 0xe7, 0xcd, 0x84,
	0xd6, 0x88, 0x88, 0x6b, 0x84, 0x31, 0xae, 0x89, 0x8e, 0x39, 0x53, 0xf6, 0x11, 0x7f, 0xea, 0x90,
	0xb7, 0x5a, 0xdd, 0x3f, 0x94, 0xbf, 0x14, 0x00, 0xd7, 0x25, 0x25, 0x9a, 0xee, 0xf6, 0xc4, 0x42,
	0xfa, 0xfa, 0x0d, 0x55, 0x1a, 0x61, 0x18, 0x8f, 0xe8, 0xf1, 0xbd, 0x28, 0x92, 0xd8, 0x0b, 0xbc,
	0xca, 0x44, 0xd8, 0x85, 0xa8, 0x02, 0xb3, 0x44, 0x88, 0x24, 0x3e, 0x34, 0xd2, 0xbb, 0xa4, 0x45,
	0xf1, 0x88, 0x79, 0x62, 0xf0, 0x18, 0x2d, 0x40, 0x31, 0xa2, 0xc7, 0x1b, 0xfb, 0xdb, 0xb8, 0x60,
	0x1e, 0x70, 0x28, 0xd5, 0x26, 0x42, 0xec, 0xed, 0xd0, 0x13, 0x3c, 0x6a, 0xb5, 0x1d, 0x4c, 0x19,
	0xd6, 0x7e, 0x65, 0x98, 0x31, 0xcb, 0x38, 0x98, 0x6a, 0x1d, 0xd5, 0x99, 0xde, 0x17, 0xb8, 0x18,
	0x78, 0x95, 0xe9, 0xd0, 0x21, 0xe4, 0x43, 0x29, 0xfd, 0xd5, 0xe0, 0x6d, 0x86, 0xc7, 0x0d, 0x73,
	0x81, 0x53, 0x35, 0xd9, 0x69, 0xd0, 0x84, 0x9c, 0xe0, 0x92, 0xa1, 0xba, 0x10, 0x05, 0x30, 0x29,
	0x3b, 0x37, 0x1b, 0xe1, 0xa3, 0xa3, 0x23, 0x45, 0x35, 0x9e, 0x30, 0x6c, 0xff, 0x51, 0x5a, 0xef,
	0x70, 0xf3, 0x41, 0xac, 0x34, 0x86, 0xa0, 0x90, 0xd6, 0xb3, 0x08, 0xdd, 0x80, 0x92, 0xec, 0x3c,
	0x8d, 0x59, 0xc4, 0xdb, 0x78, 0x32, 0xf0, 0x2a, 0x33, 0x6b, 0xd3, 0x55, 0x22, 0xe2, 0x6a, 0xf8,
	0xcc, 0x1e, 0x86, 0x17, 0x34, 0xba, 0x02, 0x63, 0xb2, 0xb3, 0xd6, 0x08, 0xf1, 0x94, 0x91, 0xb7,
	0x00, 0x2d, 0xc3, 0x84, 0xa4, 0x09, 0xe9, 0x6c, 0xd6, 0x99, 0xc6, 0xd3, 0x81, 0x57, 0x29, 0x85,
	0xbd, 0x83, 0xd4, 0x18, 0x89, 0xe4, 0x36, 0xd3, 0x54, 0x1e, 0x93, 0x04, 0xcf, 0x58, 0x63, 0x7d,
	0x47, 0xa8, 0x0a, 0x28, 0x66, 0x4a, 0x93, 0x24, 0x31, 0x8d, 0x7e, 0x48, 0x64, 0x33, 0x66, 0x78,
	0x36, 0xf0, 0x2a, 0x5e, 0x98, 0xc1, 0x94, 0x97, 0x60, 0x31, 0x63, 0xc8, 0x4a, 0x70, 0xa6, 0x68,
	0xf9, 0x39, 0x5c, 0xdd, 0xa2, 0x3a, 0x63, 0xfc, 0xbd, 0xd1, 0x79, 0xdf, 0x8d, 0xee, 0xb7, 0x87,
	0x5f, 0x7e, 0x3b, 0x0a, 0x0b, 0x83, 0xda, 0xb6, 0xea, 0x4f, 0xb2, 0xb5, 0x00, 0x45, 0x22, 0x44,
	0x5a, 0xd6, 0xaa, 0x3a, 0x74, 0x99, 0xa4, 0x7f, 0x20, 0x49, 0xa6, 0xa5, 0x07, 0x4f, 0x24, 0x61,
	0x0a, 0xcf, 0xd9, 0x26, 0x38, 0x98, 0x32, 0xba, 0xf3, 0x98, 0xb7, 0xa9, 0xc4, 0xf3, 0x96, 0x71,
	0xd0, 0xec, 0x98, 0x7d, 0x11, 0x5d, 0xee, 0x98, 0xff, 0x7d, 0xc7, 0x64, 0x0c, 0xd9, 0xed, 0x98,
	0x97, 0x80, 0x1b, 0x34, 0xa1, 0x99, 0x09, 0x18, 0x7e, 0xcd, 0x2c, 0xc1, 0x62, 0x86, 0xba, 0x2b,
	0xfd, 0x02, 0xae, 0x6d, 0x51, 0x1d, 0x12, 0x16, 0xf1, 0x56, 0xc3, 0x46, 0xeb, 0xef, 0x55, 0xbe,
	0x0d, 0xf8, 0x47, 0xf1, 0x5f, 0x6d, 0xb8, 0xb5, 0xcf, 0x63, 0x30, 0xd9, 0x67, 0x15, 0xbd, 0xf7,
	0xa0, 0x68, 0xf7, 0x33, 0x5a, 0x31, 0x43, 0xce, 0xbb, 0x91, 0xfd, 0xeb, 0x79, 0xb4, 0x7b, 0xd9,
	0x8d, 0xf3, 0x4f, 0x5f, 0x3f, 0x8c, 0xdc, 0x2d, 0xaf, 0xdb, 0xcb, 0xbf, 0xe7, 0x56, 0xd5, 0x4e,
	0x07, 0xbc, 0x9f, 0xd5, 0xd2, 0xcf, 0x07, 0x55, 0x3b, 0xb5, 0x2f, 0x7d, 0x56, 0x53, 0x56, 0x6b,
	0xdd, 0x5b, 0x45, 0xe7, 0x1e, 0x14, 0xb6, 0xa8, 0x46, 0xbe, 0x29, 0x97, 0x79, 0x3b, 0xf8, 0x4b,
	0x99, 0x9c, 0xf3, 0x71, 0xdf, 0xf8, 0xb8, 0x83, 0x86, 0xf0, 0x61, 0xba, 0x62, 0x13, 0xe5, 0xba,
	0x92, 0xb7, 0x43, 0x5c, 0x57, 0xf2, 0xd3, 0xe7, 0xba, 0xe2, 0x0f, 0xd9, 0x95, 0x77, 0x1e, 0x14,
	0x6d, 0xce, 0x9c, 0xa1, 0xbc, 0x48, 0x3b, 0x43, 0xf9, 0x99, 0x74, 0xed, 0x59, 0x1d, 0xa6, 0x3d,
	0x1f, 0x3d, 0x98, 0x1b, 0xcc, 0x1e, 0x5a, 0xee, 0x0e, 0x25, 0x2b, 0xef, 0xfe, 0x4a, 0x0e, 0xeb,
	0x5c, 0xed, 0x18, 0x57, 0x1b, 0xe5, 0xfa, 0x1f, 0xb8, 0x6a, 0x0e, 0x88, 0x1e, 0x14, 0xcd, 0xf7,
	0xe5, 0xad, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0xe8, 0x46, 0x31, 0xa5, 0x0a, 0x00, 0x00,
}
