// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	node.proto
	application.proto
	downlinkQueue.proto
	common.proto
	user.proto
	gateway.proto
	organization.proto
	profiles.proto
	networkServer.proto
	serviceProfile.proto
	deviceProfile.proto

It has these top-level messages:
	DeviceKeys
	CreateDeviceRequest
	CreateDeviceResponse
	GetDeviceRequest
	GetDeviceResponse
	DeleteDeviceRequest
	DeleteDeviceResponse
	ListDeviceByApplicationIDRequest
	DeviceListItem
	ListDeviceResponse
	UpdateDeviceRequest
	UpdateDeviceResponse
	CreateDeviceKeysRequest
	CreateDeviceKeysResponse
	GetDeviceKeysRequest
	GetDeviceKeysResponse
	UpdateDeviceKeysRequest
	UpdateDeviceKeysResponse
	DeleteDeviceKeysRequest
	DeleteDeviceKeysResponse
	ActivateDeviceRequest
	ActivateDeviceResponse
	GetDeviceActivationRequest
	GetDeviceActivationResponse
	GetRandomDevAddrRequest
	GetRandomDevAddrResponse
	GetFrameLogsRequest
	GetFrameLogsResponse
	FrameLog
	DataRate
	RXInfo
	TXInfo
	CreateApplicationRequest
	CreateApplicationResponse
	GetApplicationRequest
	GetApplicationResponse
	UpdateApplicationRequest
	UpdateApplicationResponse
	DeleteApplicationRequest
	DeleteApplicationResponse
	ListApplicationRequest
	ListApplicationResponse
	EmptyResponse
	HTTPIntegrationHeader
	HTTPIntegration
	GetHTTPIntegrationRequest
	DeleteIntegrationRequest
	ListIntegrationRequest
	ListIntegrationResponse
	EnqueueDownlinkQueueItemRequest
	EnqueueDownlinkQueueItemResponse
	DeleteDownlinkQeueueItemRequest
	DeleteDownlinkQueueItemResponse
	DownlinkQueueItem
	ListDownlinkQueueItemsRequest
	ListDownlinkQueueItemsResponse
	OrganizationLink
	ProfileRequest
	ProfileResponse
	ProfileSettings
	LoginRequest
	LoginResponse
	ListUserRequest
	UserRequest
	AddUserResponse
	UserSettings
	GetUserResponse
	AddUserRequest
	AddUserOrganization
	UpdateUserRequest
	ListUserResponse
	UserEmptyResponse
	UpdateUserPasswordRequest
	BrandingRequest
	BrandingResponse
	CreateGatewayRequest
	CreateGatewayResponse
	GetGatewayRequest
	GetGatewayResponse
	DeleteGatewayRequest
	GenerateGatewayTokenRequest
	GenerateGatewayTokenResponse
	DeleteGatewayResponse
	ListGatewayRequest
	ListGatewayItem
	ListGatewayResponse
	UpdateGatewayRequest
	UpdateGatewayResponse
	GatewayStats
	GetGatewayStatsRequest
	GetGatewayStatsResponse
	CreateChannelConfigurationRequest
	CreateChannelConfigurationResponse
	GetChannelConfigurationRequest
	GetChannelConfigurationResponse
	UpdateChannelConfigurationRequest
	UpdateChannelConfigurationResponse
	DeleteChannelConfigurationRequest
	DeleteChannelConfigurationResponse
	ListChannelConfigurationsRequest
	ListChannelConfigurationsResponse
	CreateExtraChannelRequest
	CreateExtraChannelResponse
	UpdateExtraChannelRequest
	UpdateExtraChannelResponse
	DeleteExtraChannelRequest
	DeleteExtraChannelResponse
	GetExtraChannelResponse
	GetExtraChannelsForChannelConfigurationIDRequest
	GetExtraChannelsForChannelConfigurationIDResponse
	PingRX
	GetLastPingRequest
	GetLastPingResponse
	ListOrganizationRequest
	OrganizationRequest
	GetOrganizationResponse
	CreateOrganizationRequest
	CreateOrganizationResponse
	UpdateOrganizationRequest
	ListOrganizationResponse
	OrganizationEmptyResponse
	OrganizationUserRequest
	DeleteOrganizationUserRequest
	ListOrganizationUsersRequest
	GetOrganizationUserRequest
	GetOrganizationUserResponse
	ListOrganizationUsersResponse
	ServiceProfile
	DeviceProfile
	CreateNetworkServerRequest
	CreateNetworkServerResponse
	GetNetworkServerRequest
	GetNetworkServerResponse
	UpdateNetworkServerRequest
	UpdateNetworkServerResponse
	DeleteNetworkServerRequest
	DeleteNetworkServerResponse
	ListNetworkServerRequest
	ListNetworkServerResponse
	CreateServiceProfileRequest
	CreateServiceProfileResponse
	GetServiceProfileRequest
	GetServiceProfileResponse
	UpdateServiceProfileRequest
	UpdateServiceProfileResponse
	DeleteServiceProfileRequest
	DeleteServiceProfileResponse
	ListServiceProfileRequest
	ServiceProfileMeta
	ListServiceProfileResponse
	CreateDeviceProfileRequest
	CreateDeviceProfileResponse
	GetDeviceProfileRequest
	GetDeviceProfileResponse
	UpdateDeviceProfileRequest
	UpdateDeviceProfileResponse
	DeleteDeviceProfileRequest
	DeleteDeviceProfileResponse
	ListDeviceProfileRequest
	DeviceProfileMeta
	ListDeviceProfileResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceKeys struct {
	// HEX encoded application key.
	AppKey string `protobuf:"bytes,1,opt,name=appKey" json:"appKey,omitempty"`
}

func (m *DeviceKeys) Reset()                    { *m = DeviceKeys{} }
func (m *DeviceKeys) String() string            { return proto.CompactTextString(m) }
func (*DeviceKeys) ProtoMessage()               {}
func (*DeviceKeys) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeviceKeys) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

type CreateDeviceRequest struct {
	// Hex encoded DevEUI.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Name of the device (if left blank, it will be set to the DevEUI).
	Name string `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	// ID of the application to which the device must be added.
	ApplicationID int64 `protobuf:"varint,13,opt,name=applicationID" json:"applicationID,omitempty"`
	// Description of the device.
	Description string `protobuf:"bytes,14,opt,name=description" json:"description,omitempty"`
	// DeviceProfileID attached to the device.
	DeviceProfileID string `protobuf:"bytes,18,opt,name=deviceProfileID" json:"deviceProfileID,omitempty"`
}

func (m *CreateDeviceRequest) Reset()                    { *m = CreateDeviceRequest{} }
func (m *CreateDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceRequest) ProtoMessage()               {}
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateDeviceRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *CreateDeviceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateDeviceRequest) GetApplicationID() int64 {
	if m != nil {
		return m.ApplicationID
	}
	return 0
}

func (m *CreateDeviceRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateDeviceRequest) GetDeviceProfileID() string {
	if m != nil {
		return m.DeviceProfileID
	}
	return ""
}

type CreateDeviceResponse struct {
}

func (m *CreateDeviceResponse) Reset()                    { *m = CreateDeviceResponse{} }
func (m *CreateDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceResponse) ProtoMessage()               {}
func (*CreateDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetDeviceRequest struct {
	// Hex encoded DevEUI of the device.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *GetDeviceRequest) Reset()                    { *m = GetDeviceRequest{} }
func (m *GetDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeviceRequest) ProtoMessage()               {}
func (*GetDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetDeviceRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

type GetDeviceResponse struct {
	// Hex encoded DevEUI.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Name of the device (if left blank, it will be set to the DevEUI).
	Name string `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	// ID of the application to which the device must be added.
	ApplicationID int64 `protobuf:"varint,13,opt,name=applicationID" json:"applicationID,omitempty"`
	// Description of the device.
	Description string `protobuf:"bytes,14,opt,name=description" json:"description,omitempty"`
	// DeviceProfileID attached to the device.
	DeviceProfileID string `protobuf:"bytes,18,opt,name=deviceProfileID" json:"deviceProfileID,omitempty"`
}

func (m *GetDeviceResponse) Reset()                    { *m = GetDeviceResponse{} }
func (m *GetDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDeviceResponse) ProtoMessage()               {}
func (*GetDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetDeviceResponse) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *GetDeviceResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetDeviceResponse) GetApplicationID() int64 {
	if m != nil {
		return m.ApplicationID
	}
	return 0
}

func (m *GetDeviceResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetDeviceResponse) GetDeviceProfileID() string {
	if m != nil {
		return m.DeviceProfileID
	}
	return ""
}

type DeleteDeviceRequest struct {
	// Hex encoded DevEUI of the device.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *DeleteDeviceRequest) Reset()                    { *m = DeleteDeviceRequest{} }
func (m *DeleteDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDeviceRequest) ProtoMessage()               {}
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteDeviceRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

type DeleteDeviceResponse struct {
}

func (m *DeleteDeviceResponse) Reset()                    { *m = DeleteDeviceResponse{} }
func (m *DeleteDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDeviceResponse) ProtoMessage()               {}
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ListDeviceByApplicationIDRequest struct {
	// ID of the application for which to list the devices.
	ApplicationID int64 `protobuf:"varint,3,opt,name=applicationID" json:"applicationID,omitempty"`
	// Max number of devices to return in the result-set.
	Limit int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	// Offset of the result-set (for pagination).
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	// Search against name or DevEUI
	Search string `protobuf:"bytes,4,opt,name=search" json:"search,omitempty"`
}

func (m *ListDeviceByApplicationIDRequest) Reset()         { *m = ListDeviceByApplicationIDRequest{} }
func (m *ListDeviceByApplicationIDRequest) String() string { return proto.CompactTextString(m) }
func (*ListDeviceByApplicationIDRequest) ProtoMessage()    {}
func (*ListDeviceByApplicationIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7}
}

func (m *ListDeviceByApplicationIDRequest) GetApplicationID() int64 {
	if m != nil {
		return m.ApplicationID
	}
	return 0
}

func (m *ListDeviceByApplicationIDRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListDeviceByApplicationIDRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListDeviceByApplicationIDRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type DeviceListItem struct {
	// Hex encoded DevEUI.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Name of the device (if left blank, it will be set to the DevEUI).
	Name string `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	// ID of the application to which the device must be added.
	ApplicationID int64 `protobuf:"varint,13,opt,name=applicationID" json:"applicationID,omitempty"`
	// Description of the device.
	Description string `protobuf:"bytes,14,opt,name=description" json:"description,omitempty"`
	// DeviceProfileID attached to the device.
	DeviceProfileID string `protobuf:"bytes,18,opt,name=deviceProfileID" json:"deviceProfileID,omitempty"`
	// Device-profile name.
	DeviceProfileName string `protobuf:"bytes,19,opt,name=deviceProfileName" json:"deviceProfileName,omitempty"`
}

func (m *DeviceListItem) Reset()                    { *m = DeviceListItem{} }
func (m *DeviceListItem) String() string            { return proto.CompactTextString(m) }
func (*DeviceListItem) ProtoMessage()               {}
func (*DeviceListItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeviceListItem) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *DeviceListItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceListItem) GetApplicationID() int64 {
	if m != nil {
		return m.ApplicationID
	}
	return 0
}

func (m *DeviceListItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DeviceListItem) GetDeviceProfileID() string {
	if m != nil {
		return m.DeviceProfileID
	}
	return ""
}

func (m *DeviceListItem) GetDeviceProfileName() string {
	if m != nil {
		return m.DeviceProfileName
	}
	return ""
}

type ListDeviceResponse struct {
	// Total number of devices available within the result-set.
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	// Devices within this result-set.
	Result []*DeviceListItem `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListDeviceResponse) Reset()                    { *m = ListDeviceResponse{} }
func (m *ListDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDeviceResponse) ProtoMessage()               {}
func (*ListDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ListDeviceResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListDeviceResponse) GetResult() []*DeviceListItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateDeviceRequest struct {
	// Hex encoded DevEUI.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Name of the device (if left blank, it will be set to the DevEUI).
	Name string `protobuf:"bytes,9,opt,name=name" json:"name,omitempty"`
	// ID of the application to which the device must be added.
	ApplicationID int64 `protobuf:"varint,13,opt,name=applicationID" json:"applicationID,omitempty"`
	// Description of the device.
	Description string `protobuf:"bytes,14,opt,name=description" json:"description,omitempty"`
	// DeviceProfileID attached to the device.
	DeviceProfileID string `protobuf:"bytes,18,opt,name=deviceProfileID" json:"deviceProfileID,omitempty"`
}

func (m *UpdateDeviceRequest) Reset()                    { *m = UpdateDeviceRequest{} }
func (m *UpdateDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateDeviceRequest) ProtoMessage()               {}
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpdateDeviceRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *UpdateDeviceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateDeviceRequest) GetApplicationID() int64 {
	if m != nil {
		return m.ApplicationID
	}
	return 0
}

func (m *UpdateDeviceRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateDeviceRequest) GetDeviceProfileID() string {
	if m != nil {
		return m.DeviceProfileID
	}
	return ""
}

type UpdateDeviceResponse struct {
}

func (m *UpdateDeviceResponse) Reset()                    { *m = UpdateDeviceResponse{} }
func (m *UpdateDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateDeviceResponse) ProtoMessage()               {}
func (*UpdateDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type CreateDeviceKeysRequest struct {
	// Hex encoded DevEUI of the device.
	DevEUI     string      `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	DeviceKeys *DeviceKeys `protobuf:"bytes,2,opt,name=deviceKeys" json:"deviceKeys,omitempty"`
}

func (m *CreateDeviceKeysRequest) Reset()                    { *m = CreateDeviceKeysRequest{} }
func (m *CreateDeviceKeysRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceKeysRequest) ProtoMessage()               {}
func (*CreateDeviceKeysRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CreateDeviceKeysRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *CreateDeviceKeysRequest) GetDeviceKeys() *DeviceKeys {
	if m != nil {
		return m.DeviceKeys
	}
	return nil
}

type CreateDeviceKeysResponse struct {
}

func (m *CreateDeviceKeysResponse) Reset()                    { *m = CreateDeviceKeysResponse{} }
func (m *CreateDeviceKeysResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceKeysResponse) ProtoMessage()               {}
func (*CreateDeviceKeysResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type GetDeviceKeysRequest struct {
	// Hex encoded DevEUI of the device.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *GetDeviceKeysRequest) Reset()                    { *m = GetDeviceKeysRequest{} }
func (m *GetDeviceKeysRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeviceKeysRequest) ProtoMessage()               {}
func (*GetDeviceKeysRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetDeviceKeysRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

type GetDeviceKeysResponse struct {
	DeviceKeys *DeviceKeys `protobuf:"bytes,1,opt,name=deviceKeys" json:"deviceKeys,omitempty"`
}

func (m *GetDeviceKeysResponse) Reset()                    { *m = GetDeviceKeysResponse{} }
func (m *GetDeviceKeysResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDeviceKeysResponse) ProtoMessage()               {}
func (*GetDeviceKeysResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetDeviceKeysResponse) GetDeviceKeys() *DeviceKeys {
	if m != nil {
		return m.DeviceKeys
	}
	return nil
}

type UpdateDeviceKeysRequest struct {
	// Hex encoded DevEUI of the device.
	DevEUI     string      `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	DeviceKeys *DeviceKeys `protobuf:"bytes,2,opt,name=deviceKeys" json:"deviceKeys,omitempty"`
}

func (m *UpdateDeviceKeysRequest) Reset()                    { *m = UpdateDeviceKeysRequest{} }
func (m *UpdateDeviceKeysRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateDeviceKeysRequest) ProtoMessage()               {}
func (*UpdateDeviceKeysRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *UpdateDeviceKeysRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *UpdateDeviceKeysRequest) GetDeviceKeys() *DeviceKeys {
	if m != nil {
		return m.DeviceKeys
	}
	return nil
}

type UpdateDeviceKeysResponse struct {
}

func (m *UpdateDeviceKeysResponse) Reset()                    { *m = UpdateDeviceKeysResponse{} }
func (m *UpdateDeviceKeysResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateDeviceKeysResponse) ProtoMessage()               {}
func (*UpdateDeviceKeysResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type DeleteDeviceKeysRequest struct {
	// Hex encoded DevEUI of the device.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *DeleteDeviceKeysRequest) Reset()                    { *m = DeleteDeviceKeysRequest{} }
func (m *DeleteDeviceKeysRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDeviceKeysRequest) ProtoMessage()               {}
func (*DeleteDeviceKeysRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DeleteDeviceKeysRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

type DeleteDeviceKeysResponse struct {
}

func (m *DeleteDeviceKeysResponse) Reset()                    { *m = DeleteDeviceKeysResponse{} }
func (m *DeleteDeviceKeysResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDeviceKeysResponse) ProtoMessage()               {}
func (*DeleteDeviceKeysResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type ActivateDeviceRequest struct {
	// Hex encoded DevEUI of the device to activate.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Hex encoded DevAddr.
	DevAddr string `protobuf:"bytes,2,opt,name=devAddr" json:"devAddr,omitempty"`
	// Hex encoded AppSKey.
	AppSKey string `protobuf:"bytes,3,opt,name=appSKey" json:"appSKey,omitempty"`
	// Hex encoded NwkSKey.
	NwkSKey string `protobuf:"bytes,4,opt,name=nwkSKey" json:"nwkSKey,omitempty"`
	// Uplink frame-counter.
	FCntUp uint32 `protobuf:"varint,5,opt,name=fCntUp" json:"fCntUp,omitempty"`
	// Downlink frame-counter.
	FCntDown uint32 `protobuf:"varint,6,opt,name=fCntDown" json:"fCntDown,omitempty"`
	// Skip frame-counter checks (this is insecure, but could be helpful for debugging).
	SkipFCntCheck bool `protobuf:"varint,7,opt,name=skipFCntCheck" json:"skipFCntCheck,omitempty"`
}

func (m *ActivateDeviceRequest) Reset()                    { *m = ActivateDeviceRequest{} }
func (m *ActivateDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*ActivateDeviceRequest) ProtoMessage()               {}
func (*ActivateDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ActivateDeviceRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *ActivateDeviceRequest) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func (m *ActivateDeviceRequest) GetAppSKey() string {
	if m != nil {
		return m.AppSKey
	}
	return ""
}

func (m *ActivateDeviceRequest) GetNwkSKey() string {
	if m != nil {
		return m.NwkSKey
	}
	return ""
}

func (m *ActivateDeviceRequest) GetFCntUp() uint32 {
	if m != nil {
		return m.FCntUp
	}
	return 0
}

func (m *ActivateDeviceRequest) GetFCntDown() uint32 {
	if m != nil {
		return m.FCntDown
	}
	return 0
}

func (m *ActivateDeviceRequest) GetSkipFCntCheck() bool {
	if m != nil {
		return m.SkipFCntCheck
	}
	return false
}

type ActivateDeviceResponse struct {
}

func (m *ActivateDeviceResponse) Reset()                    { *m = ActivateDeviceResponse{} }
func (m *ActivateDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*ActivateDeviceResponse) ProtoMessage()               {}
func (*ActivateDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type GetDeviceActivationRequest struct {
	// Hex encoded DevEUI of the device.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *GetDeviceActivationRequest) Reset()                    { *m = GetDeviceActivationRequest{} }
func (m *GetDeviceActivationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeviceActivationRequest) ProtoMessage()               {}
func (*GetDeviceActivationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GetDeviceActivationRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

type GetDeviceActivationResponse struct {
	// Hex encoded DevAddr.
	DevAddr string `protobuf:"bytes,1,opt,name=devAddr" json:"devAddr,omitempty"`
	// Hex encoded AppSKey.
	AppSKey string `protobuf:"bytes,2,opt,name=appSKey" json:"appSKey,omitempty"`
	// Hex encoded NwkSKey.
	NwkSKey string `protobuf:"bytes,3,opt,name=nwkSKey" json:"nwkSKey,omitempty"`
	// Uplink frame-counter.
	FCntUp uint32 `protobuf:"varint,4,opt,name=fCntUp" json:"fCntUp,omitempty"`
	// Downlink frame-counter.
	FCntDown uint32 `protobuf:"varint,5,opt,name=fCntDown" json:"fCntDown,omitempty"`
	// Skip frame-counter checks (this is insecure, but could be helpful for debugging).
	SkipFCntCheck bool `protobuf:"varint,6,opt,name=skipFCntCheck" json:"skipFCntCheck,omitempty"`
}

func (m *GetDeviceActivationResponse) Reset()                    { *m = GetDeviceActivationResponse{} }
func (m *GetDeviceActivationResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDeviceActivationResponse) ProtoMessage()               {}
func (*GetDeviceActivationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *GetDeviceActivationResponse) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func (m *GetDeviceActivationResponse) GetAppSKey() string {
	if m != nil {
		return m.AppSKey
	}
	return ""
}

func (m *GetDeviceActivationResponse) GetNwkSKey() string {
	if m != nil {
		return m.NwkSKey
	}
	return ""
}

func (m *GetDeviceActivationResponse) GetFCntUp() uint32 {
	if m != nil {
		return m.FCntUp
	}
	return 0
}

func (m *GetDeviceActivationResponse) GetFCntDown() uint32 {
	if m != nil {
		return m.FCntDown
	}
	return 0
}

func (m *GetDeviceActivationResponse) GetSkipFCntCheck() bool {
	if m != nil {
		return m.SkipFCntCheck
	}
	return false
}

type GetRandomDevAddrRequest struct {
	// Hex encoded DevEUI of the device to activate.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *GetRandomDevAddrRequest) Reset()                    { *m = GetRandomDevAddrRequest{} }
func (m *GetRandomDevAddrRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRandomDevAddrRequest) ProtoMessage()               {}
func (*GetRandomDevAddrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GetRandomDevAddrRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

type GetRandomDevAddrResponse struct {
	// Hex encoded DevAddr.
	DevAddr string `protobuf:"bytes,1,opt,name=devAddr" json:"devAddr,omitempty"`
}

func (m *GetRandomDevAddrResponse) Reset()                    { *m = GetRandomDevAddrResponse{} }
func (m *GetRandomDevAddrResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRandomDevAddrResponse) ProtoMessage()               {}
func (*GetRandomDevAddrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GetRandomDevAddrResponse) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

type GetFrameLogsRequest struct {
	// Hex encoded DevEUI.
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// Max number of frames to return in the result-set.
	Limit int64 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	// Offset of the result-set (for pagination).
	Offset int64 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *GetFrameLogsRequest) Reset()                    { *m = GetFrameLogsRequest{} }
func (m *GetFrameLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFrameLogsRequest) ProtoMessage()               {}
func (*GetFrameLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *GetFrameLogsRequest) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *GetFrameLogsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetFrameLogsRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetFrameLogsResponse struct {
	// Total number of logs.
	TotalCount int32 `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	// The result-set.
	Result []*FrameLog `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *GetFrameLogsResponse) Reset()                    { *m = GetFrameLogsResponse{} }
func (m *GetFrameLogsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFrameLogsResponse) ProtoMessage()               {}
func (*GetFrameLogsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *GetFrameLogsResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *GetFrameLogsResponse) GetResult() []*FrameLog {
	if m != nil {
		return m.Result
	}
	return nil
}

type FrameLog struct {
	// Timestamp of when the frame was logged.
	CreatedAt string `protobuf:"bytes,1,opt,name=createdAt" json:"createdAt,omitempty"`
	// RX-info set (in case of an uplink).
	RxInfoSet []*RXInfo `protobuf:"bytes,2,rep,name=rxInfoSet" json:"rxInfoSet,omitempty"`
	// TX-info (in case of a downlink).
	TxInfo *TXInfo `protobuf:"bytes,3,opt,name=txInfo" json:"txInfo,omitempty"`
	// LoRaWAN PHYPayload as a JSON string.
	PhyPayloadJSON string `protobuf:"bytes,4,opt,name=phyPayloadJSON" json:"phyPayloadJSON,omitempty"`
}

func (m *FrameLog) Reset()                    { *m = FrameLog{} }
func (m *FrameLog) String() string            { return proto.CompactTextString(m) }
func (*FrameLog) ProtoMessage()               {}
func (*FrameLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *FrameLog) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *FrameLog) GetRxInfoSet() []*RXInfo {
	if m != nil {
		return m.RxInfoSet
	}
	return nil
}

func (m *FrameLog) GetTxInfo() *TXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *FrameLog) GetPhyPayloadJSON() string {
	if m != nil {
		return m.PhyPayloadJSON
	}
	return ""
}

type DataRate struct {
	Modulation   string `protobuf:"bytes,1,opt,name=modulation" json:"modulation,omitempty"`
	BandWidth    uint32 `protobuf:"varint,2,opt,name=bandWidth" json:"bandWidth,omitempty"`
	SpreadFactor uint32 `protobuf:"varint,3,opt,name=spreadFactor" json:"spreadFactor,omitempty"`
	Bitrate      uint32 `protobuf:"varint,4,opt,name=bitrate" json:"bitrate,omitempty"`
}

func (m *DataRate) Reset()                    { *m = DataRate{} }
func (m *DataRate) String() string            { return proto.CompactTextString(m) }
func (*DataRate) ProtoMessage()               {}
func (*DataRate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *DataRate) GetModulation() string {
	if m != nil {
		return m.Modulation
	}
	return ""
}

func (m *DataRate) GetBandWidth() uint32 {
	if m != nil {
		return m.BandWidth
	}
	return 0
}

func (m *DataRate) GetSpreadFactor() uint32 {
	if m != nil {
		return m.SpreadFactor
	}
	return 0
}

func (m *DataRate) GetBitrate() uint32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

type RXInfo struct {
	// Channel number on which the frame was received.
	Channel int32 `protobuf:"varint,1,opt,name=channel" json:"channel,omitempty"`
	// Code-rate.
	CodeRate string `protobuf:"bytes,2,opt,name=codeRate" json:"codeRate,omitempty"`
	// frequency.
	Frequency int64 `protobuf:"varint,3,opt,name=frequency" json:"frequency,omitempty"`
	// LoRa SNR.
	LoRaSNR float64 `protobuf:"fixed64,4,opt,name=loRaSNR" json:"loRaSNR,omitempty"`
	// RSSI / signal strength.
	Rssi int32 `protobuf:"varint,5,opt,name=rssi" json:"rssi,omitempty"`
	// Time (when the gateway has a GPS).
	Time string `protobuf:"bytes,6,opt,name=time" json:"time,omitempty"`
	// Gateway internal timestamp.
	Timestamp uint32 `protobuf:"varint,7,opt,name=timestamp" json:"timestamp,omitempty"`
	// Data-rate.
	DataRate *DataRate `protobuf:"bytes,8,opt,name=dataRate" json:"dataRate,omitempty"`
	// HEX encoded gateway MAC.
	Mac string `protobuf:"bytes,9,opt,name=mac" json:"mac,omitempty"`
}

func (m *RXInfo) Reset()                    { *m = RXInfo{} }
func (m *RXInfo) String() string            { return proto.CompactTextString(m) }
func (*RXInfo) ProtoMessage()               {}
func (*RXInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *RXInfo) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *RXInfo) GetCodeRate() string {
	if m != nil {
		return m.CodeRate
	}
	return ""
}

func (m *RXInfo) GetFrequency() int64 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *RXInfo) GetLoRaSNR() float64 {
	if m != nil {
		return m.LoRaSNR
	}
	return 0
}

func (m *RXInfo) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *RXInfo) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *RXInfo) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RXInfo) GetDataRate() *DataRate {
	if m != nil {
		return m.DataRate
	}
	return nil
}

func (m *RXInfo) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type TXInfo struct {
	// Code-rate.
	CodeRate string `protobuf:"bytes,1,opt,name=codeRate" json:"codeRate,omitempty"`
	// Frequency.
	Frequency int64 `protobuf:"varint,2,opt,name=frequency" json:"frequency,omitempty"`
	// Immediately.
	Immediately bool `protobuf:"varint,3,opt,name=immediately" json:"immediately,omitempty"`
	// HEX encoded gateway MAC.
	Mac string `protobuf:"bytes,4,opt,name=mac" json:"mac,omitempty"`
	// TX power.
	Power int32 `protobuf:"varint,5,opt,name=power" json:"power,omitempty"`
	// Gateway internal timestamp.
	Timestamp uint32 `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	// Data-rate.
	DataRate *DataRate `protobuf:"bytes,7,opt,name=dataRate" json:"dataRate,omitempty"`
}

func (m *TXInfo) Reset()                    { *m = TXInfo{} }
func (m *TXInfo) String() string            { return proto.CompactTextString(m) }
func (*TXInfo) ProtoMessage()               {}
func (*TXInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *TXInfo) GetCodeRate() string {
	if m != nil {
		return m.CodeRate
	}
	return ""
}

func (m *TXInfo) GetFrequency() int64 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *TXInfo) GetImmediately() bool {
	if m != nil {
		return m.Immediately
	}
	return false
}

func (m *TXInfo) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *TXInfo) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *TXInfo) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TXInfo) GetDataRate() *DataRate {
	if m != nil {
		return m.DataRate
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceKeys)(nil), "api.DeviceKeys")
	proto.RegisterType((*CreateDeviceRequest)(nil), "api.CreateDeviceRequest")
	proto.RegisterType((*CreateDeviceResponse)(nil), "api.CreateDeviceResponse")
	proto.RegisterType((*GetDeviceRequest)(nil), "api.GetDeviceRequest")
	proto.RegisterType((*GetDeviceResponse)(nil), "api.GetDeviceResponse")
	proto.RegisterType((*DeleteDeviceRequest)(nil), "api.DeleteDeviceRequest")
	proto.RegisterType((*DeleteDeviceResponse)(nil), "api.DeleteDeviceResponse")
	proto.RegisterType((*ListDeviceByApplicationIDRequest)(nil), "api.ListDeviceByApplicationIDRequest")
	proto.RegisterType((*DeviceListItem)(nil), "api.DeviceListItem")
	proto.RegisterType((*ListDeviceResponse)(nil), "api.ListDeviceResponse")
	proto.RegisterType((*UpdateDeviceRequest)(nil), "api.UpdateDeviceRequest")
	proto.RegisterType((*UpdateDeviceResponse)(nil), "api.UpdateDeviceResponse")
	proto.RegisterType((*CreateDeviceKeysRequest)(nil), "api.CreateDeviceKeysRequest")
	proto.RegisterType((*CreateDeviceKeysResponse)(nil), "api.CreateDeviceKeysResponse")
	proto.RegisterType((*GetDeviceKeysRequest)(nil), "api.GetDeviceKeysRequest")
	proto.RegisterType((*GetDeviceKeysResponse)(nil), "api.GetDeviceKeysResponse")
	proto.RegisterType((*UpdateDeviceKeysRequest)(nil), "api.UpdateDeviceKeysRequest")
	proto.RegisterType((*UpdateDeviceKeysResponse)(nil), "api.UpdateDeviceKeysResponse")
	proto.RegisterType((*DeleteDeviceKeysRequest)(nil), "api.DeleteDeviceKeysRequest")
	proto.RegisterType((*DeleteDeviceKeysResponse)(nil), "api.DeleteDeviceKeysResponse")
	proto.RegisterType((*ActivateDeviceRequest)(nil), "api.ActivateDeviceRequest")
	proto.RegisterType((*ActivateDeviceResponse)(nil), "api.ActivateDeviceResponse")
	proto.RegisterType((*GetDeviceActivationRequest)(nil), "api.GetDeviceActivationRequest")
	proto.RegisterType((*GetDeviceActivationResponse)(nil), "api.GetDeviceActivationResponse")
	proto.RegisterType((*GetRandomDevAddrRequest)(nil), "api.GetRandomDevAddrRequest")
	proto.RegisterType((*GetRandomDevAddrResponse)(nil), "api.GetRandomDevAddrResponse")
	proto.RegisterType((*GetFrameLogsRequest)(nil), "api.GetFrameLogsRequest")
	proto.RegisterType((*GetFrameLogsResponse)(nil), "api.GetFrameLogsResponse")
	proto.RegisterType((*FrameLog)(nil), "api.FrameLog")
	proto.RegisterType((*DataRate)(nil), "api.DataRate")
	proto.RegisterType((*RXInfo)(nil), "api.RXInfo")
	proto.RegisterType((*TXInfo)(nil), "api.TXInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Device service

type DeviceClient interface {
	// Create creates the given device.
	Create(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error)
	// Get returns the device matching the given DevEUI.
	Get(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	// Delete deletes the device matching the given DevEUI.
	Delete(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error)
	// ListByApplicationID lists the devices by the given application ID, sorted by the name of the device.
	ListByApplicationID(ctx context.Context, in *ListDeviceByApplicationIDRequest, opts ...grpc.CallOption) (*ListDeviceResponse, error)
	// Update updates the device matching the given DevEUI.
	Update(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*UpdateDeviceResponse, error)
	// CreateKeys creates the given device-keys.
	CreateKeys(ctx context.Context, in *CreateDeviceKeysRequest, opts ...grpc.CallOption) (*CreateDeviceKeysResponse, error)
	// GetKeys returns the device-keys for the given DevEUI.
	GetKeys(ctx context.Context, in *GetDeviceKeysRequest, opts ...grpc.CallOption) (*GetDeviceKeysResponse, error)
	// UpdateKeys updates the device-keys.
	UpdateKeys(ctx context.Context, in *UpdateDeviceKeysRequest, opts ...grpc.CallOption) (*UpdateDeviceKeysResponse, error)
	// DeleteKeys deletes the device-keys for the given DevEUI.
	DeleteKeys(ctx context.Context, in *DeleteDeviceKeysRequest, opts ...grpc.CallOption) (*DeleteDeviceKeysResponse, error)
	// Activate (re)activates the device (only when ABP is set to true).
	Activate(ctx context.Context, in *ActivateDeviceRequest, opts ...grpc.CallOption) (*ActivateDeviceResponse, error)
	// GetActivation returns the current activation details of the device (OTAA and ABP).
	GetActivation(ctx context.Context, in *GetDeviceActivationRequest, opts ...grpc.CallOption) (*GetDeviceActivationResponse, error)
	// GetRandomDevAddr returns a random DevAddr taking the NwkID prefix into account.
	GetRandomDevAddr(ctx context.Context, in *GetRandomDevAddrRequest, opts ...grpc.CallOption) (*GetRandomDevAddrResponse, error)
	// GetFrameLogs returns the uplink / downlink frame log for the given DevEUI.
	GetFrameLogs(ctx context.Context, in *GetFrameLogsRequest, opts ...grpc.CallOption) (*GetFrameLogsResponse, error)
}

type deviceClient struct {
	cc *grpc.ClientConn
}

func NewDeviceClient(cc *grpc.ClientConn) DeviceClient {
	return &deviceClient{cc}
}

func (c *deviceClient) Create(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error) {
	out := new(CreateDeviceResponse)
	err := grpc.Invoke(ctx, "/api.Device/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) Get(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := grpc.Invoke(ctx, "/api.Device/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) Delete(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error) {
	out := new(DeleteDeviceResponse)
	err := grpc.Invoke(ctx, "/api.Device/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) ListByApplicationID(ctx context.Context, in *ListDeviceByApplicationIDRequest, opts ...grpc.CallOption) (*ListDeviceResponse, error) {
	out := new(ListDeviceResponse)
	err := grpc.Invoke(ctx, "/api.Device/ListByApplicationID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) Update(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*UpdateDeviceResponse, error) {
	out := new(UpdateDeviceResponse)
	err := grpc.Invoke(ctx, "/api.Device/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) CreateKeys(ctx context.Context, in *CreateDeviceKeysRequest, opts ...grpc.CallOption) (*CreateDeviceKeysResponse, error) {
	out := new(CreateDeviceKeysResponse)
	err := grpc.Invoke(ctx, "/api.Device/CreateKeys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetKeys(ctx context.Context, in *GetDeviceKeysRequest, opts ...grpc.CallOption) (*GetDeviceKeysResponse, error) {
	out := new(GetDeviceKeysResponse)
	err := grpc.Invoke(ctx, "/api.Device/GetKeys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) UpdateKeys(ctx context.Context, in *UpdateDeviceKeysRequest, opts ...grpc.CallOption) (*UpdateDeviceKeysResponse, error) {
	out := new(UpdateDeviceKeysResponse)
	err := grpc.Invoke(ctx, "/api.Device/UpdateKeys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) DeleteKeys(ctx context.Context, in *DeleteDeviceKeysRequest, opts ...grpc.CallOption) (*DeleteDeviceKeysResponse, error) {
	out := new(DeleteDeviceKeysResponse)
	err := grpc.Invoke(ctx, "/api.Device/DeleteKeys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) Activate(ctx context.Context, in *ActivateDeviceRequest, opts ...grpc.CallOption) (*ActivateDeviceResponse, error) {
	out := new(ActivateDeviceResponse)
	err := grpc.Invoke(ctx, "/api.Device/Activate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetActivation(ctx context.Context, in *GetDeviceActivationRequest, opts ...grpc.CallOption) (*GetDeviceActivationResponse, error) {
	out := new(GetDeviceActivationResponse)
	err := grpc.Invoke(ctx, "/api.Device/GetActivation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetRandomDevAddr(ctx context.Context, in *GetRandomDevAddrRequest, opts ...grpc.CallOption) (*GetRandomDevAddrResponse, error) {
	out := new(GetRandomDevAddrResponse)
	err := grpc.Invoke(ctx, "/api.Device/GetRandomDevAddr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetFrameLogs(ctx context.Context, in *GetFrameLogsRequest, opts ...grpc.CallOption) (*GetFrameLogsResponse, error) {
	out := new(GetFrameLogsResponse)
	err := grpc.Invoke(ctx, "/api.Device/GetFrameLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Device service

type DeviceServer interface {
	// Create creates the given device.
	Create(context.Context, *CreateDeviceRequest) (*CreateDeviceResponse, error)
	// Get returns the device matching the given DevEUI.
	Get(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	// Delete deletes the device matching the given DevEUI.
	Delete(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error)
	// ListByApplicationID lists the devices by the given application ID, sorted by the name of the device.
	ListByApplicationID(context.Context, *ListDeviceByApplicationIDRequest) (*ListDeviceResponse, error)
	// Update updates the device matching the given DevEUI.
	Update(context.Context, *UpdateDeviceRequest) (*UpdateDeviceResponse, error)
	// CreateKeys creates the given device-keys.
	CreateKeys(context.Context, *CreateDeviceKeysRequest) (*CreateDeviceKeysResponse, error)
	// GetKeys returns the device-keys for the given DevEUI.
	GetKeys(context.Context, *GetDeviceKeysRequest) (*GetDeviceKeysResponse, error)
	// UpdateKeys updates the device-keys.
	UpdateKeys(context.Context, *UpdateDeviceKeysRequest) (*UpdateDeviceKeysResponse, error)
	// DeleteKeys deletes the device-keys for the given DevEUI.
	DeleteKeys(context.Context, *DeleteDeviceKeysRequest) (*DeleteDeviceKeysResponse, error)
	// Activate (re)activates the device (only when ABP is set to true).
	Activate(context.Context, *ActivateDeviceRequest) (*ActivateDeviceResponse, error)
	// GetActivation returns the current activation details of the device (OTAA and ABP).
	GetActivation(context.Context, *GetDeviceActivationRequest) (*GetDeviceActivationResponse, error)
	// GetRandomDevAddr returns a random DevAddr taking the NwkID prefix into account.
	GetRandomDevAddr(context.Context, *GetRandomDevAddrRequest) (*GetRandomDevAddrResponse, error)
	// GetFrameLogs returns the uplink / downlink frame log for the given DevEUI.
	GetFrameLogs(context.Context, *GetFrameLogsRequest) (*GetFrameLogsResponse, error)
}

func RegisterDeviceServer(s *grpc.Server, srv DeviceServer) {
	s.RegisterService(&_Device_serviceDesc, srv)
}

func _Device_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Create(ctx, req.(*CreateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Get(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Delete(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_ListByApplicationID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceByApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).ListByApplicationID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/ListByApplicationID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).ListByApplicationID(ctx, req.(*ListDeviceByApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Update(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_CreateKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).CreateKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/CreateKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).CreateKeys(ctx, req.(*CreateDeviceKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/GetKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetKeys(ctx, req.(*GetDeviceKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_UpdateKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).UpdateKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/UpdateKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).UpdateKeys(ctx, req.(*UpdateDeviceKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_DeleteKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).DeleteKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/DeleteKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).DeleteKeys(ctx, req.(*DeleteDeviceKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/Activate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Activate(ctx, req.(*ActivateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/GetActivation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetActivation(ctx, req.(*GetDeviceActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetRandomDevAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomDevAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetRandomDevAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/GetRandomDevAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetRandomDevAddr(ctx, req.(*GetRandomDevAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetFrameLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrameLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetFrameLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Device/GetFrameLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetFrameLogs(ctx, req.(*GetFrameLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Device_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Device",
	HandlerType: (*DeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Device_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Device_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Device_Delete_Handler,
		},
		{
			MethodName: "ListByApplicationID",
			Handler:    _Device_ListByApplicationID_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Device_Update_Handler,
		},
		{
			MethodName: "CreateKeys",
			Handler:    _Device_CreateKeys_Handler,
		},
		{
			MethodName: "GetKeys",
			Handler:    _Device_GetKeys_Handler,
		},
		{
			MethodName: "UpdateKeys",
			Handler:    _Device_UpdateKeys_Handler,
		},
		{
			MethodName: "DeleteKeys",
			Handler:    _Device_DeleteKeys_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _Device_Activate_Handler,
		},
		{
			MethodName: "GetActivation",
			Handler:    _Device_GetActivation_Handler,
		},
		{
			MethodName: "GetRandomDevAddr",
			Handler:    _Device_GetRandomDevAddr_Handler,
		},
		{
			MethodName: "GetFrameLogs",
			Handler:    _Device_GetFrameLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}

func init() { proto.RegisterFile("node.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xd7, 0xc5, 0xc9, 0xc5, 0x99, 0xd4, 0xfd, 0xb3, 0x6e, 0xe2, 0xeb, 0x35, 0x6d, 0xad, 0xeb,
	0x1f, 0x39, 0x29, 0xc4, 0x6a, 0xe9, 0x13, 0x6f, 0x21, 0xa6, 0x26, 0xb4, 0x2a, 0xd5, 0x85, 0x02,
	0x12, 0x20, 0xb4, 0xb9, 0x5b, 0x27, 0xa7, 0xdc, 0x3f, 0xee, 0x36, 0x09, 0x56, 0xa9, 0x90, 0x78,
	0x40, 0x3c, 0xf1, 0x00, 0x5f, 0x80, 0xaf, 0x80, 0xf8, 0x0c, 0x7c, 0x02, 0x84, 0x78, 0xe1, 0x91,
	0x2f, 0xc1, 0x1b, 0xda, 0xd9, 0x3d, 0xfb, 0xce, 0xbe, 0xb3, 0xf3, 0x82, 0x54, 0x9e, 0x7c, 0x33,
	0x3b, 0x37, 0xbf, 0xf9, 0xcd, 0xce, 0xce, 0xce, 0x19, 0x20, 0x8c, 0x5c, 0xb6, 0x1d, 0x27, 0x11,
	0x8f, 0x48, 0x8d, 0xc6, 0x9e, 0xb9, 0x71, 0x18, 0x45, 0x87, 0x3e, 0xeb, 0xd2, 0xd8, 0xeb, 0xd2,
	0x30, 0x8c, 0x38, 0xe5, 0x5e, 0x14, 0xa6, 0xd2, 0xc4, 0xba, 0x03, 0xd0, 0x63, 0xa7, 0x9e, 0xc3,
	0x9e, 0xb0, 0x61, 0x4a, 0xd6, 0x41, 0xa7, 0x71, 0xfc, 0x84, 0x0d, 0x0d, 0xad, 0xad, 0x75, 0x56,
	0x6c, 0x25, 0x59, 0xbf, 0x6a, 0xd0, 0xdc, 0x4d, 0x18, 0xe5, 0x4c, 0x1a, 0xdb, 0xec, 0xcb, 0x13,
	0x96, 0x72, 0x61, 0xef, 0xb2, 0xd3, 0x77, 0x5f, 0xec, 0x65, 0xf6, 0x52, 0x22, 0x04, 0x16, 0x43,
	0x1a, 0x30, 0x63, 0x05, 0xb5, 0xf8, 0x4c, 0xee, 0x40, 0x83, 0xc6, 0xb1, 0xef, 0x39, 0x88, 0xbf,
	0xd7, 0x33, 0x1a, 0x6d, 0xad, 0x53, 0xb3, 0x8b, 0x4a, 0xd2, 0x86, 0x55, 0x97, 0xa5, 0x4e, 0xe2,
	0xc5, 0x42, 0x61, 0x5c, 0x44, 0x07, 0x79, 0x15, 0xe9, 0xc0, 0x25, 0x17, 0x83, 0x78, 0x9e, 0x44,
	0x03, 0xcf, 0x67, 0x7b, 0x3d, 0x83, 0xa0, 0xd5, 0xa4, 0xda, 0x5a, 0x87, 0xab, 0xc5, 0xa0, 0xd3,
	0x38, 0x0a, 0x53, 0x66, 0x6d, 0xc1, 0xe5, 0x3e, 0xe3, 0xe7, 0x62, 0x62, 0xfd, 0xa2, 0xc1, 0x95,
	0x9c, 0xb1, 0xf4, 0xf0, 0x9a, 0xf3, 0x7e, 0x13, 0x9a, 0x3d, 0xe6, 0xb3, 0x73, 0x6e, 0x96, 0x48,
	0x53, 0xd1, 0x5c, 0xa5, 0xe9, 0x07, 0x0d, 0xda, 0x4f, 0xbd, 0x54, 0x71, 0x7f, 0x67, 0xb8, 0x93,
	0x0f, 0x38, 0x73, 0x3a, 0xc5, 0xae, 0x56, 0xc6, 0xee, 0x2a, 0x2c, 0xf9, 0x5e, 0xe0, 0x71, 0x44,
	0xae, 0xd9, 0x52, 0x10, 0x01, 0x45, 0x83, 0x41, 0xca, 0xb8, 0xb1, 0x80, 0x6a, 0x25, 0x09, 0x7d,
	0xca, 0x68, 0xe2, 0x1c, 0x19, 0x8b, 0x32, 0x50, 0x29, 0x59, 0x7f, 0x69, 0x70, 0x51, 0x06, 0x23,
	0xc2, 0xda, 0xe3, 0x2c, 0x78, 0xbd, 0x37, 0x82, 0xbc, 0x01, 0x57, 0x0a, 0xaa, 0x67, 0x22, 0xa4,
	0x26, 0xda, 0x4e, 0x2f, 0x58, 0x14, 0xc8, 0x38, 0xdd, 0xa3, 0x52, 0xbb, 0x09, 0xc0, 0x23, 0x4e,
	0xfd, 0xdd, 0xe8, 0x24, 0xcc, 0xf2, 0x97, 0xd3, 0x90, 0xfb, 0xa0, 0x27, 0x2c, 0x3d, 0xf1, 0x45,
	0x12, 0x6b, 0x9d, 0xd5, 0x87, 0xcd, 0x6d, 0x1a, 0x7b, 0xdb, 0xc5, 0x34, 0xd9, 0xca, 0x04, 0xcf,
	0xf1, 0x8b, 0xd8, 0xfd, 0xff, 0x9d, 0xe3, 0x62, 0xd0, 0xaa, 0x40, 0x0f, 0xa0, 0x95, 0x3f, 0xdf,
	0xa2, 0x83, 0xcd, 0x23, 0xd4, 0x05, 0x70, 0x47, 0xc6, 0x58, 0x76, 0xab, 0x0f, 0x2f, 0xe5, 0x32,
	0x86, 0x3e, 0x72, 0x26, 0x96, 0x09, 0xc6, 0x34, 0x86, 0xc2, 0xdf, 0x86, 0xab, 0xa3, 0xd6, 0x70,
	0x0e, 0x70, 0xeb, 0x3d, 0x58, 0x9b, 0xb0, 0x57, 0x7b, 0x5c, 0x8c, 0x4a, 0x9b, 0x1f, 0xd5, 0x01,
	0xb4, 0xf2, 0x19, 0xf9, 0xaf, 0x98, 0x4f, 0x63, 0x28, 0xe6, 0x0f, 0xa0, 0x95, 0x6f, 0x19, 0xe7,
	0x21, 0x6f, 0x82, 0x31, 0xfd, 0x8a, 0x72, 0xf7, 0xa7, 0x06, 0x6b, 0x3b, 0x0e, 0xf7, 0x4e, 0xcf,
	0x5d, 0x98, 0x06, 0x2c, 0xbb, 0xec, 0x74, 0xc7, 0x75, 0x13, 0xa4, 0xb2, 0x62, 0x67, 0xa2, 0x58,
	0xa1, 0x71, 0xbc, 0x2f, 0xee, 0xb0, 0x9a, 0x5c, 0x51, 0xa2, 0x58, 0x09, 0xcf, 0x8e, 0x71, 0x45,
	0xf6, 0x95, 0x4c, 0x14, 0x28, 0x83, 0xdd, 0x90, 0xbf, 0x88, 0x8d, 0xa5, 0xb6, 0xd6, 0x69, 0xd8,
	0x4a, 0x22, 0x26, 0xd4, 0xc5, 0x53, 0x2f, 0x3a, 0x0b, 0x0d, 0x1d, 0x57, 0x46, 0xb2, 0x38, 0x06,
	0xe9, 0xb1, 0x17, 0x3f, 0xde, 0x0d, 0xf9, 0xee, 0x11, 0x73, 0x8e, 0x8d, 0xe5, 0xb6, 0xd6, 0xa9,
	0xdb, 0x45, 0xa5, 0x65, 0xc0, 0xfa, 0x24, 0x31, 0xc5, 0xf9, 0x11, 0x98, 0xa3, 0x62, 0x50, 0x26,
	0x5e, 0x14, 0xce, 0xcb, 0xe2, 0x6f, 0x1a, 0x5c, 0x2f, 0x7d, 0x4d, 0x55, 0x52, 0x2e, 0x2f, 0x5a,
	0x65, 0x5e, 0x16, 0x2a, 0xf3, 0x52, 0xab, 0xca, 0xcb, 0x62, 0x65, 0x5e, 0x96, 0xe6, 0xe5, 0x45,
	0x2f, 0xcb, 0xcb, 0x03, 0x68, 0xf5, 0x19, 0xb7, 0x69, 0xe8, 0x46, 0x41, 0x4f, 0x46, 0x38, 0x8f,
	0xfa, 0x23, 0x30, 0xa6, 0x5f, 0x99, 0x47, 0xdb, 0xfa, 0x14, 0x9a, 0x7d, 0xc6, 0x1f, 0x27, 0x34,
	0x60, 0x4f, 0xa3, 0xc3, 0xb9, 0xa7, 0x64, 0x74, 0x51, 0x2d, 0x94, 0x5f, 0x54, 0xb5, 0xfc, 0x45,
	0x65, 0x7d, 0x8e, 0x0d, 0x20, 0xe7, 0xbc, 0xb2, 0x67, 0x2f, 0x15, 0x7a, 0xf6, 0xdd, 0x89, 0x9e,
	0xdd, 0xc0, 0x73, 0x98, 0xf9, 0x19, 0x75, 0xeb, 0x9f, 0x35, 0xa8, 0x67, 0x4a, 0xb2, 0x01, 0x2b,
	0x0e, 0x36, 0x22, 0x77, 0x87, 0xab, 0xa0, 0xc7, 0x0a, 0xb2, 0x09, 0x2b, 0xc9, 0x57, 0x7b, 0xe1,
	0x20, 0xda, 0x67, 0x99, 0xd3, 0x55, 0x74, 0x6a, 0x7f, 0x22, 0xb4, 0xf6, 0x78, 0x95, 0xdc, 0x06,
	0x9d, 0xa3, 0x80, 0x64, 0x32, 0xbb, 0x0f, 0xa5, 0x9d, 0x5a, 0x22, 0xf7, 0xe0, 0x62, 0x7c, 0x34,
	0x7c, 0x4e, 0x87, 0x7e, 0x44, 0xdd, 0xf7, 0xf7, 0x3f, 0x78, 0xa6, 0x8e, 0xcc, 0x84, 0xd6, 0xfa,
	0x4e, 0x83, 0x7a, 0x8f, 0x72, 0x6a, 0x53, 0x8e, 0xb4, 0x83, 0xc8, 0x3d, 0xf1, 0xb1, 0x24, 0x55,
	0x8c, 0x39, 0x8d, 0xa0, 0x70, 0x40, 0x43, 0xf7, 0x63, 0xcf, 0xe5, 0x47, 0x98, 0xe0, 0x86, 0x3d,
	0x56, 0x10, 0x0b, 0x2e, 0xa4, 0x71, 0xc2, 0xa8, 0xfb, 0x98, 0x3a, 0x3c, 0x4a, 0x30, 0xba, 0x86,
	0x5d, 0xd0, 0x89, 0x7d, 0x3e, 0xf0, 0x78, 0x42, 0x39, 0x53, 0x15, 0x99, 0x89, 0xd6, 0x3f, 0x1a,
	0xe8, 0x92, 0xab, 0x30, 0x72, 0x8e, 0x68, 0x18, 0x32, 0x5f, 0xa5, 0x3e, 0x13, 0x45, 0xdd, 0x3a,
	0x91, 0xcb, 0x44, 0xb0, 0xea, 0x10, 0x8c, 0x64, 0x11, 0xdc, 0x20, 0x11, 0xd5, 0x11, 0x3a, 0x43,
	0xb5, 0xcd, 0x63, 0x85, 0xf0, 0xe9, 0x47, 0x36, 0xdd, 0x7f, 0x66, 0x23, 0xb0, 0x66, 0x67, 0xa2,
	0xb8, 0x22, 0x93, 0x34, 0xf5, 0xf0, 0x1c, 0x2c, 0xd9, 0xf8, 0x2c, 0x74, 0xdc, 0x0b, 0x18, 0x96,
	0xfe, 0x8a, 0x8d, 0xcf, 0xc2, 0xbf, 0xf8, 0x4d, 0x39, 0x0d, 0x62, 0xec, 0x15, 0x0d, 0x7b, 0xac,
	0x20, 0x9b, 0x50, 0x77, 0x55, 0x1a, 0x8d, 0x3a, 0x6e, 0x8b, 0xac, 0x89, 0x2c, 0xb7, 0xf6, 0x68,
	0x99, 0x5c, 0x86, 0x5a, 0x40, 0x1d, 0x75, 0x25, 0x8b, 0x47, 0xeb, 0x0f, 0x0d, 0x74, 0xb9, 0x7f,
	0x05, 0x86, 0xda, 0x2c, 0x86, 0x0b, 0x93, 0x0c, 0xdb, 0xb0, 0xea, 0x05, 0x01, 0x73, 0x3d, 0xca,
	0x99, 0x2f, 0x33, 0x50, 0xb7, 0xf3, 0xaa, 0x0c, 0x78, 0x71, 0x04, 0x2c, 0x4e, 0x4b, 0x1c, 0x9d,
	0xb1, 0x44, 0x91, 0x97, 0x42, 0x91, 0xa9, 0x3e, 0x8b, 0xe9, 0xf2, 0x4c, 0xa6, 0x0f, 0x7f, 0x5c,
	0x05, 0x5d, 0x76, 0x3a, 0xf2, 0x11, 0xe8, 0xf2, 0x1a, 0x26, 0x06, 0x5a, 0x97, 0x7c, 0x8c, 0x98,
	0xd7, 0x4a, 0x56, 0x54, 0xb3, 0x6d, 0x7d, 0xfb, 0xfb, 0xdf, 0x3f, 0x2d, 0x5c, 0xb1, 0x2e, 0xe0,
	0x57, 0x90, 0xbc, 0xe4, 0xd2, 0xb7, 0xb5, 0x2d, 0xb2, 0x0f, 0xb5, 0x3e, 0xe3, 0x64, 0x0d, 0x5f,
	0x9d, 0xfc, 0x28, 0x30, 0xd7, 0x27, 0xd5, 0xca, 0xdd, 0x0d, 0x74, 0xd7, 0x22, 0x6b, 0x79, 0x77,
	0xdd, 0x97, 0xb2, 0x87, 0xbc, 0x22, 0x9f, 0x89, 0xb0, 0xc5, 0x55, 0xa7, 0x82, 0x2d, 0x19, 0xc6,
	0x55, 0xb0, 0xa5, 0x73, 0xb7, 0xf2, 0xbe, 0x55, 0xe1, 0xfd, 0x7b, 0x0d, 0x9a, 0x62, 0xb0, 0x9b,
	0x18, 0xc8, 0xc9, 0x5d, 0xf4, 0x38, 0x6f, 0x60, 0x37, 0x5b, 0x13, 0x66, 0xe3, 0x3b, 0x1d, 0x61,
	0xef, 0x93, 0x4d, 0xf9, 0xa5, 0x38, 0x7e, 0x37, 0xed, 0xbe, 0x2c, 0xcc, 0x76, 0xaf, 0xb2, 0x98,
	0xc8, 0x17, 0xa0, 0xcb, 0x11, 0x41, 0x11, 0x2d, 0x19, 0x2d, 0x15, 0xd1, 0xd2, 0xf9, 0xad, 0x8d,
	0x88, 0xa6, 0x59, 0x4e, 0x54, 0x6c, 0x4f, 0x0c, 0x20, 0xf7, 0x13, 0xbf, 0x4e, 0x37, 0xa6, 0x36,
	0x38, 0x37, 0x78, 0x98, 0x37, 0x2a, 0x56, 0x15, 0xd8, 0x5d, 0x04, 0xbb, 0x65, 0x99, 0xa5, 0x60,
	0xdd, 0x63, 0x36, 0xc4, 0x82, 0x70, 0x61, 0xb9, 0xcf, 0x38, 0xc2, 0x5d, 0x2b, 0xee, 0x7e, 0x1e,
	0xcb, 0x2c, 0x5b, 0x52, 0x40, 0x16, 0x02, 0x6d, 0x90, 0x19, 0x40, 0x82, 0x97, 0xcc, 0x48, 0x8e,
	0x57, 0xc5, 0x40, 0xa7, 0x78, 0x55, 0x8e, 0x62, 0x8a, 0x97, 0x39, 0x87, 0x57, 0x20, 0xbe, 0xf3,
	0x45, 0xb1, 0xe5, 0x10, 0x2b, 0x46, 0x38, 0x85, 0x58, 0x39, 0xad, 0x29, 0x82, 0x5b, 0xb3, 0x08,
	0x86, 0x50, 0xcf, 0xe6, 0x1e, 0x22, 0x93, 0x55, 0x3a, 0xdf, 0x99, 0xd7, 0x4b, 0xd7, 0x14, 0xd0,
	0x26, 0x02, 0xdd, 0xb6, 0x6e, 0x96, 0x03, 0x51, 0xf5, 0x96, 0xa0, 0xf7, 0x35, 0x34, 0xfa, 0x8c,
	0x8f, 0x07, 0x22, 0x72, 0xab, 0xb8, 0x43, 0x53, 0x13, 0x96, 0xd9, 0xae, 0x36, 0x50, 0xf0, 0x1d,
	0x84, 0xb7, 0x48, 0x7b, 0x26, 0xbc, 0x00, 0xfb, 0x06, 0xff, 0x50, 0x28, 0x8c, 0x26, 0x2a, 0xc5,
	0x15, 0x43, 0x8e, 0x4a, 0x71, 0xd5, 0x3c, 0x63, 0x6d, 0x23, 0x74, 0xc7, 0xba, 0x57, 0x0e, 0x7d,
	0x38, 0x09, 0xe6, 0xc1, 0x85, 0xfc, 0x20, 0xa2, 0x8e, 0x63, 0xc9, 0xe0, 0x63, 0x5e, 0x2b, 0x59,
	0x51, 0xa0, 0x77, 0x10, 0xf4, 0x26, 0xd9, 0x28, 0x07, 0x1d, 0x88, 0x17, 0xd2, 0x03, 0x1d, 0xff,
	0x37, 0x7a, 0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0xf6, 0xff, 0xc0, 0x68, 0x12, 0x00,
	0x00,
}
